// Package brain provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package brain

import (
	"time"
)

// Defines values for EntriesDeleteParamsConfirm.
const (
	True EntriesDeleteParamsConfirm = true
)

// Valid indicates whether the value is a known member of the EntriesDeleteParamsConfirm enum.
func (e EntriesDeleteParamsConfirm) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// AttachEntryAttachmentRequest defines model for AttachEntryAttachmentRequest.
type AttachEntryAttachmentRequest struct {
	Attachment AttachmentReference `json:"attachment"`
}

// AttachEntryAttachmentResponse defines model for AttachEntryAttachmentResponse.
type AttachEntryAttachmentResponse struct {
	Attachments *[]AttachmentReference `json:"attachments"`
	EntryId     string                 `json:"entry_id"`
	Path        string                 `json:"path"`
}

// Attachment defines model for Attachment.
type Attachment struct {
	ContentType string               `json:"content_type"`
	Created     *string              `json:"created,omitempty"`
	Derived     *[]AttachmentDerived `json:"derived,omitempty"`
	Filename    string               `json:"filename"`
	Id          string               `json:"id"`
	Metadata    *map[string]string   `json:"metadata,omitempty"`
	Modified    *string              `json:"modified,omitempty"`
	Sha256      *string              `json:"sha256,omitempty"`
	Size        int64                `json:"size"`
	StorageKey  *string              `json:"storage_key,omitempty"`
}

// AttachmentDeletionResponse defines model for AttachmentDeletionResponse.
type AttachmentDeletionResponse struct {
	Deleted bool `json:"deleted"`
}

// AttachmentDerived defines model for AttachmentDerived.
type AttachmentDerived struct {
	ContentType *string `json:"content_type,omitempty"`
	Created     *string `json:"created,omitempty"`
	Id          string  `json:"id"`
	Kind        string  `json:"kind"`
	Size        *int64  `json:"size,omitempty"`
	StorageKey  *string `json:"storage_key,omitempty"`
}

// AttachmentDerivedText defines model for AttachmentDerivedText.
type AttachmentDerivedText struct {
	ContentType *string            `json:"content_type,omitempty"`
	Created     *string            `json:"created,omitempty"`
	Error       *string            `json:"error,omitempty"`
	Id          *string            `json:"id,omitempty"`
	Kind        *string            `json:"kind,omitempty"`
	Metadata    *map[string]string `json:"metadata,omitempty"`
	Modified    *string            `json:"modified,omitempty"`
	Status      string             `json:"status"`
	Text        *string            `json:"text,omitempty"`
}

// AttachmentExtractionRequest defines model for AttachmentExtractionRequest.
type AttachmentExtractionRequest struct {
	AttachmentId string             `json:"attachment_id"`
	ContentType  string             `json:"content_type"`
	EntryId      *string            `json:"entry_id,omitempty"`
	Filename     *string            `json:"filename,omitempty"`
	Metadata     *map[string]string `json:"metadata,omitempty"`
	ProjectId    *string            `json:"project_id,omitempty"`
	Size         *int64             `json:"size,omitempty"`
}

// AttachmentExtractionResult defines model for AttachmentExtractionResult.
type AttachmentExtractionResult struct {
	Attachment    Attachment               `json:"attachment"`
	DerivedText   AttachmentDerivedText    `json:"derived_text"`
	LinkedEntries *[]AttachmentLinkedEntry `json:"linked_entries,omitempty"`
}

// AttachmentLinkedEntry defines model for AttachmentLinkedEntry.
type AttachmentLinkedEntry struct {
	Path string  `json:"path"`
	Role *string `json:"role,omitempty"`
}

// AttachmentReference defines model for AttachmentReference.
type AttachmentReference struct {
	Caption     *string                `json:"caption,omitempty"`
	ContentType *string                `json:"content_type,omitempty"`
	Derived     *[]AttachmentDerived   `json:"derived,omitempty"`
	DerivedText *AttachmentDerivedText `json:"derived_text,omitempty"`
	DownloadUrl *string                `json:"download_url,omitempty"`
	Filename    *string                `json:"filename,omitempty"`
	Id          string                 `json:"id"`
	Metadata    *map[string]string     `json:"metadata,omitempty"`
	Role        *string                `json:"role,omitempty"`
	Sha256      *string                `json:"sha256,omitempty"`
	Size        *int64                 `json:"size,omitempty"`
	TextUrl     *string                `json:"text_url,omitempty"`
}

// AutomationAction defines model for AutomationAction.
type AutomationAction struct {
	Agent              *string `json:"agent,omitempty"`
	Command            *string `json:"command,omitempty"`
	CompleteOnIdle     *bool   `json:"complete_on_idle,omitempty"`
	DirectPrompt       *string `json:"direct_prompt,omitempty"`
	ExecutionMode      *string `json:"execution_mode,omitempty"`
	Executor           *string `json:"executor,omitempty"`
	Model              *string `json:"model,omitempty"`
	RequiresCapability *string `json:"requires_capability,omitempty"`
	SessionMode        *string `json:"session_mode,omitempty"`
	SetStatus          *string `json:"set_status,omitempty"`
	TargetWorkdir      *string `json:"target_workdir,omitempty"`
	Timeout            *string `json:"timeout,omitempty"`
	Type               string  `json:"type"`
}

// AutomationRetry defines model for AutomationRetry.
type AutomationRetry struct {
	Backoff     *string `json:"backoff,omitempty"`
	Delay       *string `json:"delay,omitempty"`
	MaxAttempts *int    `json:"max_attempts,omitempty"`
}

// BacklinkEntry defines model for BacklinkEntry.
type BacklinkEntry struct {
	Id    string `json:"id"`
	Path  string `json:"path"`
	Title string `json:"title"`
	Type  string `json:"type"`
}

// BrainEntry defines model for BrainEntry.
type BrainEntry struct {
	AccessCount             *int                        `json:"access_count,omitempty"`
	Action                  *AutomationAction           `json:"action,omitempty"`
	Agent                   *string                     `json:"agent,omitempty"`
	Attachments             *[]AttachmentReference      `json:"attachments,omitempty"`
	AttemptCount            *int                        `json:"attempt_count,omitempty"`
	AutomationRunId         *string                     `json:"automation_run_id,omitempty"`
	Backlinks               *[]BacklinkEntry            `json:"backlinks,omitempty"`
	CheckoutMode            *string                     `json:"checkout_mode,omitempty"`
	CompleteOnIdle          *bool                       `json:"complete_on_idle,omitempty"`
	CompletedAt             *string                     `json:"completed_at,omitempty"`
	Content                 string                      `json:"content"`
	Created                 *string                     `json:"created,omitempty"`
	DeliveryMode            *string                     `json:"delivery_mode,omitempty"`
	DeliveryVerification    *DeliveryVerification       `json:"delivery_verification,omitempty"`
	DependsOn               *[]string                   `json:"depends_on,omitempty"`
	DirectPrompt            *string                     `json:"direct_prompt,omitempty"`
	EmbeddingStatus         *string                     `json:"embedding_status,omitempty"`
	ExecutionMode           *string                     `json:"execution_mode,omitempty"`
	Executor                *string                     `json:"executor,omitempty"`
	ExpiresAt               *string                     `json:"expires_at,omitempty"`
	Extensions              *[]string                   `json:"extensions,omitempty"`
	FeatureDependsOn        *[]string                   `json:"feature_depends_on,omitempty"`
	FeatureExpiresAt        *string                     `json:"feature_expires_at,omitempty"`
	FeatureId               *string                     `json:"feature_id,omitempty"`
	FeaturePriority         *string                     `json:"feature_priority,omitempty"`
	FeatureRunOnceAt        *string                     `json:"feature_run_once_at,omitempty"`
	FeatureSchedule         *string                     `json:"feature_schedule,omitempty"`
	FeatureStartsAt         *string                     `json:"feature_starts_at,omitempty"`
	FeatureTimezone         *string                     `json:"feature_timezone,omitempty"`
	Generated               *bool                       `json:"generated,omitempty"`
	GeneratedBy             *string                     `json:"generated_by,omitempty"`
	GeneratedKey            *string                     `json:"generated_key,omitempty"`
	GeneratedKind           *string                     `json:"generated_kind,omitempty"`
	GitBranch               *string                     `json:"git_branch,omitempty"`
	GitRemote               *string                     `json:"git_remote,omitempty"`
	Goal                    *GoalConfig                 `json:"goal,omitempty"`
	Id                      string                      `json:"id"`
	LastFailedAt            *string                     `json:"last_failed_at,omitempty"`
	LastVerified            *string                     `json:"last_verified,omitempty"`
	MachineAffinity         *string                     `json:"machine_affinity,omitempty"`
	MaxRuns                 *int                        `json:"max_runs,omitempty"`
	MergePolicy             *string                     `json:"merge_policy,omitempty"`
	MergeStrategy           *string                     `json:"merge_strategy,omitempty"`
	MergeTargetBranch       *string                     `json:"merge_target_branch,omitempty"`
	Model                   *string                     `json:"model,omitempty"`
	Modified                *string                     `json:"modified,omitempty"`
	NextRun                 *string                     `json:"next_run,omitempty"`
	OpenPrBeforeMerge       *bool                       `json:"open_pr_before_merge,omitempty"`
	OriginClientId          *string                     `json:"origin_client_id,omitempty"`
	OriginMachineId         *string                     `json:"origin_machine_id,omitempty"`
	OriginPath              *string                     `json:"origin_path,omitempty"`
	ParentId                *string                     `json:"parent_id,omitempty"`
	Path                    string                      `json:"path"`
	Priority                *string                     `json:"priority,omitempty"`
	ProjectId               *string                     `json:"project_id,omitempty"`
	Reminder                *ReminderConfig             `json:"reminder,omitempty"`
	RemoteBranchPolicy      *string                     `json:"remote_branch_policy,omitempty"`
	RequiresCapability      *[]string                   `json:"requires_capability,omitempty"`
	ResumeExecutorOverride  *string                     `json:"resume_executor_override,omitempty"`
	ResumeInjectedContext   *string                     `json:"resume_injected_context,omitempty"`
	ResumeMode              *string                     `json:"resume_mode,omitempty"`
	ResumePreferSameSession *bool                       `json:"resume_prefer_same_session,omitempty"`
	ResumeRequested         *bool                       `json:"resume_requested,omitempty"`
	ResumeRequestedAt       *string                     `json:"resume_requested_at,omitempty"`
	Retry                   *AutomationRetry            `json:"retry,omitempty"`
	Revision                *string                     `json:"revision,omitempty"`
	RunFinalizations        *map[string]RunFinalization `json:"run_finalizations,omitempty"`
	RunOnceAt               *string                     `json:"run_once_at,omitempty"`
	Runs                    *[]CronRun                  `json:"runs,omitempty"`
	Schedule                *string                     `json:"schedule,omitempty"`
	ScheduleEnabled         *bool                       `json:"schedule_enabled,omitempty"`
	SessionMode             *string                     `json:"session_mode,omitempty"`
	Sessions                *map[string]SessionInfo     `json:"sessions,omitempty"`
	StartsAt                *string                     `json:"starts_at,omitempty"`
	Status                  string                      `json:"status"`
	Tags                    *[]string                   `json:"tags"`
	TargetWorkdir           *string                     `json:"target_workdir,omitempty"`
	Timezone                *string                     `json:"timezone,omitempty"`
	Title                   string                      `json:"title"`
	Trigger                 *TriggerConfig              `json:"trigger,omitempty"`
	Type                    string                      `json:"type"`
	UserOriginalRequest     *string                     `json:"user_original_request,omitempty"`
	Workdir                 *string                     `json:"workdir,omitempty"`
}

// BulkDeleteRequest defines model for BulkDeleteRequest.
type BulkDeleteRequest struct {
	DryRun *bool             `json:"dry_run,omitempty"`
	Filter *BulkUpdateFilter `json:"filter,omitempty"`
	Force  *bool             `json:"force,omitempty"`
	Limit  *int              `json:"limit,omitempty"`
	Paths  *[]string         `json:"paths,omitempty"`
}

// BulkDeleteResponse defines model for BulkDeleteResponse.
type BulkDeleteResponse struct {
	Deleted      int                 `json:"deleted"`
	DryRun       bool                `json:"dry_run"`
	Failed       int                 `json:"failed"`
	MatchedTotal *int                `json:"matched_total,omitempty"`
	Results      *[]BulkUpdateResult `json:"results"`
	Total        int                 `json:"total"`
	Truncated    *bool               `json:"truncated,omitempty"`
}

// BulkUpdateEntry defines model for BulkUpdateEntry.
type BulkUpdateEntry struct {
	Path    string             `json:"path"`
	Updates UpdateEntryRequest `json:"updates"`
}

// BulkUpdateFilter defines model for BulkUpdateFilter.
type BulkUpdateFilter struct {
	Agent         *string   `json:"agent,omitempty"`
	ExecutionMode *string   `json:"execution_mode,omitempty"`
	Executor      *string   `json:"executor,omitempty"`
	FeatureId     *string   `json:"feature_id,omitempty"`
	GeneratedBy   *string   `json:"generated_by,omitempty"`
	GeneratedKey  *string   `json:"generated_key,omitempty"`
	Priority      *string   `json:"priority,omitempty"`
	Project       *string   `json:"project,omitempty"`
	Status        *string   `json:"status,omitempty"`
	Tags          *[]string `json:"tags,omitempty"`
	Type          *string   `json:"type,omitempty"`
}

// BulkUpdateRequest defines model for BulkUpdateRequest.
type BulkUpdateRequest struct {
	DryRun  *bool               `json:"dry_run,omitempty"`
	Entries *[]BulkUpdateEntry  `json:"entries,omitempty"`
	Filter  *BulkUpdateFilter   `json:"filter,omitempty"`
	Force   *bool               `json:"force,omitempty"`
	Limit   *int                `json:"limit,omitempty"`
	Updates *UpdateEntryRequest `json:"updates,omitempty"`
}

// BulkUpdateResponse defines model for BulkUpdateResponse.
type BulkUpdateResponse struct {
	DryRun       bool                `json:"dry_run"`
	Failed       int                 `json:"failed"`
	MatchedTotal *int                `json:"matched_total,omitempty"`
	Results      *[]BulkUpdateResult `json:"results"`
	Total        int                 `json:"total"`
	Truncated    *bool               `json:"truncated,omitempty"`
	Updated      int                 `json:"updated"`
}

// BulkUpdateResult defines model for BulkUpdateResult.
type BulkUpdateResult struct {
	Error  *string `json:"error,omitempty"`
	Id     string  `json:"id"`
	Path   string  `json:"path"`
	Status string  `json:"status"`
	Title  string  `json:"title"`
}

// CreateAttachmentResponse defines model for CreateAttachmentResponse.
type CreateAttachmentResponse struct {
	Attachment Attachment `json:"attachment"`
}

// CreateEntryRequest defines model for CreateEntryRequest.
type CreateEntryRequest struct {
	Action              *AutomationAction           `json:"action,omitempty"`
	Agent               *string                     `json:"agent,omitempty"`
	AssignmentIntent    *string                     `json:"assignment_intent,omitempty"`
	Attachments         *[]AttachmentReference      `json:"attachments,omitempty"`
	AutomationRunId     *string                     `json:"automation_run_id,omitempty"`
	CheckoutMode        *string                     `json:"checkout_mode,omitempty"`
	CompleteOnIdle      *bool                       `json:"complete_on_idle,omitempty"`
	Content             string                      `json:"content"`
	DeliveryMode        *string                     `json:"delivery_mode,omitempty"`
	DependsOn           *[]string                   `json:"depends_on,omitempty"`
	DirectPrompt        *string                     `json:"direct_prompt,omitempty"`
	ExecutionMode       *string                     `json:"execution_mode,omitempty"`
	Executor            *string                     `json:"executor,omitempty"`
	ExpiresAt           *string                     `json:"expires_at,omitempty"`
	Extensions          *[]string                   `json:"extensions,omitempty"`
	FeatureDependsOn    *[]string                   `json:"feature_depends_on,omitempty"`
	FeatureExpiresAt    *string                     `json:"feature_expires_at,omitempty"`
	FeatureId           *string                     `json:"feature_id,omitempty"`
	FeaturePriority     *string                     `json:"feature_priority,omitempty"`
	FeatureRunOnceAt    *string                     `json:"feature_run_once_at,omitempty"`
	FeatureSchedule     *string                     `json:"feature_schedule,omitempty"`
	FeatureStartsAt     *string                     `json:"feature_starts_at,omitempty"`
	FeatureTimezone     *string                     `json:"feature_timezone,omitempty"`
	Generated           *bool                       `json:"generated,omitempty"`
	GeneratedBy         *string                     `json:"generated_by,omitempty"`
	GeneratedKey        *string                     `json:"generated_key,omitempty"`
	GeneratedKind       *string                     `json:"generated_kind,omitempty"`
	GitBranch           *string                     `json:"git_branch,omitempty"`
	GitRemote           *string                     `json:"git_remote,omitempty"`
	Global              *bool                       `json:"global,omitempty"`
	Goal                *GoalConfig                 `json:"goal,omitempty"`
	MachineAffinity     *string                     `json:"machine_affinity,omitempty"`
	MaxRuns             *int                        `json:"max_runs,omitempty"`
	MergePolicy         *string                     `json:"merge_policy,omitempty"`
	MergeStrategy       *string                     `json:"merge_strategy,omitempty"`
	MergeTargetBranch   *string                     `json:"merge_target_branch,omitempty"`
	Model               *string                     `json:"model,omitempty"`
	NextRun             *string                     `json:"next_run,omitempty"`
	OpenPrBeforeMerge   *bool                       `json:"open_pr_before_merge,omitempty"`
	OriginClientId      *string                     `json:"origin_client_id,omitempty"`
	OriginMachineId     *string                     `json:"origin_machine_id,omitempty"`
	OriginPath          *string                     `json:"origin_path,omitempty"`
	Priority            *string                     `json:"priority,omitempty"`
	Project             *string                     `json:"project,omitempty"`
	RelatedEntries      *[]string                   `json:"relatedEntries,omitempty"`
	Reminder            *ReminderConfig             `json:"reminder,omitempty"`
	RemoteBranchPolicy  *string                     `json:"remote_branch_policy,omitempty"`
	RequiresCapability  *[]string                   `json:"requires_capability,omitempty"`
	Retry               *AutomationRetry            `json:"retry,omitempty"`
	RunFinalizations    *map[string]RunFinalization `json:"run_finalizations,omitempty"`
	RunOnceAt           *string                     `json:"run_once_at,omitempty"`
	RunnerId            *string                     `json:"runner_id,omitempty"`
	Runs                *[]CronRun                  `json:"runs,omitempty"`
	Schedule            *string                     `json:"schedule,omitempty"`
	ScheduleEnabled     *bool                       `json:"schedule_enabled,omitempty"`
	SessionMode         *string                     `json:"session_mode,omitempty"`
	StartsAt            *string                     `json:"starts_at,omitempty"`
	Status              *string                     `json:"status,omitempty"`
	Tags                *[]string                   `json:"tags,omitempty"`
	TargetWorkdir       *string                     `json:"target_workdir,omitempty"`
	Timezone            *string                     `json:"timezone,omitempty"`
	Title               string                      `json:"title"`
	Trigger             *TriggerConfig              `json:"trigger,omitempty"`
	Type                string                      `json:"type"`
	UserOriginalRequest *string                     `json:"user_original_request,omitempty"`
	Workdir             *string                     `json:"workdir,omitempty"`
}

// CreateEntryResponse defines model for CreateEntryResponse.
type CreateEntryResponse struct {
	Id     string    `json:"id"`
	Link   string    `json:"link"`
	Path   string    `json:"path"`
	Status string    `json:"status"`
	Tags   *[]string `json:"tags,omitempty"`
	Title  string    `json:"title"`
	Type   string    `json:"type"`
}

// CronRun defines model for CronRun.
type CronRun struct {
	Completed  *string `json:"completed,omitempty"`
	Duration   *int    `json:"duration,omitempty"`
	FailedTask *string `json:"failed_task,omitempty"`
	RunId      string  `json:"run_id"`
	SkipReason *string `json:"skip_reason,omitempty"`
	Started    string  `json:"started"`
	Status     string  `json:"status"`
	Tasks      *int    `json:"tasks,omitempty"`
}

// DeliveryEvidence defines model for DeliveryEvidence.
type DeliveryEvidence struct {
	Checks               *map[string]string `json:"checks"`
	Head                 string             `json:"head"`
	IntegrationArtifact  *string            `json:"integration_artifact,omitempty"`
	IntegrationPassed    bool               `json:"integration_passed"`
	IntegrationReference *string            `json:"integration_reference,omitempty"`
	IntegrationVerifier  *string            `json:"integration_verifier,omitempty"`
	MergeCommit          string             `json:"merge_commit"`
	Merged               bool               `json:"merged"`
	ReviewAccepted       bool               `json:"review_accepted"`
	Source               string             `json:"source"`
	Target               string             `json:"target"`
	VerifiedAt           time.Time          `json:"verified_at"`
	Verifier             string             `json:"verifier"`
}

// DeliveryVerification defines model for DeliveryVerification.
type DeliveryVerification struct {
	Evidence          *DeliveryEvidence `json:"evidence,omitempty"`
	Head              string            `json:"head"`
	PullRequest       int               `json:"pull_request"`
	Repository        string            `json:"repository"`
	Required          string            `json:"required"`
	RequiredChecks    *[]string         `json:"required_checks"`
	Revision          int               `json:"revision"`
	Target            string            `json:"target"`
	VerificationError *string           `json:"verification_error,omitempty"`
}

// DispatchLease defines model for DispatchLease.
type DispatchLease struct {
	AckedAt           *int64  `json:"acked_at,omitempty"`
	AssignedMachineId string  `json:"assigned_machine_id"`
	AssignedRunnerId  string  `json:"assigned_runner_id"`
	ExpiresAt         int64   `json:"expires_at"`
	Id                *string `json:"id,omitempty"`
	LastError         *string `json:"last_error,omitempty"`
	LeaseId           string  `json:"leaseId"`
	ProjectId         string  `json:"project_id"`
	PushedAt          int64   `json:"pushed_at"`
	RejectedAt        *int64  `json:"rejected_at,omitempty"`
	State             string  `json:"state"`
	TaskId            string  `json:"task_id"`
}

// EmbeddingHealthStatus defines model for EmbeddingHealthStatus.
type EmbeddingHealthStatus struct {
	Enabled  bool    `json:"enabled"`
	Model    *string `json:"model,omitempty"`
	Provider *string `json:"provider,omitempty"`
	Status   string  `json:"status"`
}

// GoalConfig defines model for GoalConfig.
type GoalConfig struct {
	BlockedStatuses  *[]string     `json:"blocked_statuses,omitempty"`
	CompleteStatuses *[]string     `json:"complete_statuses,omitempty"`
	Criteria         *string       `json:"criteria,omitempty"`
	Id               string        `json:"id"`
	Steering         *GoalSteering `json:"steering,omitempty"`
	TaskId           *string       `json:"task_id,omitempty"`
	TriggerSource    *string       `json:"trigger_source,omitempty"`
	Validation       *string       `json:"validation,omitempty"`
	Workdir          *string       `json:"workdir,omitempty"`
}

// GoalSteering defines model for GoalSteering.
type GoalSteering struct {
	CooldownMinutes *int  `json:"cooldown_minutes,omitempty"`
	Enabled         *bool `json:"enabled,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Embedding EmbeddingHealthStatus `json:"embedding"`
	Status    string                `json:"status"`
	Timestamp time.Time             `json:"timestamp"`
}

// LegacyErrorResponse Existing REST error envelope; SDKs adapt HTTP status to a machine code and preserve field details without changing the server wire format.
type LegacyErrorResponse struct {
	// Code Optional future-compatible machine code; legacy endpoints usually omit it.
	Code    *string             `json:"code,omitempty"`
	Details *[]ValidationDetail `json:"details,omitempty"`
	Error   string              `json:"error"`
	Message string              `json:"message"`

	// RequestId Optional fallback when X-Request-ID is absent.
	RequestId *string `json:"request_id,omitempty"`
}

// ListAttachmentsResponse defines model for ListAttachmentsResponse.
type ListAttachmentsResponse struct {
	Attachments *[]Attachment `json:"attachments"`
	Total       int           `json:"total"`
}

// ListEntriesResponse defines model for ListEntriesResponse.
type ListEntriesResponse struct {
	Entries   *[]BrainEntry `json:"entries"`
	Limit     int           `json:"limit"`
	Offset    int           `json:"offset"`
	Total     int           `json:"total"`
	Truncated *bool         `json:"truncated,omitempty"`
}

// MoveEntryRequest defines model for MoveEntryRequest.
type MoveEntryRequest struct {
	Project string `json:"project"`
}

// MoveResult defines model for MoveResult.
type MoveResult struct {
	From    string `json:"from"`
	Id      string `json:"id"`
	NewPath string `json:"newPath"`
	OldPath string `json:"oldPath"`
	Project string `json:"project"`
	Success bool   `json:"success"`
	Title   string `json:"title"`
	To      string `json:"to"`
}

// PlacementReason defines model for PlacementReason.
type PlacementReason struct {
	CreatedAt      int64   `json:"created_at"`
	Decision       string  `json:"decision"`
	Id             *int64  `json:"id,omitempty"`
	MachineId      *string `json:"machine_id,omitempty"`
	MissingLabels  *string `json:"missing_labels,omitempty"`
	ProjectId      string  `json:"project_id"`
	Reason         *string `json:"reason,omitempty"`
	RequiredLabels *string `json:"required_labels,omitempty"`
	RunnerId       *string `json:"runner_id,omitempty"`
	RunnerLabels   *string `json:"runner_labels,omitempty"`
	TaskId         string  `json:"task_id"`
}

// ReminderConfig defines model for ReminderConfig.
type ReminderConfig struct {
	Action          *string `json:"action,omitempty"`
	Agent           *string `json:"agent,omitempty"`
	ExecutionMode   *string `json:"execution_mode,omitempty"`
	Executor        *string `json:"executor,omitempty"`
	FireCount       *int    `json:"fire_count,omitempty"`
	FiredAt         *string `json:"fired_at,omitempty"`
	GeneratedTaskId *string `json:"generated_task_id,omitempty"`
	Id              string  `json:"id"`
	Model           *string `json:"model,omitempty"`
	Prompt          *string `json:"prompt,omitempty"`
	RemindAt        *string `json:"remind_at,omitempty"`
	Repeat          *string `json:"repeat,omitempty"`
	RepeatUntil     *string `json:"repeat_until,omitempty"`
	TargetWorkdir   *string `json:"target_workdir,omitempty"`
	Timezone        *string `json:"timezone,omitempty"`
}

// ResolvedTask defines model for ResolvedTask.
type ResolvedTask struct {
	AbandonReason           *string                 `json:"abandon_reason,omitempty"`
	Action                  *AutomationAction       `json:"action,omitempty"`
	Agent                   string                  `json:"agent"`
	AssignedRunnerId        *string                 `json:"assigned_runner_id,omitempty"`
	AssignmentScope         *string                 `json:"assignment_scope,omitempty"`
	AttemptCount            *int                    `json:"attempt_count,omitempty"`
	BlockedBy               *[]string               `json:"blocked_by"`
	BlockedByFeatures       *[]string               `json:"blocked_by_features,omitempty"`
	BlockedByReason         *string                 `json:"blocked_by_reason,omitempty"`
	CheckoutMode            *string                 `json:"checkout_mode,omitempty"`
	Classification          string                  `json:"classification"`
	CompleteOnIdle          *bool                   `json:"complete_on_idle,omitempty"`
	CompletedAt             *string                 `json:"completed_at,omitempty"`
	Content                 *string                 `json:"content,omitempty"`
	Created                 string                  `json:"created"`
	DeliveryMode            *string                 `json:"delivery_mode,omitempty"`
	DeliveryVerification    *DeliveryVerification   `json:"delivery_verification,omitempty"`
	DependsOn               *[]string               `json:"depends_on"`
	DirectPrompt            string                  `json:"direct_prompt"`
	DispatchLease           *DispatchLease          `json:"dispatch_lease,omitempty"`
	Env                     *map[string]string      `json:"env,omitempty"`
	ExecutionMode           *string                 `json:"execution_mode,omitempty"`
	Executor                *string                 `json:"executor,omitempty"`
	ExpiresAt               *string                 `json:"expires_at,omitempty"`
	Extensions              *[]string               `json:"extensions,omitempty"`
	FeatureDependsOn        *[]string               `json:"feature_depends_on,omitempty"`
	FeatureExpiresAt        *string                 `json:"feature_expires_at,omitempty"`
	FeatureId               *string                 `json:"feature_id,omitempty"`
	FeaturePriority         *string                 `json:"feature_priority,omitempty"`
	FeatureRunOnceAt        *string                 `json:"feature_run_once_at,omitempty"`
	FeatureSchedule         *string                 `json:"feature_schedule,omitempty"`
	FeatureStartsAt         *string                 `json:"feature_starts_at,omitempty"`
	FeatureTimezone         *string                 `json:"feature_timezone,omitempty"`
	Generated               *bool                   `json:"generated,omitempty"`
	GeneratedBy             *string                 `json:"generated_by,omitempty"`
	GeneratedKey            *string                 `json:"generated_key,omitempty"`
	GeneratedKind           *string                 `json:"generated_kind,omitempty"`
	GitBranch               string                  `json:"git_branch"`
	GitRemote               string                  `json:"git_remote"`
	Id                      string                  `json:"id"`
	InCycle                 bool                    `json:"in_cycle"`
	IsAbandoned             *bool                   `json:"is_abandoned,omitempty"`
	LastFailedAt            *string                 `json:"last_failed_at,omitempty"`
	LastPlacementReason     *PlacementReason        `json:"last_placement_reason,omitempty"`
	MachineAffinity         *string                 `json:"machine_affinity,omitempty"`
	MaxRuns                 *int                    `json:"max_runs,omitempty"`
	MergePolicy             *string                 `json:"merge_policy,omitempty"`
	MergeStrategy           *string                 `json:"merge_strategy,omitempty"`
	MergeTargetBranch       *string                 `json:"merge_target_branch,omitempty"`
	Model                   string                  `json:"model"`
	Modified                *string                 `json:"modified,omitempty"`
	NextRun                 *string                 `json:"next_run,omitempty"`
	OpenPrBeforeMerge       *bool                   `json:"open_pr_before_merge,omitempty"`
	OriginClientId          *string                 `json:"origin_client_id,omitempty"`
	OriginMachineId         *string                 `json:"origin_machine_id,omitempty"`
	OriginPath              *string                 `json:"origin_path,omitempty"`
	ParentId                *string                 `json:"parent_id,omitempty"`
	Path                    string                  `json:"path"`
	PlacementReasons        *[]PlacementReason      `json:"placement_reasons,omitempty"`
	Priority                string                  `json:"priority"`
	ProjectId               *string                 `json:"projectId,omitempty"`
	RemoteBranchPolicy      *string                 `json:"remote_branch_policy,omitempty"`
	RequiresCapability      *[]string               `json:"requires_capability,omitempty"`
	ResolvedDeps            *[]string               `json:"resolved_deps"`
	ResolvedWorkdir         string                  `json:"resolved_workdir"`
	ResumeExecutorOverride  *string                 `json:"resume_executor_override,omitempty"`
	ResumeInjectedContext   *string                 `json:"resume_injected_context,omitempty"`
	ResumeMode              *string                 `json:"resume_mode,omitempty"`
	ResumePreferSameSession *bool                   `json:"resume_prefer_same_session,omitempty"`
	ResumeRequested         *bool                   `json:"resume_requested,omitempty"`
	ResumeRequestedAt       *string                 `json:"resume_requested_at,omitempty"`
	Retry                   *AutomationRetry        `json:"retry,omitempty"`
	RunOnceAt               *string                 `json:"run_once_at,omitempty"`
	Runs                    *[]CronRun              `json:"runs,omitempty"`
	Schedule                *string                 `json:"schedule,omitempty"`
	ScheduleEnabled         *bool                   `json:"schedule_enabled,omitempty"`
	Sessions                *map[string]SessionInfo `json:"sessions,omitempty"`
	StartsAt                *string                 `json:"starts_at,omitempty"`
	Status                  string                  `json:"status"`
	Tags                    *[]string               `json:"tags,omitempty"`
	TargetWorkdir           *string                 `json:"target_workdir,omitempty"`
	Timezone                *string                 `json:"timezone,omitempty"`
	Title                   string                  `json:"title"`
	Trigger                 *TriggerConfig          `json:"trigger,omitempty"`
	UndispatchableReason    *string                 `json:"undispatchable_reason,omitempty"`
	UnresolvedDeps          *[]string               `json:"unresolved_deps"`
	UnresolvedFeatureDeps   *[]string               `json:"unresolved_feature_deps,omitempty"`
	UserOriginalRequest     *string                 `json:"user_original_request,omitempty"`
	WaitingOn               *[]string               `json:"waiting_on"`
	WaitingOnFeatures       *[]string               `json:"waiting_on_features,omitempty"`
	Workdir                 string                  `json:"workdir"`
}

// RunFinalization defines model for RunFinalization.
type RunFinalization struct {
	FinalizedAt string  `json:"finalized_at"`
	SessionId   *string `json:"session_id,omitempty"`
	Status      string  `json:"status"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	FeatureId *string   `json:"feature_id,omitempty"`
	Global    *bool     `json:"global,omitempty"`
	Include   *[]string `json:"include,omitempty"`
	Limit     *int      `json:"limit,omitempty"`
	Priority  *string   `json:"priority,omitempty"`
	Project   *string   `json:"project,omitempty"`
	Projects  *[]string `json:"projects,omitempty"`
	Query     string    `json:"query"`
	Status    *string   `json:"status,omitempty"`
	Strategy  *string   `json:"strategy,omitempty"`
	Tags      *[]string `json:"tags,omitempty"`
	Type      *string   `json:"type,omitempty"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Results *[]SearchResult `json:"results"`
	Total   int             `json:"total"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Attachments *[]AttachmentReference `json:"attachments,omitempty"`
	Id          string                 `json:"id"`
	MatchSource *string                `json:"match_source,omitempty"`
	Path        string                 `json:"path"`
	Snippet     string                 `json:"snippet"`
	Status      string                 `json:"status"`
	Title       string                 `json:"title"`
	Type        string                 `json:"type"`
}

// SectionContentResponse defines model for SectionContentResponse.
type SectionContentResponse struct {
	Content            string `json:"content"`
	IncludeSubsections bool   `json:"includeSubsections"`
	Path               string `json:"path"`
	Title              string `json:"title"`
}

// SectionHeader defines model for SectionHeader.
type SectionHeader struct {
	Level int    `json:"level"`
	Title string `json:"title"`
}

// SectionsResponse defines model for SectionsResponse.
type SectionsResponse struct {
	Path     string           `json:"path"`
	Sections *[]SectionHeader `json:"sections"`
}

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	CronId    *string `json:"cron_id,omitempty"`
	Hostname  *string `json:"hostname,omitempty"`
	MachineId *string `json:"machine_id,omitempty"`
	ParentId  *string `json:"parent_id,omitempty"`
	RunId     *string `json:"run_id,omitempty"`
	RunnerId  *string `json:"runner_id,omitempty"`
	Timestamp string  `json:"timestamp"`
	Workdir   *string `json:"workdir,omitempty"`
}

// TaskListResponse defines model for TaskListResponse.
type TaskListResponse struct {
	Count  int             `json:"count"`
	Cycles *[]*[]string    `json:"cycles,omitempty"`
	Stats  *TaskStats      `json:"stats,omitempty"`
	Tasks  *[]ResolvedTask `json:"tasks"`
}

// TaskStats defines model for TaskStats.
type TaskStats struct {
	Blocked       int `json:"blocked"`
	NotPending    int `json:"not_pending"`
	Ready         int `json:"ready"`
	StatusBlocked int `json:"status_blocked"`
	Total         int `json:"total"`
	Waiting       int `json:"waiting"`
}

// TriggerConfig defines model for TriggerConfig.
type TriggerConfig struct {
	Cooldown               *string            `json:"cooldown,omitempty"`
	Event                  *string            `json:"event,omitempty"`
	Events                 *[]string          `json:"events,omitempty"`
	Filter                 *map[string]string `json:"filter,omitempty"`
	IgnoreAutomationEvents *bool              `json:"ignore_automation_events,omitempty"`
	MaxConcurrent          *int               `json:"max_concurrent,omitempty"`
	OncePer                *string            `json:"once_per,omitempty"`
	Schedule               *string            `json:"schedule,omitempty"`
	Timezone               *string            `json:"timezone,omitempty"`
	Type                   *string            `json:"type,omitempty"`
	Webhook                *string            `json:"webhook,omitempty"`
}

// UpdateEntryRequest defines model for UpdateEntryRequest.
type UpdateEntryRequest struct {
	Action              *AutomationAction           `json:"action,omitempty"`
	Agent               *string                     `json:"agent,omitempty"`
	Append              *string                     `json:"append,omitempty"`
	Attachments         *[]AttachmentReference      `json:"attachments,omitempty"`
	AutomationRunId     *string                     `json:"automation_run_id,omitempty"`
	CheckoutMode        *string                     `json:"checkout_mode,omitempty"`
	CompleteOnIdle      *bool                       `json:"complete_on_idle,omitempty"`
	Content             *string                     `json:"content,omitempty"`
	DeliveryMode        *string                     `json:"delivery_mode,omitempty"`
	DependsOn           *[]string                   `json:"depends_on,omitempty"`
	DirectPrompt        *string                     `json:"direct_prompt,omitempty"`
	ExecutionMode       *string                     `json:"execution_mode,omitempty"`
	Executor            *string                     `json:"executor,omitempty"`
	ExpectedRevision    *string                     `json:"expected_revision,omitempty"`
	ExpiresAt           *string                     `json:"expires_at,omitempty"`
	Extensions          *[]string                   `json:"extensions,omitempty"`
	FeatureDependsOn    *[]string                   `json:"feature_depends_on,omitempty"`
	FeatureExpiresAt    *string                     `json:"feature_expires_at,omitempty"`
	FeatureId           *string                     `json:"feature_id,omitempty"`
	FeaturePriority     *string                     `json:"feature_priority,omitempty"`
	FeatureRunOnceAt    *string                     `json:"feature_run_once_at,omitempty"`
	FeatureSchedule     *string                     `json:"feature_schedule,omitempty"`
	FeatureStartsAt     *string                     `json:"feature_starts_at,omitempty"`
	FeatureTimezone     *string                     `json:"feature_timezone,omitempty"`
	Generated           *bool                       `json:"generated,omitempty"`
	GeneratedBy         *string                     `json:"generated_by,omitempty"`
	GeneratedKey        *string                     `json:"generated_key,omitempty"`
	GeneratedKind       *string                     `json:"generated_kind,omitempty"`
	GitBranch           *string                     `json:"git_branch,omitempty"`
	GitRemote           *string                     `json:"git_remote,omitempty"`
	Goal                *GoalConfig                 `json:"goal,omitempty"`
	MachineAffinity     *string                     `json:"machine_affinity,omitempty"`
	MaxRuns             *int                        `json:"max_runs,omitempty"`
	MergePolicy         *string                     `json:"merge_policy,omitempty"`
	MergeStrategy       *string                     `json:"merge_strategy,omitempty"`
	MergeTargetBranch   *string                     `json:"merge_target_branch,omitempty"`
	Model               *string                     `json:"model,omitempty"`
	NextRun             *string                     `json:"next_run,omitempty"`
	Note                *string                     `json:"note,omitempty"`
	OpenPrBeforeMerge   *bool                       `json:"open_pr_before_merge,omitempty"`
	OriginClientId      *string                     `json:"origin_client_id,omitempty"`
	OriginMachineId     *string                     `json:"origin_machine_id,omitempty"`
	OriginPath          *string                     `json:"origin_path,omitempty"`
	Priority            *string                     `json:"priority,omitempty"`
	Reminder            *ReminderConfig             `json:"reminder,omitempty"`
	RemoteBranchPolicy  *string                     `json:"remote_branch_policy,omitempty"`
	Retry               *AutomationRetry            `json:"retry,omitempty"`
	RunFinalizations    *map[string]RunFinalization `json:"run_finalizations,omitempty"`
	RunOnceAt           *string                     `json:"run_once_at,omitempty"`
	Runs                *[]CronRun                  `json:"runs,omitempty"`
	Schedule            *string                     `json:"schedule,omitempty"`
	ScheduleEnabled     *bool                       `json:"schedule_enabled,omitempty"`
	Sessions            *map[string]SessionInfo     `json:"sessions,omitempty"`
	StartsAt            *string                     `json:"starts_at,omitempty"`
	Status              *string                     `json:"status,omitempty"`
	Tags                *[]string                   `json:"tags,omitempty"`
	TargetWorkdir       *string                     `json:"target_workdir,omitempty"`
	Timezone            *string                     `json:"timezone,omitempty"`
	Title               *string                     `json:"title,omitempty"`
	Trigger             *TriggerConfig              `json:"trigger,omitempty"`
	UserOriginalRequest *string                     `json:"user_original_request,omitempty"`
	Workdir             *string                     `json:"workdir,omitempty"`
}

// ValidationDetail defines model for ValidationDetail.
type ValidationDetail struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// AttachmentsListParams defines parameters for AttachmentsList.
type AttachmentsListParams struct {
	ProjectId string `form:"project_id" json:"project_id"`
}

// AttachmentsUploadMultipartBody defines parameters for AttachmentsUpload.
type AttachmentsUploadMultipartBody struct {
	File []byte `json:"file"`

	// Metadata JSON-encoded object with string values
	Metadata  *string `json:"metadata,omitempty"`
	ProjectId string  `json:"project_id"`
}

// AttachmentsDeleteParams defines parameters for AttachmentsDelete.
type AttachmentsDeleteParams struct {
	ProjectId string `form:"project_id" json:"project_id"`
}

// AttachmentsGetParams defines parameters for AttachmentsGet.
type AttachmentsGetParams struct {
	ProjectId string `form:"project_id" json:"project_id"`
}

// AttachmentsDownloadParams defines parameters for AttachmentsDownload.
type AttachmentsDownloadParams struct {
	ProjectId string `form:"project_id" json:"project_id"`
}

// AttachmentsExtractParams defines parameters for AttachmentsExtract.
type AttachmentsExtractParams struct {
	ProjectId string `form:"project_id" json:"project_id"`
}

// AttachmentsTextParams defines parameters for AttachmentsText.
type AttachmentsTextParams struct {
	ProjectId string `form:"project_id" json:"project_id"`
}

// EntriesListParams defines parameters for EntriesList.
type EntriesListParams struct {
	Project   *string `form:"project,omitempty" json:"project,omitempty"`
	Type      *string `form:"type,omitempty" json:"type,omitempty"`
	Status    *string `form:"status,omitempty" json:"status,omitempty"`
	Tags      *string `form:"tags,omitempty" json:"tags,omitempty"`
	FeatureId *string `form:"feature_id,omitempty" json:"feature_id,omitempty"`
	Limit     *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset    *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Global    *bool   `form:"global,omitempty" json:"global,omitempty"`
	SortBy    *string `form:"sortBy,omitempty" json:"sortBy,omitempty"`
	SortOrder *string `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// EntriesDeleteParams defines parameters for EntriesDelete.
type EntriesDeleteParams struct {
	Confirm EntriesDeleteParamsConfirm `form:"confirm" json:"confirm"`
	Force   *bool                      `form:"force,omitempty" json:"force,omitempty"`
}

// EntriesDeleteParamsConfirm defines parameters for EntriesDelete.
type EntriesDeleteParamsConfirm bool

// AttachmentsForEntryParams defines parameters for AttachmentsForEntry.
type AttachmentsForEntryParams struct {
	ProjectId string `form:"project_id" json:"project_id"`
}

// AttachmentsAttachParams defines parameters for AttachmentsAttach.
type AttachmentsAttachParams struct {
	ProjectId string `form:"project_id" json:"project_id"`
}

// AttachmentsDetachParams defines parameters for AttachmentsDetach.
type AttachmentsDetachParams struct {
	Role      string `form:"role" json:"role"`
	ProjectId string `form:"project_id" json:"project_id"`
}

// GraphRelatedParams defines parameters for GraphRelated.
type GraphRelatedParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// SectionsGetParams defines parameters for SectionsGet.
type SectionsGetParams struct {
	IncludeSubsections *bool `form:"includeSubsections,omitempty" json:"includeSubsections,omitempty"`
}

// AttachmentsUploadMultipartRequestBody defines body for AttachmentsUpload for multipart/form-data ContentType.
type AttachmentsUploadMultipartRequestBody AttachmentsUploadMultipartBody

// AttachmentsExtractJSONRequestBody defines body for AttachmentsExtract for application/json ContentType.
type AttachmentsExtractJSONRequestBody = AttachmentExtractionRequest

// EntriesCreateJSONRequestBody defines body for EntriesCreate for application/json ContentType.
type EntriesCreateJSONRequestBody = CreateEntryRequest

// EntriesBulkDeleteJSONRequestBody defines body for EntriesBulkDelete for application/json ContentType.
type EntriesBulkDeleteJSONRequestBody = BulkDeleteRequest

// EntriesBulkUpdateJSONRequestBody defines body for EntriesBulkUpdate for application/json ContentType.
type EntriesBulkUpdateJSONRequestBody = BulkUpdateRequest

// EntriesUpdateJSONRequestBody defines body for EntriesUpdate for application/json ContentType.
type EntriesUpdateJSONRequestBody = UpdateEntryRequest

// AttachmentsAttachJSONRequestBody defines body for AttachmentsAttach for application/json ContentType.
type AttachmentsAttachJSONRequestBody = AttachEntryAttachmentRequest

// EntriesMoveJSONRequestBody defines body for EntriesMove for application/json ContentType.
type EntriesMoveJSONRequestBody = MoveEntryRequest

// SearchQueryJSONRequestBody defines body for SearchQuery for application/json ContentType.
type SearchQueryJSONRequestBody = SearchRequest
