/**
 * Brain API Plugin for Antigravity
 *
 * This is a placeholder for future Antigravity integration.
 * The implementation will depend on Antigravity's plugin API.
 *
 * This file is auto-generated by brain. Do not edit directly.
 * Source: https://github.com/huynle/brain
 * Generated: {{GENERATED_DATE}}
 *
 * TODO: Implement full Antigravity plugin when API is available.
 */

console.log("Brain API Antigravity Plugin - Coming Soon!");
console.log("For now, use the Brain API directly at: http://localhost:3333");
console.log("");
console.log("API Endpoints:");
console.log("  POST /api/v1/entries     - Create entry");
console.log("  GET  /api/v1/entries/:id - Get entry");
console.log("  POST /api/v1/search      - Search entries");
console.log("  POST /api/v1/inject      - Get context");
console.log("");
console.log("See https://github.com/huynle/brain for full documentation.");
