/**
 * Brain API Extension for Cursor IDE
 *
 * This is a placeholder for future Cursor IDE integration.
 * Cursor uses VS Code extension format, so full implementation
 * would require a proper VS Code extension structure.
 *
 * For now, you can use the Brain API directly via HTTP from Cursor.
 *
 * This file is auto-generated by brain. Do not edit directly.
 * Source: https://github.com/huynle/brain
 * Generated: {{GENERATED_DATE}}
 *
 * TODO: Implement full Cursor extension with:
 * - VS Code extension manifest (package.json)
 * - Extension activation
 * - Command palette integration
 * - Sidebar panel for brain entries
 */

console.log("Brain API Cursor Extension - Coming Soon!");
console.log("For now, use the Brain API directly at: http://localhost:3333");
console.log("");
console.log("API Endpoints:");
console.log("  POST /api/v1/entries     - Create entry");
console.log("  GET  /api/v1/entries/:id - Get entry");
console.log("  POST /api/v1/search      - Search entries");
console.log("  POST /api/v1/inject      - Get context");
console.log("");
console.log("See https://github.com/huynle/brain for full documentation.");
