package mcp

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/huynle/brain-api/internal/types"
)

// RegisterGoalTools registers goal automation MCP tools on the server.
func RegisterGoalTools(s *Server, client *APIClient) {
	registerBrainGoalCreate(s, client)
	registerBrainGoalList(s, client)
	registerBrainGoalUpdate(s, client)
	registerBrainGoalLifecycleAlias(s, client, "goal_pause", "Pause a goal automation by setting status to blocked.", "blocked", "Goal paused")
	registerBrainGoalLifecycleAlias(s, client, "goal_resume", "Resume a goal automation by setting status to active.", "active", "Goal resumed")
	registerBrainGoalLifecycleAlias(s, client, "goal_archive", "Archive a goal automation by setting status to archived.", "archived", "Goal archived")
	registerBrainGoalRun(s, client)
	registerBrainGoalProgress(s, client)
	registerBrainGoalAudit(s, client)
	registerBrainGoalDelete(s, client)
}

func goalCommonProperties(includeCreateOnly bool) map[string]Property {
	props := map[string]Property{
		"feature_id":                {Type: "string", Description: "Feature ID to scope the goal"},
		"title":                     {Type: "string", Description: "Goal title/objective"},
		"content":                   {Type: "string", Description: "Optional goal body/content"},
		"goal_id":                   {Type: "string", Description: "Stable goal identifier. Generated by the API if omitted on create."},
		"criteria":                  {Type: "string", Description: "Success criteria for the goal"},
		"validation":                {Type: "string", Description: "How goal completion is validated"},
		"workdir":                   {Type: "string", Description: "Working directory for generated work"},
		"trigger_source":            {Type: "string", Enum: []string{types.GoalTriggerSourceTask, types.GoalTriggerSourceFeature, types.GoalTriggerSourceBoth}, Description: "Lifecycle events that trigger reconciliation"},
		"task_id":                   {Type: "string", Description: "Task ID to scope the goal to a single task (takes precedence over feature_id)"},
		"complete_statuses":         {Type: "array", Items: &Property{Type: "string"}, Description: "Task statuses that count as complete"},
		"blocked_statuses":          {Type: "array", Items: &Property{Type: "string"}, Description: "Task statuses that count as blocked"},
		"steering_enabled":          {Type: "boolean", Description: "Steer live agent sessions toward the goal while work is in progress (default: true)"},
		"steering_cooldown_minutes": {Type: "number", Description: "Minimum minutes between steering prompt injections (default: 15)"},
		"action_type":               {Type: "string", Description: "Automation action type (prompt, script, update, http)"},
		"direct_prompt":             {Type: "string", Description: "Prompt text for prompt actions"},
		"command":                   {Type: "string", Description: "Command for script actions"},
		"agent":                     {Type: "string", Description: "Agent override"},
		"model":                     {Type: "string", Description: "Model override"},
		"executor":                  {Type: "string", Description: "Executor override"},
		"target_workdir":            {Type: "string", Description: "Target workdir override"},
		"execution_mode":            {Type: "string", Description: "Execution mode (worktree or current_branch)"},
		"session_mode":              {Type: "string", Description: "Session mode (continue or fresh)"},
		"complete_on_idle":          {Type: "boolean", Description: "Auto-complete generated tasks when the agent goes idle"},
		"timeout":                   {Type: "string", Description: "Execution timeout (e.g. 30m, 1h)"},
		"requires_capability":       {Type: "string", Description: "Required runner capability"},
		"action":                    {Type: "object", Description: "Nested AutomationAction object; flat action_* fields are merged over it"},
	}
	if includeCreateOnly {
		props["project"] = Property{Type: "string", Description: "Project for the goal"}
		props["config"] = Property{Type: "object", Description: "Nested GoalConfig object; flat config fields are merged over it"}
	} else {
		props["status"] = Property{Type: "string", Description: "Goal status"}
		// On update these fields are presence-based: passing "" clears them.
		// Say so, because an advertised field whose empty value silently did
		// nothing is exactly the trap this schema used to set.
		props["feature_id"] = Property{Type: "string", Description: "Feature ID to scope the goal. Pass \"\" to clear the feature scope and widen the goal to the whole project."}
		props["task_id"] = Property{Type: "string", Description: "Task ID to scope the goal to a single task (takes precedence over feature_id). Pass \"\" to clear."}
		props["criteria"] = Property{Type: "string", Description: "Success criteria for the goal. Pass \"\" to clear."}
		props["validation"] = Property{Type: "string", Description: "How goal completion is validated. Pass \"\" to clear."}
		props["workdir"] = Property{Type: "string", Description: "Working directory for generated work. Pass \"\" to clear."}
		props["complete_statuses"] = Property{Type: "array", Items: &Property{Type: "string"}, Description: "Task statuses that count as complete. Pass [] to reset to defaults (completed, validated, archived)."}
		props["blocked_statuses"] = Property{Type: "array", Items: &Property{Type: "string"}, Description: "Task statuses that count as blocked. Pass [] to reset to the default (blocked)."}
	}
	return props
}

func registerBrainGoalCreate(s *Server, client *APIClient) {
	s.RegisterTool(Tool{
		Name:        "goal_create",
		Description: "Create a goal automation: keep working until an objective is satisfied.",
		InputSchema: InputSchema{Type: "object", Properties: goalCommonProperties(true), Required: []string{"project", "title"}},
	}, func(ctx context.Context, args map[string]any) (string, error) {
		project := StringArg(args, "project", "")
		title := StringArg(args, "title", "")
		if project == "" {
			return "", fmt.Errorf("provide a 'project'")
		}
		if title == "" {
			return "", fmt.Errorf("provide a 'title'")
		}

		req := types.CreateGoalRequest{
			Project:   project,
			FeatureID: StringArg(args, "feature_id", ""),
			Title:     title,
			Content:   StringArg(args, "content", ""),
			Config:    buildGoalConfig(args),
			Action:    buildGoalAction(args),
		}

		var goal types.GoalSummary
		if err := client.Request(ctx, http.MethodPost, "/goals", req, nil, &goal); err != nil {
			return "", err
		}
		return formatGoalSummary("Goal created", &goal), nil
	})
}

func registerBrainGoalList(s *Server, client *APIClient) {
	s.RegisterTool(Tool{
		Name:        "goal_list",
		Description: "List goal automations (active + blocked + completed by default), optionally filtered by project, feature_id, and status ('archived' or 'all' reveal hidden goals).",
		InputSchema: InputSchema{Type: "object", Properties: map[string]Property{"project": {Type: "string", Description: "Filter by project"}, "feature_id": {Type: "string", Description: "Filter by feature ID"}, "status": {Type: "string", Description: "Status filter: exact status, 'archived', or 'all' (default: active+blocked+completed)"}}},
	}, func(ctx context.Context, args map[string]any) (string, error) {
		query := map[string]string{}
		if project := StringArg(args, "project", ""); project != "" {
			query["project"] = project
		}
		if featureID := StringArg(args, "feature_id", ""); featureID != "" {
			query["feature_id"] = featureID
		}
		if status := StringArg(args, "status", ""); status != "" {
			query["status"] = status
		}
		var resp struct {
			Goals []types.GoalSummary `json:"goals"`
		}
		if err := client.Request(ctx, http.MethodGet, "/goals", nil, query, &resp); err != nil {
			return "", err
		}
		return formatGoalList(resp.Goals), nil
	})
}

func registerBrainGoalUpdate(s *Server, client *APIClient) {
	s.RegisterTool(Tool{
		Name:        "goal_update",
		Description: "Update a goal automation's title/content/status/scope/config/action fields. Omitted fields are left alone; an explicit empty value clears the field (feature_id: \"\" re-scopes the goal to its whole project).",
		InputSchema: InputSchema{Type: "object", Properties: goalCommonProperties(false), Required: []string{"goal_id"}},
	}, func(ctx context.Context, args map[string]any) (string, error) {
		goalID := StringArg(args, "goal_id", "")
		if goalID == "" {
			return "", fmt.Errorf("provide a 'goal_id'")
		}
		req := buildUpdateGoalRequest(args)
		var goal types.GoalSummary
		if err := client.Request(ctx, http.MethodPatch, "/goals/"+url.PathEscape(goalID), req, nil, &goal); err != nil {
			return "", err
		}
		return formatGoalSummary("Goal updated", &goal), nil
	})
}

func registerBrainGoalLifecycleAlias(s *Server, client *APIClient, name, description, status, prefix string) {
	s.RegisterTool(Tool{
		Name:        name,
		Description: description,
		InputSchema: InputSchema{Type: "object", Properties: map[string]Property{"goal_id": {Type: "string", Description: "Goal ID"}}, Required: []string{"goal_id"}},
	}, func(ctx context.Context, args map[string]any) (string, error) {
		goalID := StringArg(args, "goal_id", "")
		if goalID == "" {
			return "", fmt.Errorf("provide a 'goal_id'")
		}
		req := types.UpdateGoalRequest{Status: &status}
		var goal types.GoalSummary
		if err := client.Request(ctx, http.MethodPatch, "/goals/"+url.PathEscape(goalID), req, nil, &goal); err != nil {
			return "", err
		}
		return formatGoalSummary(prefix, &goal), nil
	})
}

func registerBrainGoalRun(s *Server, client *APIClient) {
	s.RegisterTool(Tool{Name: "goal_run", Description: "Manually reconcile a goal automation now.", InputSchema: InputSchema{Type: "object", Properties: map[string]Property{"goal_id": {Type: "string", Description: "Goal ID"}}, Required: []string{"goal_id"}}}, func(ctx context.Context, args map[string]any) (string, error) {
		goalID := StringArg(args, "goal_id", "")
		if goalID == "" {
			return "", fmt.Errorf("provide a 'goal_id'")
		}
		var audit types.GoalReconcileAudit
		if err := client.Request(ctx, http.MethodPost, "/goals/"+url.PathEscape(goalID)+"/run", nil, nil, &audit); err != nil {
			return "", err
		}
		return formatGoalRun(&audit), nil
	})
}

func registerBrainGoalProgress(s *Server, client *APIClient) {
	s.RegisterTool(Tool{Name: "goal_progress", Description: "Show linked task progress for a goal automation.", InputSchema: InputSchema{Type: "object", Properties: map[string]Property{"goal_id": {Type: "string", Description: "Goal ID"}}, Required: []string{"goal_id"}}}, func(ctx context.Context, args map[string]any) (string, error) {
		goalID := StringArg(args, "goal_id", "")
		if goalID == "" {
			return "", fmt.Errorf("provide a 'goal_id'")
		}
		var progress types.GoalProgressResponse
		if err := client.Request(ctx, http.MethodGet, "/goals/"+url.PathEscape(goalID)+"/progress", nil, nil, &progress); err != nil {
			return "", err
		}
		return formatGoalProgress(&progress), nil
	})
}

func registerBrainGoalAudit(s *Server, client *APIClient) {
	s.RegisterTool(Tool{Name: "goal_audit", Description: "Show reconcile audit history for a goal automation.", InputSchema: InputSchema{Type: "object", Properties: map[string]Property{"goal_id": {Type: "string", Description: "Goal ID"}, "limit": {Type: "number", Description: "Maximum audit rows (default: 50)"}}, Required: []string{"goal_id"}}}, func(ctx context.Context, args map[string]any) (string, error) {
		goalID := StringArg(args, "goal_id", "")
		if goalID == "" {
			return "", fmt.Errorf("provide a 'goal_id'")
		}
		limit := IntArg(args, "limit", 50)
		query := map[string]string{"limit": fmt.Sprintf("%d", limit)}
		var resp struct {
			Audit []types.GoalReconcileAudit `json:"audit"`
		}
		if err := client.Request(ctx, http.MethodGet, "/goals/"+url.PathEscape(goalID)+"/audit", nil, query, &resp); err != nil {
			return "", err
		}
		return formatGoalAudit(goalID, resp.Audit), nil
	})
}

func registerBrainGoalDelete(s *Server, client *APIClient) {
	s.RegisterTool(Tool{Name: "goal_delete", Description: "Permanently delete a goal automation (the underlying automation entry is removed).", InputSchema: InputSchema{Type: "object", Properties: map[string]Property{"goal_id": {Type: "string", Description: "Goal ID"}}, Required: []string{"goal_id"}}}, func(ctx context.Context, args map[string]any) (string, error) {
		goalID := StringArg(args, "goal_id", "")
		if goalID == "" {
			return "", fmt.Errorf("provide a 'goal_id'")
		}
		var resp struct {
			Success bool   `json:"success"`
			GoalID  string `json:"goal_id"`
		}
		if err := client.Request(ctx, http.MethodDelete, "/goals/"+url.PathEscape(goalID), nil, nil, &resp); err != nil {
			return "", err
		}
		return fmt.Sprintf("Goal deleted: %s", goalID), nil
	})
}

func buildGoalConfig(args map[string]any) types.GoalConfig {
	cfg := types.GoalConfig{}
	if raw, ok := args["config"].(map[string]any); ok {
		cfg.ID = stringFromMap(raw, "id")
		cfg.Criteria = stringFromMap(raw, "criteria")
		cfg.Validation = stringFromMap(raw, "validation")
		cfg.Workdir = stringFromMap(raw, "workdir")
		cfg.TriggerSource = stringFromMap(raw, "trigger_source")
		cfg.TaskID = stringFromMap(raw, "task_id")
		cfg.CompleteStatuses = stringSliceFromMap(raw, "complete_statuses")
		cfg.BlockedStatuses = stringSliceFromMap(raw, "blocked_statuses")
		if steering, ok := raw["steering"].(map[string]any); ok {
			cfg.Steering = goalSteeringFromMap(steering)
		}
	}
	if v := StringArg(args, "goal_id", ""); v != "" {
		cfg.ID = v
	}
	if v := StringArg(args, "criteria", ""); v != "" {
		cfg.Criteria = v
	}
	if v := StringArg(args, "validation", ""); v != "" {
		cfg.Validation = v
	}
	if v := StringArg(args, "workdir", ""); v != "" {
		cfg.Workdir = v
	}
	if v := StringArg(args, "trigger_source", ""); v != "" {
		cfg.TriggerSource = v
	}
	if v := StringArg(args, "task_id", ""); v != "" {
		cfg.TaskID = v
	}
	if v := StringSliceArg(args, "complete_statuses"); len(v) > 0 {
		cfg.CompleteStatuses = v
	}
	if v := StringSliceArg(args, "blocked_statuses"); len(v) > 0 {
		cfg.BlockedStatuses = v
	}
	if steering := buildGoalSteering(args); steering != nil {
		cfg.Steering = mergeGoalSteering(cfg.Steering, steering)
	}
	return cfg
}

// goalSteeringFromMap converts a nested steering object to GoalSteering.
func goalSteeringFromMap(m map[string]any) *types.GoalSteering {
	steering := &types.GoalSteering{}
	if b, ok := m["enabled"].(bool); ok {
		steering.Enabled = &b
	}
	if n, ok := m["cooldown_minutes"].(float64); ok {
		steering.CooldownMinutes = int(n)
	}
	return steering
}

// buildGoalSteering builds a GoalSteering from the flat steering_* args, or
// nil when neither is present.
func buildGoalSteering(args map[string]any) *types.GoalSteering {
	_, hasEnabled := args["steering_enabled"]
	_, hasCooldown := args["steering_cooldown_minutes"]
	if !hasEnabled && !hasCooldown {
		return nil
	}
	steering := &types.GoalSteering{}
	if hasEnabled {
		b := BoolArg(args, "steering_enabled", true)
		steering.Enabled = &b
	}
	if hasCooldown {
		steering.CooldownMinutes = IntArg(args, "steering_cooldown_minutes", 0)
	}
	return steering
}

// mergeGoalSteering overlays flat steering args over the nested config value.
func mergeGoalSteering(base, overlay *types.GoalSteering) *types.GoalSteering {
	if base == nil {
		return overlay
	}
	if overlay == nil {
		return base
	}
	merged := *base
	if overlay.Enabled != nil {
		merged.Enabled = overlay.Enabled
	}
	if overlay.CooldownMinutes != 0 {
		merged.CooldownMinutes = overlay.CooldownMinutes
	}
	return &merged
}

func buildGoalAction(args map[string]any) types.AutomationAction {
	action := types.AutomationAction{Type: "prompt"}
	if raw, ok := args["action"].(map[string]any); ok {
		action.Type = stringFromMap(raw, "type")
		action.DirectPrompt = stringFromMap(raw, "direct_prompt")
		action.Command = stringFromMap(raw, "command")
		action.Agent = stringFromMap(raw, "agent")
		action.Model = stringFromMap(raw, "model")
		action.Executor = stringFromMap(raw, "executor")
		action.TargetWorkdir = stringFromMap(raw, "target_workdir")
		action.ExecutionMode = stringFromMap(raw, "execution_mode")
		action.SessionMode = stringFromMap(raw, "session_mode")
		action.Timeout = stringFromMap(raw, "timeout")
		action.RequiresCapability = stringFromMap(raw, "requires_capability")
		if b, ok := raw["complete_on_idle"].(bool); ok {
			action.CompleteOnIdle = &b
		}
	}
	if v := StringArg(args, "action_type", ""); v != "" {
		action.Type = v
	}
	if action.Type == "" {
		action.Type = "prompt"
	}
	if v := StringArg(args, "direct_prompt", ""); v != "" {
		action.DirectPrompt = v
	}
	if v := StringArg(args, "command", ""); v != "" {
		action.Command = v
	}
	if v := StringArg(args, "agent", ""); v != "" {
		action.Agent = v
	}
	if v := StringArg(args, "model", ""); v != "" {
		action.Model = v
	}
	if v := StringArg(args, "executor", ""); v != "" {
		action.Executor = v
	}
	if v := StringArg(args, "target_workdir", ""); v != "" {
		action.TargetWorkdir = v
	}
	if v := StringArg(args, "execution_mode", ""); v != "" {
		action.ExecutionMode = v
	}
	if v := StringArg(args, "session_mode", ""); v != "" {
		action.SessionMode = v
	}
	if v := StringArg(args, "timeout", ""); v != "" {
		action.Timeout = v
	}
	if v := StringArg(args, "requires_capability", ""); v != "" {
		action.RequiresCapability = v
	}
	if _, ok := args["complete_on_idle"]; ok {
		b := BoolArg(args, "complete_on_idle", false)
		action.CompleteOnIdle = &b
	}
	return action
}

// clearableStringArg returns a pointer to the string at key when the caller
// supplied one, and nil when the key is absent or holds a non-string (JSON
// null included, which reads as "not supplied" rather than "clear this").
//
// Presence is the test, not emptiness. Every string arm below was once guarded
// `if v := StringArg(...); v != ""`, which makes an explicit "" indistinguishable
// from an omitted field — so no string field on a goal could be cleared, only
// overwritten with something else. MCP args arrive as map[string]any, where the
// two ARE distinguishable; it just takes checking the key instead of the value.
func clearableStringArg(args map[string]any, key string) *string {
	v, ok := args[key].(string)
	if !ok {
		return nil
	}
	return &v
}

// clearableStringSliceArg is clearableStringArg for array fields: an explicit
// [] resets the field (the goal status sets then fall back to the reconciler's
// defaults), which the old `len(v) > 0` guard could not express.
func clearableStringSliceArg(args map[string]any, key string) *[]string {
	if _, ok := args[key]; !ok {
		return nil
	}
	v := StringSliceArg(args, key)
	if v == nil {
		return nil
	}
	return &v
}

func buildUpdateGoalRequest(args map[string]any) types.UpdateGoalRequest {
	req := types.UpdateGoalRequest{}

	// Title and status stay value-based: a goal has no valid empty title (the
	// rebuild rejects one) and no valid empty status, so a blank there is an
	// autofilled field, never an instruction to clear.
	if v := StringArg(args, "title", ""); v != "" {
		req.Title = &v
	}
	if v := StringArg(args, "status", ""); v != "" {
		req.Status = &v
	}

	// Everything else is presence-based, so "" clears the field. feature_id
	// is the one that was missing outright — advertised by the input schema,
	// handled on create, and silently dropped here, which left re-scoping a
	// goal to delete-and-recreate.
	req.FeatureID = clearableStringArg(args, "feature_id")
	req.Content = clearableStringArg(args, "content")
	req.Criteria = clearableStringArg(args, "criteria")
	req.Validation = clearableStringArg(args, "validation")
	req.Workdir = clearableStringArg(args, "workdir")
	req.TriggerSource = clearableStringArg(args, "trigger_source")
	req.TaskID = clearableStringArg(args, "task_id")
	req.CompleteStatuses = clearableStringSliceArg(args, "complete_statuses")
	req.BlockedStatuses = clearableStringSliceArg(args, "blocked_statuses")

	if steering := buildGoalSteering(args); steering != nil {
		req.Steering = steering
	}
	if hasActionArgs(args) {
		action := buildGoalAction(args)
		req.Action = &action
	}
	return req
}

func hasActionArgs(args map[string]any) bool {
	for _, key := range []string{"action", "action_type", "direct_prompt", "command", "agent", "model", "executor", "target_workdir", "execution_mode", "session_mode", "complete_on_idle", "timeout", "requires_capability"} {
		if _, ok := args[key]; ok {
			return true
		}
	}
	return false
}

func stringFromMap(m map[string]any, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

func stringSliceFromMap(m map[string]any, key string) []string {
	arr, ok := m[key].([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(arr))
	for _, item := range arr {
		if s, ok := item.(string); ok {
			out = append(out, s)
		}
	}
	return out
}

func formatGoalSummary(prefix string, goal *types.GoalSummary) string {
	if goal == nil {
		return prefix
	}
	lines := []string{fmt.Sprintf("%s: %s", prefix, goal.GoalID)}
	if goal.EntryID != "" {
		lines = append(lines, fmt.Sprintf("- entry_id: %s", goal.EntryID))
	}
	if goal.Title != "" {
		lines = append(lines, fmt.Sprintf("- title: %s", goal.Title))
	}
	if goal.Project != "" {
		lines = append(lines, fmt.Sprintf("- project: %s", goal.Project))
	}
	if goal.FeatureID != "" {
		lines = append(lines, fmt.Sprintf("- feature_id: %s", goal.FeatureID))
	}
	if goal.Status != "" {
		lines = append(lines, fmt.Sprintf("- status: %s", goal.Status))
	}
	if goal.Config != nil {
		lines = append(lines, fmt.Sprintf("- trigger_source: %s", goal.Config.NormalizedTriggerSource()))
	}
	return strings.Join(lines, "\n")
}

func formatGoalList(goals []types.GoalSummary) string {
	if len(goals) == 0 {
		return "No goals found.\n\nCreate one with `goal_create`."
	}
	lines := []string{fmt.Sprintf("## Goals (%d)", len(goals)), "", "| goal_id | title | project | feature | status | trigger |", "|---|---|---|---|---|---|"}
	for _, goal := range goals {
		trigger := ""
		if goal.Config != nil {
			trigger = goal.Config.NormalizedTriggerSource()
		}
		feature := goal.FeatureID
		if feature == "" {
			feature = "-"
		}
		project := goal.Project
		if project == "" {
			project = "(global)"
		}
		lines = append(lines, fmt.Sprintf("| %s | %s | %s | %s | %s | %s |", goal.GoalID, goal.Title, project, feature, goal.Status, trigger))
	}
	return strings.Join(lines, "\n")
}

func formatGoalRun(audit *types.GoalReconcileAudit) string {
	if audit == nil {
		return "Reconcile: no audit returned"
	}
	lines := []string{fmt.Sprintf("## Reconcile: %s", audit.GoalID), "", fmt.Sprintf("- Decision: %s", audit.Decision), fmt.Sprintf("- Reason: %s", audit.Reason)}
	if audit.Project != "" {
		lines = append(lines, fmt.Sprintf("- Project: %s", audit.Project))
	}
	if audit.FeatureID != "" {
		lines = append(lines, fmt.Sprintf("- Feature: %s", audit.FeatureID))
	}
	if audit.GeneratedTaskID != "" {
		lines = append(lines, fmt.Sprintf("- Generated task: %s", audit.GeneratedTaskID))
	}
	lines = append(lines, fmt.Sprintf("- Linked tasks: %d", len(audit.LinkedTasks)))
	return strings.Join(lines, "\n")
}

func formatGoalProgress(p *types.GoalProgressResponse) string {
	if p == nil {
		return "Progress: no data returned"
	}
	lines := []string{fmt.Sprintf("## Progress: %s", p.GoalID), ""}
	if p.EntryID != "" {
		lines = append(lines, fmt.Sprintf("- entry_id: %s", p.EntryID))
	}
	if p.Project != "" {
		lines = append(lines, fmt.Sprintf("- Project: %s", p.Project))
	}
	if p.FeatureID != "" {
		lines = append(lines, fmt.Sprintf("- Feature ID: %s", p.FeatureID))
	}
	if p.GoalStatus != "" {
		lines = append(lines, fmt.Sprintf("- Goal: %s", p.GoalStatus))
	}
	// Only set for a feature-scoped goal; see GoalProgressResponse.
	if p.FeatureStatus != "" {
		lines = append(lines, fmt.Sprintf("- Feature: %s", p.FeatureStatus))
	}
	lines = append(lines, fmt.Sprintf("- Total: %d", p.Total), fmt.Sprintf("- Pending: %d", p.Pending), fmt.Sprintf("- In Progress: %d", p.InProgress), fmt.Sprintf("- Completed: %d", p.Completed), fmt.Sprintf("- Blocked: %d", p.Blocked))
	if len(p.Tasks) > 0 {
		lines = append(lines, "", "### Tasks")
		for _, task := range p.Tasks {
			lines = append(lines, fmt.Sprintf("- %s **%s** (%s)", statusEmojiExtended(task.Status), task.Title, task.ID))
		}
	}
	return strings.Join(lines, "\n")
}

func formatGoalAudit(goalID string, audits []types.GoalReconcileAudit) string {
	if len(audits) == 0 {
		return fmt.Sprintf("No reconcile audit records found for goal %s.", goalID)
	}
	lines := []string{fmt.Sprintf("## Reconcile Audit: %s", goalID), ""}
	for _, audit := range audits {
		lines = append(lines, fmt.Sprintf("- **%s** — %s", audit.Timestamp, audit.Decision))
		if audit.Reason != "" {
			lines = append(lines, fmt.Sprintf("  Reason: %s", audit.Reason))
		}
		if audit.GeneratedTaskID != "" {
			lines = append(lines, fmt.Sprintf("  Generated task: %s", audit.GeneratedTaskID))
		}
		lines = append(lines, fmt.Sprintf("  Linked tasks: %d", len(audit.LinkedTasks)))
	}
	return strings.Join(lines, "\n")
}
