package mcp_test

import (
	"testing"
)

// TestGolden_SupervisorTools covers supervisor_tools.go plus the live-inject
// path of resume_task_with_context, on a dedicated server with a scripted
// runner connected over the real bridge. Delivery verification is only driven
// to its pre-provider refusals: a matching revision on a configured policy
// would call GitHub, which no test may do.
func TestGolden_SupervisorTools(t *testing.T) {
	api := dedicatedAPI(t)
	g := newGoldenAt(t, "supervisor_tools", api)
	g.scrubRe(`"event_cursor":"[^"]*"`, `"event_cursor":"<CURSOR>"`)
	g.scrubRe(`"next_cursor":"[^"]*"`, `"next_cursor":"<CURSOR>"`)
	g.scrubRe(`"after":"[A-Za-z0-9_=-]{20,}"`, `"after":"<CURSOR>"`)
	g.scrubRe(`"window":"[^"]*"`, `"window":"<WINDOW>"`)
	g.scrubRe(`"version":"[^"]*","commit":"[^"]*"`, `"version":"<VERSION>","commit":"<COMMIT>"`)
	g.scrubRe(`"commit":"[^"]*","version":"[^"]*"`, `"commit":"<COMMIT>","version":"<VERSION>"`)
	p := "sup"
	task := entryFields(t, api, map[string]any{"type": "task", "title": "Supervised", "content": "s", "project": p, "status": "pending", "feature_id": "feat-s"})
	g.bind("TASK", task)
	// A second project keeps "sup" to one task: the snapshot orders tasks by
	// their random ids.
	p2 := "sup-two"
	done := entryFields(t, api, map[string]any{"type": "task", "title": "Finished", "content": "f", "project": p2, "status": "completed"})
	g.bind("DONE", done)

	apiDo(t, "POST", api+"/api/v1/runners/register", map[string]any{"runner_id": "sup-runner", "hostname": "h", "executors": []string{"opencode"}})
	apiDo(t, "PUT", api+"/api/v1/runners/sup-runner/instances/ins-adhoc", map[string]any{"kind": "adhoc", "status": "idle", "started_at": 1, "last_seen": 1, "executor": "opencode"})
	g.call("session tail not connected", "session_tail", map[string]any{"runner_id": "sup-runner", "session_id": "ses-1"})
	g.call("session children not connected", "session_children", map[string]any{"runner_id": "sup-runner", "session_id": "ses-parent"})
	g.call("resume live not connected", "resume_task_with_context", map[string]any{"project": p, "task_id": task, "injected_context": "nudge", "force": true})

	runner := connectScriptedRunner(t, api, "sup-runner", scriptedResponse)
	g.call("session tail missing ids", "session_tail", map[string]any{"runner_id": "sup-runner"})
	g.call("session tail", "session_tail", map[string]any{"runner_id": "sup-runner", "session_id": "ses-1"})
	g.frames(runner)
	g.call("session tail page", "session_tail", map[string]any{"runner_id": "sup-runner", "session_id": "ses-1", "limit": 1, "max_bytes": 1024})
	g.frames(runner)
	g.call("session tail bad limit", "session_tail", map[string]any{"runner_id": "sup-runner", "session_id": "ses-1", "limit": 500})
	g.frames(runner)
	g.call("session tail empty", "session_tail", map[string]any{"runner_id": "sup-runner", "session_id": "ses-empty"})
	g.frames(runner)
	g.call("session tail unknown", "session_tail", map[string]any{"runner_id": "sup-runner", "session_id": "ses-missing"})
	g.frames(runner)
	g.call("session tail other runner", "session_tail", map[string]any{"runner_id": "ghost runner", "session_id": "ses/1"})
	g.call("session children missing ids", "session_children", map[string]any{"session_id": "ses-parent"})
	g.call("session children", "session_children", map[string]any{"runner_id": "sup-runner", "session_id": "ses-parent"})
	g.frames(runner)
	g.call("session children page", "session_children", map[string]any{"runner_id": "sup-runner", "session_id": "ses-parent", "limit": 1})
	g.frames(runner)
	g.call("session children bad limit", "session_children", map[string]any{"runner_id": "sup-runner", "session_id": "ses-parent", "limit": 0})
	g.frames(runner)
	g.call("session children unknown", "session_children", map[string]any{"runner_id": "sup-runner", "session_id": "ses-missing"})
	g.frames(runner)

	apiDo(t, "PUT", api+"/api/v1/runners/sup-runner/instances/ins-task", map[string]any{"kind": "task", "status": "busy", "project_id": p, "task_id": task, "session_ids": []string{"ses-old", "ses-live"}, "executor": "opencode", "started_at": 2, "last_seen": 2})
	g.call("resume live inject", "resume_task_with_context", map[string]any{"project": p, "task_id": task, "injected_context": "focus on the tests"})
	g.frames(runner)
	g.call("task after live inject", "task_get", map[string]any{"project": p, "task_id": task})

	g.call("resource health", "resource_health", map[string]any{"project": p})
	g.call("resource health task", "resource_health", map[string]any{"project": p, "task_id": task})
	g.call("events wait immediate", "events_wait", map[string]any{"project": "quiet-project", "timeout_ms": 0})
	g.call("events wait bad limit", "events_wait", map[string]any{"project": p, "timeout_ms": 0, "limit": 500})
	g.call("events wait bad cursor", "events_wait", map[string]any{"project": p, "timeout_ms": 0, "after": "not-a-cursor"})
	g.call("events wait filtered", "events_wait", map[string]any{"project": "quiet-project", "task_id": "t", "feature_id": "f", "type": "task.created", "timeout_ms": 0, "limit": 5})

	g.call("delivery gate", "delivery_gate", map[string]any{"project": p, "task_id": task})
	g.call("delivery gate unknown", "delivery_gate", map[string]any{"project": p, "task_id": "zzzzzzzz"})
	g.call("delivery gate missing", "delivery_gate", map[string]any{"project": p})
	g.call("delivery verify unconfigured", "delivery_verify", map[string]any{"project": p, "task_id": task, "expected_revision": 0})
	g.call("delivery verify missing", "delivery_verify", map[string]any{"project": p, "expected_revision": 0})
	g.call("delivery record missing command", "delivery_record", map[string]any{"project": p, "task_id": task})
	g.call("delivery record invalid policy", "delivery_record", map[string]any{"project": p, "task_id": task, "command": map[string]any{"action": "configure", "expected_revision": 0, "policy": map[string]any{"required": "merged", "repository": "not a repo"}}})
	g.call("delivery record unknown field", "delivery_record", map[string]any{"project": p, "task_id": task, "command": map[string]any{"action": "configure", "expected_revison": 0}})
	g.call("delivery record wrong type", "delivery_record", map[string]any{"project": p, "task_id": task, "command": map[string]any{"action": "configure", "expected_revision": "0"}})
	g.call("delivery record configure", "delivery_record", map[string]any{"project": p, "task_id": task, "command": map[string]any{"action": "configure", "expected_revision": 0, "policy": map[string]any{"required": "integrated", "repository": "huynle/brain-api", "pull_request": 42, "head": "0123456789abcdef0123456789abcdef01234567", "target": "main", "required_checks": []string{"ci/test", "ci/lint"}}}})
	g.call("delivery record stale", "delivery_record", map[string]any{"project": p, "task_id": task, "command": map[string]any{"action": "configure", "expected_revision": 0, "policy": map[string]any{"required": "none"}}})
	g.call("delivery record integration without evidence", "delivery_record", map[string]any{"project": p, "task_id": task, "command": map[string]any{"action": "integration", "expected_revision": 1, "artifact": "0123456789abcdef0123456789abcdef01234567", "passed": true, "evidence_reference": "ci#9"}})
	g.call("delivery record unknown action", "delivery_record", map[string]any{"project": p, "task_id": task, "command": map[string]any{"action": "ship", "expected_revision": 1}})
	g.call("delivery verify stale", "delivery_verify", map[string]any{"project": p, "task_id": task, "expected_revision": 7})
	g.call("delivery gate configured", "delivery_gate", map[string]any{"project": p, "task_id": task})
	g.call("delivery record unknown task", "delivery_record", map[string]any{"project": p, "task_id": "zzzzzzzz", "command": map[string]any{"action": "configure", "expected_revision": 0, "policy": map[string]any{"required": "none"}}})

	g.call("capabilities", "supervisor_capabilities", map[string]any{"project": p})
	g.call("snapshot", "supervisor_snapshot", map[string]any{"project": p})
	g.call("snapshot filtered", "supervisor_snapshot", map[string]any{"project": p, "task_id": task, "feature_id": "feat-s", "limit": 1, "after_task": "0"})
	g.call("snapshot bad limit", "supervisor_snapshot", map[string]any{"project": p, "limit": 1000})
	g.call("dispatch preview", "task_dispatch_preview", map[string]any{"project": p, "task_id": task})
	g.call("dispatch preview manual", "task_dispatch_preview", map[string]any{"project": p, "task_id": task, "manual": true})
	g.call("dispatch preview done", "task_dispatch_preview", map[string]any{"project": p2, "task_id": done})
	g.call("dispatch preview unknown", "task_dispatch_preview", map[string]any{"project": p, "task_id": "zzzzzzzz"})

	g.call("checkpoint list empty", "supervisor_checkpoint", map[string]any{"project": p})
	g.call("checkpoint request", "supervisor_checkpoint", map[string]any{"command": map[string]any{"action": "request", "expected_revision": 0, "checkpoint": map[string]any{"id": "chk-00001", "project": p, "task_id": task, "feature_id": "feat-s", "artifact": "commit abc123", "question": "Ship it?"}}})
	g.call("checkpoint request again", "supervisor_checkpoint", map[string]any{"command": map[string]any{"action": "request", "expected_revision": 0, "checkpoint": map[string]any{"id": "chk-00001", "project": p, "task_id": task, "feature_id": "feat-s", "artifact": "commit abc123", "question": "Ship it?"}}})
	g.call("checkpoint answer stale", "supervisor_checkpoint", map[string]any{"command": map[string]any{"action": "answer", "expected_revision": 0, "checkpoint": map[string]any{"id": "chk-00001", "project": p, "artifact": "commit abc123", "answer": "yes"}}})
	g.call("checkpoint answer", "supervisor_checkpoint", map[string]any{"command": map[string]any{"action": "answer", "expected_revision": 1, "checkpoint": map[string]any{"id": "chk-00001", "project": p, "artifact": "commit abc123", "answer": "yes"}}})
	g.call("checkpoint verify", "supervisor_checkpoint", map[string]any{"command": map[string]any{"action": "verify", "expected_revision": 2, "checkpoint": map[string]any{"id": "chk-00001", "project": p, "artifact": "commit abc123", "verification_reference": "ci#1"}}})
	g.call("checkpoint bounds", "supervisor_checkpoint", map[string]any{"command": map[string]any{"action": "request", "checkpoint": map[string]any{"id": "short", "project": p, "artifact": "a"}}})
	g.call("checkpoint unknown field", "supervisor_checkpoint", map[string]any{"command": map[string]any{"action": "request", "checkpoint": map[string]any{"id": "chk-00002"}, "extra": true}})
	g.call("checkpoint list", "supervisor_checkpoint", map[string]any{"project": p})
	g.call("checkpoint versions", "supervisor_checkpoint", map[string]any{"project": p, "id": "chk-00001"})
	g.call("checkpoint list after", "supervisor_checkpoint", map[string]any{"project": p, "after": "chk-00001"})

	g.call("budget unknown", "execution_budget", map[string]any{"project": p, "id": "bud-0001"})
	g.call("budget configure", "execution_budget", map[string]any{"command": map[string]any{"action": "configure", "expected_revision": 0, "budget": map[string]any{"id": "bud-0001", "project": p, "timezone": "UTC", "unit": "runs", "limit": 5}}})
	g.call("budget configure stale", "execution_budget", map[string]any{"command": map[string]any{"action": "configure", "expected_revision": 0, "budget": map[string]any{"id": "bud-0001", "project": p, "timezone": "UTC", "unit": "runs", "limit": 9}}})
	g.call("budget get", "execution_budget", map[string]any{"project": p, "id": "bud-0001"})
	g.call("budget reserve", "execution_budget", map[string]any{"command": map[string]any{"action": "reserve", "budget": map[string]any{"id": "bud-0001", "project": p}, "reservation_id": "res-0001", "units": 2}})
	g.call("budget reserve over", "execution_budget", map[string]any{"command": map[string]any{"action": "reserve", "budget": map[string]any{"id": "bud-0001", "project": p}, "reservation_id": "res-0002", "units": 50}})
	g.call("budget commit", "execution_budget", map[string]any{"command": map[string]any{"action": "commit", "budget": map[string]any{"id": "bud-0001", "project": p}, "reservation_id": "res-0001"}})
	g.call("budget cancel unknown", "execution_budget", map[string]any{"command": map[string]any{"action": "cancel", "budget": map[string]any{"id": "bud-0001", "project": p}, "reservation_id": "res-nope"}})
	g.call("budget get after", "execution_budget", map[string]any{"project": p, "id": "bud-0001"})
	g.call("budget unknown action", "execution_budget", map[string]any{"command": map[string]any{"action": "spend", "budget": map[string]any{"id": "bud-0001", "project": p}}})
	g.call("budget invalid identity", "execution_budget", map[string]any{"command": map[string]any{"action": "configure", "budget": map[string]any{"project": p}}})
	g.call("budget wrong type", "execution_budget", map[string]any{"command": map[string]any{"action": "reserve", "budget": map[string]any{"id": "bud-0001", "project": p}, "units": 1.5}})

	g.call("operation bad id", "supervisor_operation", map[string]any{"id": "short", "operation": "trigger", "project": p2, "task_id": done})
	g.call("operation unsupported", "supervisor_operation", map[string]any{"id": "op-unsupported-1", "operation": "explode"})
	g.call("operation unknown field", "supervisor_operation", map[string]any{"id": "op-extra-0001", "operation": "trigger", "project": p2, "task_id": done, "bogus": 1})
	g.call("operation prompt incomplete", "supervisor_operation", map[string]any{"id": "op-prompt-0001", "operation": "prompt", "runner_id": "sup-runner"})
	g.call("operation prompt", "supervisor_operation", map[string]any{"id": "op-prompt-0002", "operation": "prompt", "runner_id": "sup-runner", "instance_id": "ins-adhoc", "session_id": "ses-1", "text": "please summarize"})
	g.frames(runner)
	g.call("operation prompt replay", "supervisor_operation", map[string]any{"id": "op-prompt-0002", "operation": "prompt", "runner_id": "sup-runner", "instance_id": "ins-adhoc", "session_id": "ses-1", "text": "please summarize"})
	g.frames(runner)
	g.call("operation prompt conflict", "supervisor_operation", map[string]any{"id": "op-prompt-0002", "operation": "prompt", "runner_id": "sup-runner", "instance_id": "ins-adhoc", "session_id": "ses-1", "text": "different"})
	g.call("operation prompt unknown session", "supervisor_operation", map[string]any{"id": "op-prompt-0003", "operation": "prompt", "runner_id": "sup-runner", "instance_id": "ins-adhoc", "session_id": "ses-missing", "text": "x"})
	g.frames(runner)
	g.call("operation trigger", "supervisor_operation", map[string]any{"id": "op-trigger-0001", "operation": "trigger", "project": p2, "task_id": done})
	g.call("operation resume", "supervisor_operation", map[string]any{"id": "op-resume-0001", "operation": "resume_with_context", "project": p2, "task_id": done, "text": "resume with this"})
	g.call("operation checkpoint stale", "supervisor_operation", map[string]any{"id": "op-chk-00001", "operation": "trigger", "project": p, "task_id": task, "checkpoint_id": "chk-00001", "checkpoint_revision": 1})
	g.call("operation budget refused", "supervisor_operation", map[string]any{"id": "op-budget-0001", "operation": "trigger", "project": p, "task_id": task, "budget_id": "bud-0001", "budget_units": 99})
	g.call("operation budget", "supervisor_operation", map[string]any{"id": "op-budget-0002", "operation": "trigger", "project": p, "task_id": task, "budget_id": "bud-0001", "budget_units": 1, "parent_reservation": ""})
	g.call("operation wrong type", "supervisor_operation", map[string]any{"id": "op-type-00001", "operation": "trigger", "project": p2, "task_id": done, "budget_units": "one"})
	g.call("operation get", "supervisor_operation_get", map[string]any{"id": "op-prompt-0002"})
	g.call("operation get rejected", "supervisor_operation_get", map[string]any{"id": "op-budget-0001"})
	g.call("operation get unknown", "supervisor_operation_get", map[string]any{"id": "op-nothing-01"})
	g.call("operation get missing", "supervisor_operation_get", nil)
	g.call("operation get odd id", "supervisor_operation_get", map[string]any{"id": "a b/c"})

	dead := deadAPIMCP(t)
	g.callAt(dead, "dead tail", "session_tail", map[string]any{"runner_id": "r 1", "session_id": "s/1"})
	g.callAt(dead, "dead children", "session_children", map[string]any{"runner_id": "r", "session_id": "s"})
	g.callAt(dead, "dead resource health", "resource_health", map[string]any{"project": "p q"})
	g.callAt(dead, "dead events wait", "events_wait", map[string]any{"project": "p", "after": "c"})
	g.callAt(dead, "dead gate", "delivery_gate", map[string]any{"project": "p", "task_id": "t/1"})
	g.callAt(dead, "dead verify", "delivery_verify", map[string]any{"project": "p", "task_id": "t", "expected_revision": 3})
	g.callAt(dead, "dead record", "delivery_record", map[string]any{"project": "p", "task_id": "t", "command": map[string]any{"action": "configure"}})
	g.callAt(dead, "dead capabilities", "supervisor_capabilities", map[string]any{"project": "p", "limit": 5, "manual": true})
	g.callAt(dead, "dead snapshot", "supervisor_snapshot", map[string]any{"project": "p"})
	g.callAt(dead, "dead preview", "task_dispatch_preview", map[string]any{"project": "p", "task_id": "t", "manual": true})
	g.callAt(dead, "dead operation", "supervisor_operation", map[string]any{"id": "op-dead-0001", "operation": "trigger"})
	g.callAt(dead, "dead operation get", "supervisor_operation_get", map[string]any{"id": "op/1"})
	g.callAt(dead, "dead checkpoint list", "supervisor_checkpoint", map[string]any{"project": "p", "after": "x"})
	g.callAt(dead, "dead checkpoint command", "supervisor_checkpoint", map[string]any{"command": map[string]any{"action": "request"}})
	g.callAt(dead, "dead budget get", "execution_budget", map[string]any{"project": "p", "id": "b"})
	g.callAt(dead, "dead budget command", "execution_budget", map[string]any{"command": map[string]any{"action": "commit"}})
	g.check()
}
