package plugins

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestOpenCodeTarget_ID(t *testing.T) {
	target := &OpenCodeTarget{}
	if got := target.ID(); got != "opencode" {
		t.Errorf("ID() = %q, want %q", got, "opencode")
	}
}

func TestOpenCodeTarget_Name(t *testing.T) {
	target := &OpenCodeTarget{}
	if got := target.Name(); got != "OpenCode" {
		t.Errorf("Name() = %q, want %q", got, "OpenCode")
	}
}

func TestOpenCodeTarget_Description(t *testing.T) {
	target := &OpenCodeTarget{}
	desc := target.Description()
	if desc == "" {
		t.Error("Description() returned empty string")
	}
	if !strings.Contains(desc, "OpenCode") {
		t.Errorf("Description() = %q, should mention OpenCode", desc)
	}
}

func TestOpenCodeTarget_Exists_ReturnsFalseWhenConfigMissing(t *testing.T) {
	// Create temp dir that doesn't contain .config/opencode
	tmpDir := t.TempDir()

	target := &OpenCodeTarget{
		configPath: filepath.Join(tmpDir, ".config", "opencode"),
	}

	if target.Exists() {
		t.Error("Exists() = true, want false when config directory missing")
	}
}

func TestOpenCodeTarget_Exists_ReturnsTrueWhenConfigExists(t *testing.T) {
	// Create temp dir with .config/opencode
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")
	if err := os.MkdirAll(configPath, 0755); err != nil {
		t.Fatalf("Failed to create test config dir: %v", err)
	}

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	if !target.Exists() {
		t.Error("Exists() = false, want true when config directory exists")
	}
}

func TestOpenCodeTarget_Install_CreatesPluginDirectory(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	pluginDir := filepath.Join(configPath, "plugin")
	if _, err := os.Stat(pluginDir); os.IsNotExist(err) {
		t.Error("Install() did not create plugin directory")
	}
}

func TestOpenCodeTarget_Install_CopiesPluginFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// Check that brain.ts and brain-planning.ts were installed
	pluginDir := filepath.Join(configPath, "plugin")

	expectedFiles := []string{"brain.ts", "brain-planning.ts"}
	for _, filename := range expectedFiles {
		filePath := filepath.Join(pluginDir, filename)
		if _, err := os.Stat(filePath); os.IsNotExist(err) {
			t.Errorf("Install() did not copy %s", filename)
		}
	}
}

func TestOpenCodeTarget_Install_SkipsREADME(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// README.md should NOT be installed
	pluginDir := filepath.Join(configPath, "plugin")
	readmePath := filepath.Join(pluginDir, "README.md")

	if _, err := os.Stat(readmePath); !os.IsNotExist(err) {
		t.Error("Install() should not copy README.md")
	}
}

func TestOpenCodeTarget_Install_AddsAutoGeneratedHeader(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// Check that installed file has auto-generated header
	pluginDir := filepath.Join(configPath, "plugin")
	filePath := filepath.Join(pluginDir, "brain.ts")

	content, err := os.ReadFile(filePath)
	if err != nil {
		t.Fatalf("Failed to read installed file: %v", err)
	}

	contentStr := string(content)
	if !strings.Contains(contentStr, "AUTO-GENERATED FILE") {
		t.Error("Installed file should contain AUTO-GENERATED header")
	}
	if !strings.Contains(contentStr, "brain install opencode") {
		t.Error("Header should mention 'brain install opencode'")
	}
}

func TestOpenCodeTarget_Install_DryRunDoesNotCreateFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	opts := InstallOptions{
		DryRun: true,
	}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() with DryRun failed: %v", err)
	}

	// Plugin directory may be created, but files should not be
	pluginDir := filepath.Join(configPath, "plugin")

	// Check that no plugin files were created
	entries, err := os.ReadDir(pluginDir)
	if err != nil {
		// Directory might not exist in dry-run, that's ok
		if !os.IsNotExist(err) {
			t.Fatalf("Failed to read plugin dir: %v", err)
		}
		return
	}

	for _, entry := range entries {
		if strings.HasSuffix(entry.Name(), ".ts") {
			t.Errorf("DryRun should not create file: %s", entry.Name())
		}
	}
}

func TestOpenCodeTarget_Install_ForceOverwritesExistingFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")
	pluginDir := filepath.Join(configPath, "plugin")

	// Create plugin directory and an existing file
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		t.Fatalf("Failed to create plugin dir: %v", err)
	}

	existingFile := filepath.Join(pluginDir, "brain.ts")
	existingContent := "// Old content"
	if err := os.WriteFile(existingFile, []byte(existingContent), 0644); err != nil {
		t.Fatalf("Failed to create existing file: %v", err)
	}

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	opts := InstallOptions{
		Force: true,
	}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() with Force failed: %v", err)
	}

	// Check that file was overwritten
	content, err := os.ReadFile(existingFile)
	if err != nil {
		t.Fatalf("Failed to read file after install: %v", err)
	}

	if string(content) == existingContent {
		t.Error("Force install should overwrite existing file")
	}
}

func TestOpenCodeTarget_Install_WithoutForceFailsIfFilesExist(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")
	pluginDir := filepath.Join(configPath, "plugin")

	// Create plugin directory and an existing file
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		t.Fatalf("Failed to create plugin dir: %v", err)
	}

	existingFile := filepath.Join(pluginDir, "brain.ts")
	if err := os.WriteFile(existingFile, []byte("existing"), 0644); err != nil {
		t.Fatalf("Failed to create existing file: %v", err)
	}

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	opts := InstallOptions{
		Force: false,
	}
	err := target.Install(opts)

	if err == nil {
		t.Fatal("Install() should fail when files exist without Force")
	}

	if !strings.Contains(err.Error(), "exists") {
		t.Errorf("Error should mention file exists, got: %v", err)
	}
}

func TestOpenCodeTarget_Uninstall_RemovesPluginFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")
	pluginDir := filepath.Join(configPath, "plugin")

	// Create plugin directory with files
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		t.Fatalf("Failed to create plugin dir: %v", err)
	}

	testFiles := []string{"brain.ts", "brain-planning.ts"}
	for _, filename := range testFiles {
		filePath := filepath.Join(pluginDir, filename)
		if err := os.WriteFile(filePath, []byte("test"), 0644); err != nil {
			t.Fatalf("Failed to create test file: %v", err)
		}
	}

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	err := target.Uninstall()
	if err != nil {
		t.Fatalf("Uninstall() failed: %v", err)
	}

	// Check that files were removed
	for _, filename := range testFiles {
		filePath := filepath.Join(pluginDir, filename)
		if _, err := os.Stat(filePath); !os.IsNotExist(err) {
			t.Errorf("Uninstall() did not remove %s", filename)
		}
	}
}

func TestOpenCodeTarget_Validate_DetectsMissingFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")
	pluginDir := filepath.Join(configPath, "plugin")

	// Create plugin directory but don't add any files
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		t.Fatalf("Failed to create plugin dir: %v", err)
	}

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	err := target.Validate()
	if err == nil {
		t.Fatal("Validate() should fail when plugin files are missing")
	}
}

func TestOpenCodeTarget_Validate_PassesWhenFilesExist(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	// Install first
	opts := InstallOptions{}
	if err := target.Install(opts); err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// Now validate
	err := target.Validate()
	if err != nil {
		t.Errorf("Validate() should pass after successful install, got: %v", err)
	}
}

func TestGetAvailableTargets_ReturnsOpenCodeTarget(t *testing.T) {
	targets := GetAvailableTargets()

	if len(targets) == 0 {
		t.Fatal("GetAvailableTargets() returned empty list")
	}

	found := false
	for _, target := range targets {
		if target.ID() == "opencode" {
			found = true
			break
		}
	}

	if !found {
		t.Error("GetAvailableTargets() should include opencode target")
	}
}
