package plugins

import (
	"bytes"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func capturePluginOutput(t *testing.T, f func()) string {
	t.Helper()

	old := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("failed to capture stdout: %v", err)
	}
	os.Stdout = w

	f()

	_ = w.Close()
	os.Stdout = old

	var buf bytes.Buffer
	_, _ = io.Copy(&buf, r)
	return buf.String()
}

func TestOpenCodeTarget_ID(t *testing.T) {
	target := &OpenCodeTarget{}
	if got := target.ID(); got != "opencode" {
		t.Errorf("ID() = %q, want %q", got, "opencode")
	}
}

func TestOpenCodeTarget_Name(t *testing.T) {
	target := &OpenCodeTarget{}
	if got := target.Name(); got != "OpenCode" {
		t.Errorf("Name() = %q, want %q", got, "OpenCode")
	}
}

func TestOpenCodeTarget_Description(t *testing.T) {
	target := &OpenCodeTarget{}
	desc := target.Description()
	if desc == "" {
		t.Error("Description() returned empty string")
	}
	if !strings.Contains(desc, "OpenCode") {
		t.Errorf("Description() = %q, should mention OpenCode", desc)
	}
}

func TestOpenCodeTarget_Exists_ReturnsFalseWhenConfigMissing(t *testing.T) {
	// Create temp dir that doesn't contain .config/opencode
	tmpDir := t.TempDir()

	target := &OpenCodeTarget{
		configPath: filepath.Join(tmpDir, ".config", "opencode"),
	}

	if target.Exists() {
		t.Error("Exists() = true, want false when config directory missing")
	}
}

func TestOpenCodeTarget_Exists_ReturnsTrueWhenConfigExists(t *testing.T) {
	// Create temp dir with .config/opencode
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")
	if err := os.MkdirAll(configPath, 0755); err != nil {
		t.Fatalf("Failed to create test config dir: %v", err)
	}

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	if !target.Exists() {
		t.Error("Exists() = false, want true when config directory exists")
	}
}

func TestOpenCodeTarget_Install_CreatesAgentDirectory(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// After the brain.ts → MCP migration, no top-level plugin/*.ts files
	// ship with opencode assets, so plugin/ is no longer guaranteed to be
	// created. The agent/ directory always is, since brain-planner.md ships.
	agentDir := filepath.Join(configPath, "agent")
	if _, err := os.Stat(agentDir); os.IsNotExist(err) {
		t.Error("Install() did not create agent directory")
	}
}

func TestOpenCodeTarget_Install_CopiesPluginFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// Check that representative agent/skill/command files were installed.
	// Top-level plugin/*.ts files are no longer shipped (Brain tools moved
	// to the brain MCP stdio server), but the tdd-enforcement plugin and its
	// bun-shim dependency DO ship under plugin/ and tool/lib/ so the tdd-dev
	// agent (dispatched by the brain-runner-queue skill on Route B/C) has a
	// working tdd_gate tool.
	expectedFiles := []string{
		"agent/brain-planner.md",
		"agent/tdd-dev.md",
		"command/do.md",
		"skill/brain-memory/SKILL.md",
		"skill/test-driven-development/SKILL.md",
		"skill/root-cause-tracing/SKILL.md",
		"skill/root-cause-tracing/find-polluter.sh",
		"skill/verification-before-completion/SKILL.md",
		"plugin/tdd-enforcement.ts",
		"tool/lib/bun-shim.ts",
	}
	for _, rel := range expectedFiles {
		filePath := filepath.Join(configPath, rel)
		if _, err := os.Stat(filePath); os.IsNotExist(err) {
			t.Errorf("Install() did not copy %s", rel)
		}
	}
}

func TestOpenCodeTarget_Install_SkipsREADME(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// README.md should NOT be installed
	pluginDir := filepath.Join(configPath, "plugin")
	readmePath := filepath.Join(pluginDir, "README.md")

	if _, err := os.Stat(readmePath); !os.IsNotExist(err) {
		t.Error("Install() should not copy README.md")
	}
}

func TestOpenCodeTarget_Install_AddsAutoGeneratedHeader(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// Check that an installed markdown file has the auto-generated header.
	// Use the brain-planner agent file as a representative installed asset.
	filePath := filepath.Join(configPath, "agent", "brain-planner.md")

	content, err := os.ReadFile(filePath)
	if err != nil {
		t.Fatalf("Failed to read installed file: %v", err)
	}

	contentStr := string(content)
	if !strings.Contains(contentStr, "AUTO-GENERATED FILE") {
		t.Error("Installed file should contain AUTO-GENERATED header")
	}
	if !strings.Contains(contentStr, "brain install opencode") {
		t.Error("Header should mention 'brain install opencode'")
	}
}

func TestOpenCodeTarget_Install_SkillStartsWithFrontmatter(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	err := target.Install(InstallOptions{})
	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	filePath := filepath.Join(configPath, "skill", "brain-runner-queue", "SKILL.md")
	content, err := os.ReadFile(filePath)
	if err != nil {
		t.Fatalf("Failed to read installed skill file: %v", err)
	}

	memorySkillPath := filepath.Join(configPath, "skill", "brain-memory", "SKILL.md")
	memoryContent, err := os.ReadFile(memorySkillPath)
	if err != nil {
		t.Fatalf("Failed to read installed memory skill file: %v", err)
	}
	if !strings.Contains(string(memoryContent), "name: brain-memory") {
		t.Fatal("installed memory skill should contain brain-memory frontmatter")
	}

	contentStr := string(content)
	if !strings.HasPrefix(contentStr, "---\n") {
		t.Fatalf("installed skill must start with YAML frontmatter for OpenCode discovery, got prefix %q", contentStr[:min(len(contentStr), 40)])
	}
	if !strings.Contains(contentStr, "AUTO-GENERATED FILE") {
		t.Error("Installed skill should still contain AUTO-GENERATED header")
	}
}

func TestOpenCodeTarget_Install_DryRunDoesNotCreateFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	opts := InstallOptions{
		DryRun: true,
	}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() with DryRun failed: %v", err)
	}

	// Plugin directory may be created, but files should not be
	pluginDir := filepath.Join(configPath, "plugin")

	// Check that no plugin files were created
	entries, err := os.ReadDir(pluginDir)
	if err != nil {
		// Directory might not exist in dry-run, that's ok
		if !os.IsNotExist(err) {
			t.Fatalf("Failed to read plugin dir: %v", err)
		}
		return
	}

	for _, entry := range entries {
		if strings.HasSuffix(entry.Name(), ".ts") {
			t.Errorf("DryRun should not create file: %s", entry.Name())
		}
	}
}

func TestOpenCodeTarget_Install_ForceOverwritesExistingFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")

	// Seed an existing installed asset that Install will overwrite.
	agentDir := filepath.Join(configPath, "agent")
	if err := os.MkdirAll(agentDir, 0755); err != nil {
		t.Fatalf("Failed to create agent dir: %v", err)
	}

	existingFile := filepath.Join(agentDir, "brain-planner.md")
	existingContent := "# Old content"
	if err := os.WriteFile(existingFile, []byte(existingContent), 0644); err != nil {
		t.Fatalf("Failed to create existing file: %v", err)
	}

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	opts := InstallOptions{
		Force: true,
	}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() with Force failed: %v", err)
	}

	// Check that file was overwritten
	content, err := os.ReadFile(existingFile)
	if err != nil {
		t.Fatalf("Failed to read file after install: %v", err)
	}

	if string(content) == existingContent {
		t.Error("Force install should overwrite existing file")
	}
}

func TestOpenCodeTarget_Install_ForceReportsUpdatedFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")
	agentDir := filepath.Join(configPath, "agent")

	if err := os.MkdirAll(agentDir, 0755); err != nil {
		t.Fatalf("Failed to create agent dir: %v", err)
	}

	existingFile := filepath.Join(agentDir, "brain-planner.md")
	if err := os.WriteFile(existingFile, []byte("# Old content"), 0644); err != nil {
		t.Fatalf("Failed to create existing file: %v", err)
	}

	target := &OpenCodeTarget{configPath: configPath}

	var installErr error
	output := capturePluginOutput(t, func() {
		installErr = target.Install(InstallOptions{Force: true})
	})
	if installErr != nil {
		t.Fatalf("Install() with Force failed: %v", installErr)
	}

	if !strings.Contains(output, "Updated: agent/brain-planner.md") {
		t.Fatalf("force install should report updated file, output:\n%s", output)
	}
}

func TestOpenCodeTarget_Install_ForceReportsIdenticalFilesAndLeavesUntouched(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")
	target := &OpenCodeTarget{configPath: configPath}

	if err := target.Install(InstallOptions{}); err != nil {
		t.Fatalf("initial Install() failed: %v", err)
	}

	installedFile := filepath.Join(configPath, "agent", "brain-planner.md")
	oldTime := time.Date(2024, 1, 2, 3, 4, 5, 0, time.UTC)
	if err := os.Chtimes(installedFile, oldTime, oldTime); err != nil {
		t.Fatalf("failed to set file time: %v", err)
	}

	var installErr error
	output := capturePluginOutput(t, func() {
		installErr = target.Install(InstallOptions{Force: true})
	})
	if installErr != nil {
		t.Fatalf("Install() with Force failed: %v", installErr)
	}

	if !strings.Contains(output, "Identical: agent/brain-planner.md (left untouched)") {
		t.Fatalf("force install should report identical file left untouched, output:\n%s", output)
	}

	info, err := os.Stat(installedFile)
	if err != nil {
		t.Fatalf("failed to stat installed file: %v", err)
	}
	if !info.ModTime().Equal(oldTime) {
		t.Fatalf("identical file should be left untouched; modtime = %s, want %s", info.ModTime(), oldTime)
	}
}

func TestOpenCodeTarget_Install_ForceIsIdempotentAcrossRuns(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")
	target := &OpenCodeTarget{configPath: configPath}

	if err := target.Install(InstallOptions{}); err != nil {
		t.Fatalf("initial Install() failed: %v", err)
	}

	installedFile := filepath.Join(configPath, "agent", "brain-planner.md")
	before, err := os.ReadFile(installedFile)
	if err != nil {
		t.Fatalf("failed to read installed file: %v", err)
	}

	// The generated file content must be stable across invocations so --force
	// only updates files when the embedded source changes.
	time.Sleep(1100 * time.Millisecond)

	var installErr error
	output := capturePluginOutput(t, func() {
		installErr = target.Install(InstallOptions{Force: true})
	})
	if installErr != nil {
		t.Fatalf("force Install() failed: %v", installErr)
	}

	after, err := os.ReadFile(installedFile)
	if err != nil {
		t.Fatalf("failed to read installed file after force: %v", err)
	}
	if !bytes.Equal(after, before) {
		t.Fatal("force install should not rewrite unchanged generated content")
	}
	if !strings.Contains(output, "Identical: agent/brain-planner.md (left untouched)") {
		t.Fatalf("force install should report unchanged file as identical, output:\n%s", output)
	}
	if strings.Contains(output, "Updated: agent/brain-planner.md") {
		t.Fatalf("force install should not update unchanged file, output:\n%s", output)
	}
}

func TestOpenCodeTarget_Install_ForceRemovesRetiredBrainGeneratedSkills(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")
	target := &OpenCodeTarget{configPath: configPath}

	retiredSkill := filepath.Join(configPath, "skill", "brain-dream-context", "SKILL.md")
	if err := os.MkdirAll(filepath.Dir(retiredSkill), 0755); err != nil {
		t.Fatalf("failed to create retired skill dir: %v", err)
	}
	if err := os.WriteFile(retiredSkill, []byte("---\nname: brain-dream-context\ndescription: old\n---\n\n<!--\nAUTO-GENERATED FILE - DO NOT EDIT DIRECTLY\n\nThis file was installed by: brain install opencode\n-->\n"), 0644); err != nil {
		t.Fatalf("failed to create retired skill: %v", err)
	}

	retiredPlugin := filepath.Join(configPath, "plugin", "brain-planning.ts")
	retiredBrainTS := filepath.Join(configPath, "plugin", "brain.ts")
	retiredCommand := filepath.Join(configPath, "command", "execute-plan.md")
	retiredTool := filepath.Join(configPath, "tool", "plan-checkout", "index.ts")
	for _, file := range []string{retiredPlugin, retiredBrainTS, retiredCommand, retiredTool} {
		if err := os.MkdirAll(filepath.Dir(file), 0755); err != nil {
			t.Fatalf("failed to create retired file dir: %v", err)
		}
		if err := os.WriteFile(file, []byte("<!--\nAUTO-GENERATED FILE - DO NOT EDIT DIRECTLY\n\nThis file was installed by: brain install opencode\n-->\n"), 0644); err != nil {
			t.Fatalf("failed to create retired file: %v", err)
		}
	}

	userSkill := filepath.Join(configPath, "skill", "brain-user-skill", "SKILL.md")
	if err := os.MkdirAll(filepath.Dir(userSkill), 0755); err != nil {
		t.Fatalf("failed to create user skill dir: %v", err)
	}
	if err := os.WriteFile(userSkill, []byte("---\nname: brain-user-skill\ndescription: keep me\n---\n"), 0644); err != nil {
		t.Fatalf("failed to create user skill: %v", err)
	}

	var installErr error
	output := capturePluginOutput(t, func() {
		installErr = target.Install(InstallOptions{Force: true})
	})
	if installErr != nil {
		t.Fatalf("Install() with Force failed: %v", installErr)
	}

	for _, file := range []string{retiredSkill, retiredPlugin, retiredBrainTS, retiredCommand, retiredTool} {
		if _, err := os.Stat(file); !os.IsNotExist(err) {
			t.Fatalf("force install should remove retired generated file %s, stat err: %v", file, err)
		}
	}
	if _, err := os.Stat(userSkill); err != nil {
		t.Fatalf("force install should leave user-created skills untouched: %v", err)
	}
	for _, want := range []string{
		"Removed retired: skill/brain-dream-context/SKILL.md",
		"Removed retired: plugin/brain-planning.ts",
		"Removed retired: plugin/brain.ts",
		"Removed retired: command/execute-plan.md",
		"Removed retired: tool/plan-checkout/index.ts",
	} {
		if !strings.Contains(output, want) {
			t.Fatalf("force install should report retired file removal %q, output:\n%s", want, output)
		}
	}
}

func TestOpenCodeTarget_Install_WithoutForceSkipsExistingFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")
	agentDir := filepath.Join(configPath, "agent")

	// Seed an existing installed asset that Install should not overwrite without --force.
	if err := os.MkdirAll(agentDir, 0755); err != nil {
		t.Fatalf("Failed to create agent dir: %v", err)
	}

	existingFile := filepath.Join(agentDir, "brain-planner.md")
	if err := os.WriteFile(existingFile, []byte("existing"), 0644); err != nil {
		t.Fatalf("Failed to create existing file: %v", err)
	}

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	opts := InstallOptions{
		Force: false,
	}
	err := target.Install(opts)

	// Should succeed — existing files are skipped, new files still installed
	if err != nil {
		t.Fatalf("Install() should succeed (skip existing, install rest): %v", err)
	}

	// Existing file should NOT be overwritten
	content, _ := os.ReadFile(existingFile)
	if string(content) != "existing" {
		t.Errorf("Existing file should not be overwritten without --force")
	}
}

func TestOpenCodeTarget_Uninstall_RemovesPluginFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")
	agentDir := filepath.Join(configPath, "agent")
	skillDir := filepath.Join(configPath, "skill", "brain-memory")

	// Uninstall removes files that currently ship in the embedded asset
	// tree. Seed two such files (an agent and a skill) so we exercise the
	// recursive-cleanup path. Top-level plugin/*.ts cleanup is covered by
	// the retired-files logic exercised in
	// TestOpenCodeTarget_Install_ForceRemovesRetiredBrainGeneratedSkills.
	if err := os.MkdirAll(agentDir, 0755); err != nil {
		t.Fatalf("Failed to create agent dir: %v", err)
	}
	if err := os.MkdirAll(skillDir, 0755); err != nil {
		t.Fatalf("Failed to create skill dir: %v", err)
	}

	agentFile := filepath.Join(agentDir, "brain-planner.md")
	skillFile := filepath.Join(skillDir, "SKILL.md")
	for _, file := range []string{agentFile, skillFile} {
		if err := os.WriteFile(file, []byte("test"), 0644); err != nil {
			t.Fatalf("Failed to create test file %s: %v", file, err)
		}
	}

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	err := target.Uninstall()
	if err != nil {
		t.Fatalf("Uninstall() failed: %v", err)
	}

	for _, file := range []string{agentFile, skillFile} {
		if _, err := os.Stat(file); !os.IsNotExist(err) {
			t.Errorf("Uninstall() did not remove %s", file)
		}
	}
}

func TestOpenCodeTarget_Validate_DetectsMissingFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")
	pluginDir := filepath.Join(configPath, "plugin")

	// Create plugin directory but don't add any files
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		t.Fatalf("Failed to create plugin dir: %v", err)
	}

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	err := target.Validate()
	if err == nil {
		t.Fatal("Validate() should fail when plugin files are missing")
	}
}

func TestOpenCodeTarget_Validate_PassesWhenFilesExist(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".config", "opencode")

	target := &OpenCodeTarget{
		configPath: configPath,
	}

	// Install first
	opts := InstallOptions{}
	if err := target.Install(opts); err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// Now validate
	err := target.Validate()
	if err != nil {
		t.Errorf("Validate() should pass after successful install, got: %v", err)
	}
}

func TestGetAvailableTargets_ReturnsOpenCodeTarget(t *testing.T) {
	targets := GetAvailableTargets()

	if len(targets) == 0 {
		t.Fatal("GetAvailableTargets() returned empty list")
	}

	found := false
	for _, target := range targets {
		if target.ID() == "opencode" {
			found = true
			break
		}
	}

	if !found {
		t.Error("GetAvailableTargets() should include opencode target")
	}
}
