package plugins

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestPiTarget_ID(t *testing.T) {
	target := &PiTarget{}
	if got := target.ID(); got != "pi" {
		t.Errorf("ID() = %q, want %q", got, "pi")
	}
}

func TestPiTarget_Name(t *testing.T) {
	target := &PiTarget{}
	if got := target.Name(); got != "Pi Coding Agent" {
		t.Errorf("Name() = %q, want %q", got, "Pi Coding Agent")
	}
}

func TestPiTarget_Description(t *testing.T) {
	target := &PiTarget{}
	desc := target.Description()
	if desc == "" {
		t.Error("Description() returned empty string")
	}
	if !strings.Contains(desc, "Pi") {
		t.Errorf("Description() = %q, should mention Pi", desc)
	}
}

func TestPiTarget_Exists_ReturnsFalseWhenConfigMissing(t *testing.T) {
	tmpDir := t.TempDir()

	target := &PiTarget{
		configPath: filepath.Join(tmpDir, ".pi"),
	}

	if target.Exists() {
		t.Error("Exists() = true, want false when config directory missing")
	}
}

func TestPiTarget_Exists_ReturnsTrueWhenConfigExists(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".pi")
	if err := os.MkdirAll(configPath, 0755); err != nil {
		t.Fatalf("Failed to create test config dir: %v", err)
	}

	target := &PiTarget{
		configPath: configPath,
	}

	if !target.Exists() {
		t.Error("Exists() = false, want true when config directory exists")
	}
}

func TestPiTarget_Install_CreatesBrainAgentsDirectory(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".pi")

	target := &PiTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	agentsDir := filepath.Join(configPath, "brain-agents")
	if _, err := os.Stat(agentsDir); os.IsNotExist(err) {
		t.Error("Install() did not create brain-agents directory")
	}
}

func TestPiTarget_Install_CreatesExtensionsDirectory(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".pi")

	target := &PiTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	extDir := filepath.Join(configPath, "extensions")
	if _, err := os.Stat(extDir); os.IsNotExist(err) {
		t.Error("Install() did not create extensions directory")
	}
}

func TestPiTarget_Install_CopiesAgentBundles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".pi")

	target := &PiTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// Check tdd-dev agent bundle
	tddDevFiles := []string{"config.json", "system-prompt.md", "extension.ts"}
	for _, filename := range tddDevFiles {
		filePath := filepath.Join(configPath, "brain-agents", "tdd-dev", filename)
		if _, err := os.Stat(filePath); os.IsNotExist(err) {
			t.Errorf("Install() did not copy tdd-dev/%s", filename)
		}
	}

	// Check explore agent bundle
	exploreFiles := []string{"config.json", "system-prompt.md", "extension.ts"}
	for _, filename := range exploreFiles {
		filePath := filepath.Join(configPath, "brain-agents", "explore", filename)
		if _, err := os.Stat(filePath); os.IsNotExist(err) {
			t.Errorf("Install() did not copy explore/%s", filename)
		}
	}
}

func TestPiTarget_Install_CopiesExtensions(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".pi")

	target := &PiTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// Check brain-tools.ts extension
	filePath := filepath.Join(configPath, "extensions", "brain-tools.ts")
	if _, err := os.Stat(filePath); os.IsNotExist(err) {
		t.Error("Install() did not copy extensions/brain-tools.ts")
	}
}

func TestPiTarget_Install_SkipsREADME(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".pi")

	target := &PiTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// README.md should NOT be installed at the root
	readmePath := filepath.Join(configPath, "README.md")
	if _, err := os.Stat(readmePath); !os.IsNotExist(err) {
		t.Error("Install() should not copy README.md to config root")
	}

	// README.md should NOT be installed in brain-agents
	readmePath = filepath.Join(configPath, "brain-agents", "README.md")
	if _, err := os.Stat(readmePath); !os.IsNotExist(err) {
		t.Error("Install() should not copy README.md to brain-agents")
	}
}

func TestPiTarget_Install_AddsAutoGeneratedHeaderToTS(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".pi")

	target := &PiTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// Check that installed .ts file has auto-generated header
	filePath := filepath.Join(configPath, "extensions", "brain-tools.ts")

	content, err := os.ReadFile(filePath)
	if err != nil {
		t.Fatalf("Failed to read installed file: %v", err)
	}

	contentStr := string(content)
	if !strings.Contains(contentStr, "AUTO-GENERATED FILE") {
		t.Error("Installed .ts file should contain AUTO-GENERATED header")
	}
	if !strings.Contains(contentStr, "brain install pi") {
		t.Error("Header should mention 'brain install pi'")
	}
}

func TestPiTarget_Install_AddsAutoGeneratedHeaderToMD(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".pi")

	target := &PiTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// Check that installed .md file has auto-generated header
	filePath := filepath.Join(configPath, "brain-agents", "tdd-dev", "system-prompt.md")

	content, err := os.ReadFile(filePath)
	if err != nil {
		t.Fatalf("Failed to read installed file: %v", err)
	}

	contentStr := string(content)
	if !strings.Contains(contentStr, "AUTO-GENERATED FILE") {
		t.Error("Installed .md file should contain AUTO-GENERATED header")
	}
	if !strings.Contains(contentStr, "brain install pi") {
		t.Error("Header should mention 'brain install pi'")
	}
}

func TestPiTarget_Install_DryRunDoesNotCreateFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".pi")

	target := &PiTarget{
		configPath: configPath,
	}

	opts := InstallOptions{
		DryRun: true,
	}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() with DryRun failed: %v", err)
	}

	// brain-agents directory should NOT exist in dry-run
	agentsDir := filepath.Join(configPath, "brain-agents")
	if _, err := os.Stat(agentsDir); !os.IsNotExist(err) {
		t.Error("DryRun should not create brain-agents directory")
	}

	// extensions directory should NOT exist in dry-run
	extDir := filepath.Join(configPath, "extensions")
	if _, err := os.Stat(extDir); !os.IsNotExist(err) {
		t.Error("DryRun should not create extensions directory")
	}
}

func TestPiTarget_Install_ForceOverwritesExistingFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".pi")
	extDir := filepath.Join(configPath, "extensions")

	// Create directory and an existing file
	if err := os.MkdirAll(extDir, 0755); err != nil {
		t.Fatalf("Failed to create extensions dir: %v", err)
	}

	existingFile := filepath.Join(extDir, "brain-tools.ts")
	existingContent := "// Old content"
	if err := os.WriteFile(existingFile, []byte(existingContent), 0644); err != nil {
		t.Fatalf("Failed to create existing file: %v", err)
	}

	target := &PiTarget{
		configPath: configPath,
	}

	opts := InstallOptions{
		Force: true,
	}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() with Force failed: %v", err)
	}

	// Check that file was overwritten
	content, err := os.ReadFile(existingFile)
	if err != nil {
		t.Fatalf("Failed to read file after install: %v", err)
	}

	if string(content) == existingContent {
		t.Error("Force install should overwrite existing file")
	}
}

func TestPiTarget_Install_WithoutForceSkipsExistingFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".pi")
	extDir := filepath.Join(configPath, "extensions")

	// Create directory and an existing file
	if err := os.MkdirAll(extDir, 0755); err != nil {
		t.Fatalf("Failed to create extensions dir: %v", err)
	}

	existingFile := filepath.Join(extDir, "brain-tools.ts")
	if err := os.WriteFile(existingFile, []byte("existing"), 0644); err != nil {
		t.Fatalf("Failed to create existing file: %v", err)
	}

	target := &PiTarget{
		configPath: configPath,
	}

	opts := InstallOptions{
		Force: false,
	}
	err := target.Install(opts)

	// Should succeed — existing files are skipped, new files still installed
	if err != nil {
		t.Fatalf("Install() should succeed (skip existing, install rest): %v", err)
	}

	// Existing file should NOT be overwritten
	content, _ := os.ReadFile(existingFile)
	if string(content) != "existing" {
		t.Errorf("Existing file should not be overwritten without --force")
	}
}

func TestPiTarget_Uninstall_RemovesInstalledFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".pi")

	target := &PiTarget{
		configPath: configPath,
	}

	// Install first
	opts := InstallOptions{}
	if err := target.Install(opts); err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// Verify files exist before uninstall
	extFile := filepath.Join(configPath, "extensions", "brain-tools.ts")
	if _, err := os.Stat(extFile); os.IsNotExist(err) {
		t.Fatal("Expected brain-tools.ts to exist before uninstall")
	}

	err := target.Uninstall()
	if err != nil {
		t.Fatalf("Uninstall() failed: %v", err)
	}

	// Check that files were removed
	filesToCheck := []string{
		filepath.Join(configPath, "extensions", "brain-tools.ts"),
		filepath.Join(configPath, "brain-agents", "tdd-dev", "config.json"),
		filepath.Join(configPath, "brain-agents", "tdd-dev", "system-prompt.md"),
		filepath.Join(configPath, "brain-agents", "tdd-dev", "extension.ts"),
		filepath.Join(configPath, "brain-agents", "explore", "config.json"),
		filepath.Join(configPath, "brain-agents", "explore", "system-prompt.md"),
		filepath.Join(configPath, "brain-agents", "explore", "extension.ts"),
	}

	for _, filePath := range filesToCheck {
		if _, err := os.Stat(filePath); !os.IsNotExist(err) {
			t.Errorf("Uninstall() did not remove %s", filePath)
		}
	}
}

func TestPiTarget_Validate_DetectsMissingFiles(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".pi")

	// Create config directory but don't install files
	if err := os.MkdirAll(configPath, 0755); err != nil {
		t.Fatalf("Failed to create config dir: %v", err)
	}

	target := &PiTarget{
		configPath: configPath,
	}

	err := target.Validate()
	if err == nil {
		t.Fatal("Validate() should fail when files are missing")
	}

	// Should mention missing files (not just the pi binary check)
	if !strings.Contains(err.Error(), "missing files") && !strings.Contains(err.Error(), "pi binary") {
		t.Errorf("Validate() error = %q, should mention missing files or pi binary", err.Error())
	}
}

func TestPiTarget_Validate_PassesWhenFilesExist(t *testing.T) {
	// Skip if pi binary is not on PATH — can't fully validate without it
	// But we can at least test that Install+Validate file checking works
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".pi")

	target := &PiTarget{
		configPath: configPath,
	}

	// Install first
	opts := InstallOptions{}
	if err := target.Install(opts); err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// Validate - may fail on pi binary check, but should not fail on missing files
	err := target.Validate()
	if err != nil {
		// If it fails, it should only be because pi binary is not on PATH
		if !strings.Contains(err.Error(), "pi binary") {
			t.Errorf("Validate() should only fail on pi binary check after install, got: %v", err)
		}
	}
}

func TestGetAvailableTargets_IncludesPiTarget(t *testing.T) {
	targets := GetAvailableTargets()

	found := false
	for _, target := range targets {
		if target.ID() == "pi" {
			found = true
			break
		}
	}

	if !found {
		t.Error("GetAvailableTargets() should include pi target")
	}
}

func TestPiTarget_Install_ConfigJsonNotModified(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".pi")

	target := &PiTarget{
		configPath: configPath,
	}

	opts := InstallOptions{}
	err := target.Install(opts)

	if err != nil {
		t.Fatalf("Install() failed: %v", err)
	}

	// config.json should NOT have auto-generated header
	filePath := filepath.Join(configPath, "brain-agents", "tdd-dev", "config.json")
	content, err := os.ReadFile(filePath)
	if err != nil {
		t.Fatalf("Failed to read config.json: %v", err)
	}

	contentStr := string(content)
	if strings.Contains(contentStr, "AUTO-GENERATED") {
		t.Error("config.json should not have auto-generated header")
	}

	// Verify it's valid JSON-like content (starts with {)
	trimmed := strings.TrimSpace(contentStr)
	if !strings.HasPrefix(trimmed, "{") {
		t.Errorf("config.json should start with '{', got: %s", trimmed[:20])
	}
}
