export const TASK_SSE_HEARTBEAT_MS = 30_000;

const TASK_SSE_IDLE_TIMEOUT_BUFFER_MS = 30_000;

export const TASK_SSE_SAFE_IDLE_TIMEOUT_SECONDS = Math.ceil(
  (TASK_SSE_HEARTBEAT_MS + TASK_SSE_IDLE_TIMEOUT_BUFFER_MS) / 1000
);
