/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get server health */
        get: operations["health.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List entries */
        get: operations["entries.list"];
        put?: never;
        /** Create an entry */
        post: operations["entries.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get an entry by ID or legacy path */
        get: operations["entries.get"];
        put?: never;
        post?: never;
        /** Delete a confirmed entry */
        delete: operations["entries.delete"];
        options?: never;
        head?: never;
        /** Update an entry */
        patch: operations["entries.update"];
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search visible entries
         * @description Semantic/hybrid strategy may call an embedding provider; not a safe dry-run read.
         */
        post: operations["search.query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** List resolved project tasks */
        get: operations["tasks.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{projectId}/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                taskId: string;
            };
            cookie?: never;
        };
        /** Get a resolved task */
        get: operations["tasks.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move an entry between projects */
        post: operations["entries.move"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/bulk-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update a bounded set of entries */
        post: operations["entries.bulkUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a bounded set of entries */
        post: operations["entries.bulkDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** List section headings */
        get: operations["sections.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}/sections/{title}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                title: string;
            };
            cookie?: never;
        };
        /** Get a section by heading title */
        get: operations["sections.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}/backlinks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get entries linking to this entry */
        get: operations["graph.backlinks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}/outlinks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get entries linked from this entry */
        get: operations["graph.outlinks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get related entries */
        get: operations["graph.related"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List project attachment metadata */
        get: operations["attachments.list"];
        put?: never;
        /** Upload attachment bytes without local path interpretation */
        post: operations["attachments.upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{attachmentID}": {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path: {
                attachmentID: string;
            };
            cookie?: never;
        };
        /** Get project attachment metadata */
        get: operations["attachments.get"];
        put?: never;
        post?: never;
        /** Delete an unreferenced attachment */
        delete: operations["attachments.delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{attachmentID}/content": {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path: {
                attachmentID: string;
            };
            cookie?: never;
        };
        /** Download bounded attachment bytes */
        get: operations["attachments.download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{attachmentID}/text": {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path: {
                attachmentID: string;
            };
            cookie?: never;
        };
        /** Download already-extracted text without invoking extraction */
        get: operations["attachments.text"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{attachmentID}/extract": {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path: {
                attachmentID: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run extraction and persist derived text */
        post: operations["attachments.extract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}/attachments": {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** List entry attachment references */
        get: operations["attachments.forEntry"];
        put?: never;
        /**
         * Attach an existing project attachment to an entry
         * @description attachment.role must be non-empty; metadata DTO omission does not waive service validation.
         */
        post: operations["attachments.attach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}/attachments/{attachmentID}": {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path: {
                id: string;
                attachmentID: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an attachment reference from an entry */
        delete: operations["attachments.detach"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visible goals by project, feature and status */
        get: operations["goals.list"];
        put?: never;
        /** Create a goal automation */
        post: operations["goals.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a goal automation */
        delete: operations["goals.delete"];
        options?: never;
        head?: never;
        /** Update a goal automation */
        patch: operations["goals.update"];
        trace?: never;
    };
    "/goals/{goalId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        /** Read goal-scoped linked-task progress */
        get: operations["goals.progress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        /** Read bounded goal reconcile audit history */
        get: operations["goals.audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile a goal; may submit work or steer a session */
        post: operations["goals.run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reminders */
        get: operations["reminders.list"];
        put?: never;
        /** Create a reminder */
        post: operations["reminders.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reminders/{reminderId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminderId: string;
            };
            cookie?: never;
        };
        /** Get a reminder */
        get: operations["reminders.get"];
        put?: never;
        post?: never;
        /** Delete a reminder */
        delete: operations["reminders.delete"];
        options?: never;
        head?: never;
        /** Update a reminder */
        patch: operations["reminders.update"];
        trace?: never;
    };
    "/reminders/{reminderId}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminderId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge a reminder */
        post: operations["reminders.ack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reminders/{reminderId}/snooze": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminderId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snooze a reminder until a new timestamp */
        post: operations["reminders.snooze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reminders/{reminderId}/fire": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminderId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fire a reminder now; may publish notices or submit work */
        post: operations["reminders.fire"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List attention for the authenticated recipient */
        get: operations["attention.list"];
        put?: never;
        /** Create attention under existing publication policy */
        post: operations["attention.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attention/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get authenticated recipient attention counts */
        get: operations["attention.counts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attention/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get authenticated recipient attention item */
        get: operations["attention.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attention/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark attention read */
        post: operations["attention.read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attention/{id}/unread": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark attention unread */
        post: operations["attention.unread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attention/{id}/snooze": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snooze attention until a timestamp */
        post: operations["attention.snooze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attention/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve attention */
        post: operations["attention.resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attention/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss attention */
        post: operations["attention.dismiss"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhook subscriptions */
        get: operations["webhooks.list"];
        put?: never;
        /** Create webhook subscription for future outbound delivery */
        post: operations["webhooks.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Read webhook subscription */
        get: operations["webhooks.get"];
        put?: never;
        post?: never;
        /** Delete webhook subscription */
        delete: operations["webhooks.delete"];
        options?: never;
        head?: never;
        /** Update webhook subscription */
        patch: operations["webhooks.update"];
        trace?: never;
    };
    "/webhooks/{id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** List webhook deliveries */
        get: operations["webhooks.deliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a synthetic event to the webhook destination */
        post: operations["webhooks.test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessResponse: {
            success: boolean;
        };
        ListWebhooksResponse: {
            webhooks: components["schemas"]["WebhookResponse"][];
        };
        ListWebhookDeliveriesResponse: {
            deliveries: components["schemas"]["WebhookDeliveryResponse"][];
        };
        DeletionResponse: {
            deleted: boolean;
        };
        SnoozeReminderRequest: {
            /** Format: date-time */
            remind_at: string;
        };
        SnoozeAttentionRequest: {
            /** Format: date-time */
            snoozed_until: string;
        };
        AttentionListResponse: {
            attention: components["schemas"]["Attention"][];
            count: number;
        };
        ListGoalsResponse: {
            goals: components["schemas"]["GoalSummary"][] | null;
            count: number;
        };
        DeleteGoalResponse: {
            success: boolean;
            goal_id: string;
        };
        GoalAuditResponse: {
            audit: components["schemas"]["GoalReconcileAudit"][] | null;
            count: number;
        };
        /** @description Existing REST error envelope; SDKs adapt HTTP status to a machine code and preserve field details without changing the server wire format. */
        LegacyErrorResponse: {
            error: string;
            message: string;
            details?: components["schemas"]["ValidationDetail"][];
            /** @description Optional future-compatible machine code; legacy endpoints usually omit it. */
            code?: string;
            /** @description Optional fallback when X-Request-ID is absent. */
            request_id?: string;
        };
        ValidationDetail: {
            field: string;
            message: string;
        };
        AttachmentDeletionResponse: {
            deleted: boolean;
        };
        HealthResponse: {
            status: string;
            /** Format: date-time */
            timestamp: string;
            embedding: components["schemas"]["EmbeddingHealthStatus"];
        };
        EmbeddingHealthStatus: {
            enabled: boolean;
            status: string;
            provider?: string;
            model?: string;
        };
        AttachmentDerived: {
            content_type?: string;
            created?: string;
            id: string;
            kind: string;
            /** Format: int64 */
            size?: number;
            storage_key?: string;
        };
        AttachmentDerivedText: {
            content_type?: string;
            created?: string;
            error?: string;
            id?: string;
            kind?: string;
            metadata?: {
                [key: string]: string;
            } | null;
            modified?: string;
            status: string;
            text?: string;
        };
        AttachmentReference: {
            caption?: string;
            content_type?: string;
            derived?: components["schemas"]["AttachmentDerived"][] | null;
            derived_text?: components["schemas"]["AttachmentDerivedText"] | null;
            download_url?: string;
            filename?: string;
            id: string;
            metadata?: {
                [key: string]: string;
            } | null;
            role?: string;
            sha256?: string;
            /** Format: int64 */
            size?: number;
            text_url?: string;
        };
        AutomationAction: {
            agent?: string;
            command?: string;
            complete_on_idle?: boolean | null;
            direct_prompt?: string;
            execution_mode?: string;
            executor?: string;
            model?: string;
            requires_capability?: string;
            session_mode?: string;
            set_status?: string;
            target_workdir?: string;
            timeout?: string;
            type: string;
        };
        AutomationRetry: {
            backoff?: string;
            delay?: string;
            max_attempts?: number;
        };
        BacklinkEntry: {
            id: string;
            path: string;
            title: string;
            type: string;
        };
        BrainEntry: {
            access_count?: number;
            action?: components["schemas"]["AutomationAction"] | null;
            agent?: string;
            attachments?: components["schemas"]["AttachmentReference"][] | null;
            attempt_count?: number;
            automation_run_id?: string;
            backlinks?: components["schemas"]["BacklinkEntry"][] | null;
            checkout_mode?: string;
            complete_on_idle?: boolean | null;
            completed_at?: string;
            content: string;
            created?: string;
            delivery_mode?: string;
            delivery_verification?: components["schemas"]["DeliveryVerification"] | null;
            depends_on?: string[] | null;
            direct_prompt?: string;
            embedding_status?: string;
            execution_mode?: string;
            executor?: string;
            expires_at?: string;
            extensions?: string[] | null;
            feature_depends_on?: string[] | null;
            feature_expires_at?: string;
            feature_id?: string;
            feature_priority?: string;
            feature_run_once_at?: string;
            feature_schedule?: string;
            feature_starts_at?: string;
            feature_timezone?: string;
            generated?: boolean | null;
            generated_by?: string;
            generated_key?: string;
            generated_kind?: string;
            git_branch?: string;
            git_remote?: string;
            goal?: components["schemas"]["GoalConfig"] | null;
            id: string;
            last_failed_at?: string;
            last_verified?: string;
            machine_affinity?: string;
            max_runs?: number | null;
            merge_policy?: string;
            merge_strategy?: string;
            merge_target_branch?: string;
            model?: string;
            modified?: string;
            next_run?: string;
            open_pr_before_merge?: boolean | null;
            origin_client_id?: string;
            origin_machine_id?: string;
            origin_path?: string;
            parent_id?: string;
            path: string;
            priority?: string;
            project_id?: string;
            reminder?: components["schemas"]["ReminderConfig"] | null;
            remote_branch_policy?: string;
            requires_capability?: string[] | null;
            resume_executor_override?: string;
            resume_injected_context?: string;
            resume_mode?: string;
            resume_prefer_same_session?: boolean;
            resume_requested?: boolean;
            resume_requested_at?: string;
            retry?: components["schemas"]["AutomationRetry"] | null;
            revision?: string;
            run_finalizations?: {
                [key: string]: components["schemas"]["RunFinalization"];
            } | null;
            run_once_at?: string;
            runs?: components["schemas"]["CronRun"][] | null;
            schedule?: string;
            schedule_enabled?: boolean | null;
            session_mode?: string;
            sessions?: {
                [key: string]: components["schemas"]["SessionInfo"];
            } | null;
            starts_at?: string;
            status: string;
            tags: string[] | null;
            target_workdir?: string;
            timezone?: string;
            title: string;
            trigger?: components["schemas"]["TriggerConfig"] | null;
            type: string;
            user_original_request?: string;
            workdir?: string;
        };
        CreateEntryRequest: {
            action?: components["schemas"]["AutomationAction"] | null;
            agent?: string;
            assignment_intent?: string;
            attachments?: components["schemas"]["AttachmentReference"][] | null;
            automation_run_id?: string;
            checkout_mode?: string;
            complete_on_idle?: boolean | null;
            content: string;
            delivery_mode?: string;
            depends_on?: string[] | null;
            direct_prompt?: string;
            execution_mode?: string;
            executor?: string;
            expires_at?: string;
            extensions?: string[] | null;
            feature_depends_on?: string[] | null;
            feature_expires_at?: string;
            feature_id?: string;
            feature_priority?: string;
            feature_run_once_at?: string;
            feature_schedule?: string;
            feature_starts_at?: string;
            feature_timezone?: string;
            generated?: boolean | null;
            generated_by?: string;
            generated_key?: string;
            generated_kind?: string;
            git_branch?: string;
            git_remote?: string;
            global?: boolean | null;
            goal?: components["schemas"]["GoalConfig"] | null;
            machine_affinity?: string;
            max_runs?: number | null;
            merge_policy?: string;
            merge_strategy?: string;
            merge_target_branch?: string;
            model?: string;
            next_run?: string;
            open_pr_before_merge?: boolean | null;
            origin_client_id?: string;
            origin_machine_id?: string;
            origin_path?: string;
            priority?: string;
            project?: string;
            relatedEntries?: string[] | null;
            reminder?: components["schemas"]["ReminderConfig"] | null;
            remote_branch_policy?: string;
            requires_capability?: string[] | null;
            retry?: components["schemas"]["AutomationRetry"] | null;
            run_finalizations?: {
                [key: string]: components["schemas"]["RunFinalization"];
            } | null;
            run_once_at?: string;
            runner_id?: string;
            runs?: components["schemas"]["CronRun"][] | null;
            schedule?: string;
            schedule_enabled?: boolean | null;
            session_mode?: string;
            starts_at?: string;
            status?: string;
            tags?: string[] | null;
            target_workdir?: string;
            timezone?: string;
            title: string;
            trigger?: components["schemas"]["TriggerConfig"] | null;
            type: string;
            user_original_request?: string;
            workdir?: string;
        };
        CreateEntryResponse: {
            id: string;
            link: string;
            path: string;
            status: string;
            tags?: string[] | null;
            title: string;
            type: string;
        };
        CronRun: {
            completed?: string;
            duration?: number | null;
            failed_task?: string;
            run_id: string;
            skip_reason?: string;
            started: string;
            status: string;
            tasks?: number | null;
        };
        DeliveryEvidence: {
            checks: {
                [key: string]: string;
            } | null;
            head: string;
            integration_artifact?: string;
            integration_passed: boolean;
            integration_reference?: string;
            integration_verifier?: string;
            merge_commit: string;
            merged: boolean;
            review_accepted: boolean;
            source: string;
            target: string;
            /** Format: date-time */
            verified_at: string;
            verifier: string;
        };
        DeliveryVerification: {
            evidence?: components["schemas"]["DeliveryEvidence"] | null;
            head: string;
            pull_request: number;
            repository: string;
            required: string;
            required_checks: string[] | null;
            revision: number;
            target: string;
            verification_error?: string;
        };
        DispatchLease: {
            /** Format: int64 */
            acked_at?: number;
            assigned_machine_id: string;
            assigned_runner_id: string;
            /** Format: int64 */
            expires_at: number;
            id?: string;
            last_error?: string;
            leaseId: string;
            project_id: string;
            /** Format: int64 */
            pushed_at: number;
            /** Format: int64 */
            rejected_at?: number;
            state: string;
            task_id: string;
        };
        GoalConfig: {
            blocked_statuses?: string[] | null;
            complete_statuses?: string[] | null;
            criteria?: string;
            id: string;
            steering?: components["schemas"]["GoalSteering"] | null;
            task_id?: string;
            trigger_source?: string;
            validation?: string;
            workdir?: string;
        };
        GoalSteering: {
            cooldown_minutes?: number;
            enabled?: boolean | null;
        };
        ListEntriesResponse: {
            entries: components["schemas"]["BrainEntry"][] | null;
            limit: number;
            offset: number;
            total: number;
            truncated?: boolean;
        };
        PlacementReason: {
            /** Format: int64 */
            created_at: number;
            decision: string;
            /** Format: int64 */
            id?: number;
            machine_id?: string;
            missing_labels?: string;
            project_id: string;
            reason?: string;
            required_labels?: string;
            runner_id?: string;
            runner_labels?: string;
            task_id: string;
        };
        ReminderConfig: {
            action?: string;
            agent?: string;
            execution_mode?: string;
            executor?: string;
            fire_count?: number;
            fired_at?: string;
            generated_task_id?: string;
            id: string;
            model?: string;
            prompt?: string;
            remind_at?: string;
            repeat?: string;
            repeat_until?: string;
            target_workdir?: string;
            timezone?: string;
        };
        ResolvedTask: {
            abandon_reason?: string;
            action?: components["schemas"]["AutomationAction"] | null;
            agent: string;
            assigned_runner_id?: string;
            assignment_scope?: string;
            attempt_count?: number;
            blocked_by: string[] | null;
            blocked_by_features?: string[] | null;
            blocked_by_reason?: string;
            checkout_mode?: string;
            classification: string;
            complete_on_idle?: boolean | null;
            completed_at?: string;
            content?: string;
            created: string;
            delivery_mode?: string;
            delivery_verification?: components["schemas"]["DeliveryVerification"] | null;
            depends_on: string[] | null;
            direct_prompt: string;
            dispatch_lease?: components["schemas"]["DispatchLease"] | null;
            env?: {
                [key: string]: string;
            } | null;
            execution_mode?: string;
            executor?: string;
            expires_at?: string;
            extensions?: string[] | null;
            feature_depends_on?: string[] | null;
            feature_expires_at?: string;
            feature_id?: string;
            feature_priority?: string;
            feature_run_once_at?: string;
            feature_schedule?: string;
            feature_starts_at?: string;
            feature_timezone?: string;
            generated?: boolean | null;
            generated_by?: string;
            generated_key?: string;
            generated_kind?: string;
            git_branch: string;
            git_remote: string;
            id: string;
            in_cycle: boolean;
            is_abandoned?: boolean;
            last_failed_at?: string;
            last_placement_reason?: components["schemas"]["PlacementReason"] | null;
            machine_affinity?: string;
            max_runs?: number | null;
            merge_policy?: string;
            merge_strategy?: string;
            merge_target_branch?: string;
            model: string;
            modified?: string;
            next_run?: string;
            open_pr_before_merge?: boolean | null;
            origin_client_id?: string;
            origin_machine_id?: string;
            origin_path?: string;
            parent_id?: string;
            path: string;
            placement_reasons?: components["schemas"]["PlacementReason"][] | null;
            priority: string;
            projectId?: string;
            remote_branch_policy?: string;
            requires_capability?: string[] | null;
            resolved_deps: string[] | null;
            resolved_workdir: string;
            resume_executor_override?: string;
            resume_injected_context?: string;
            resume_mode?: string;
            resume_prefer_same_session?: boolean;
            resume_requested?: boolean;
            resume_requested_at?: string;
            retry?: components["schemas"]["AutomationRetry"] | null;
            run_once_at?: string;
            runs?: components["schemas"]["CronRun"][] | null;
            schedule?: string;
            schedule_enabled?: boolean | null;
            sessions?: {
                [key: string]: components["schemas"]["SessionInfo"];
            } | null;
            starts_at?: string;
            status: string;
            tags?: string[] | null;
            target_workdir?: string;
            timezone?: string;
            title: string;
            trigger?: components["schemas"]["TriggerConfig"] | null;
            undispatchable_reason?: string;
            unresolved_deps: string[] | null;
            unresolved_feature_deps?: string[] | null;
            user_original_request?: string;
            waiting_on: string[] | null;
            waiting_on_features?: string[] | null;
            workdir: string;
        };
        RunFinalization: {
            finalized_at: string;
            session_id?: string;
            status: string;
        };
        SearchRequest: {
            feature_id?: string;
            global?: boolean | null;
            include?: string[] | null;
            limit?: number | null;
            priority?: string;
            project?: string;
            projects?: string[] | null;
            query: string;
            status?: string;
            strategy?: string;
            tags?: string[] | null;
            type?: string;
        };
        SearchResponse: {
            results: components["schemas"]["SearchResult"][] | null;
            total: number;
        };
        SearchResult: {
            attachments?: components["schemas"]["AttachmentReference"][] | null;
            id: string;
            match_source?: string;
            path: string;
            snippet: string;
            status: string;
            title: string;
            type: string;
        };
        SessionInfo: {
            cron_id?: string;
            hostname?: string;
            machine_id?: string;
            parent_id?: string;
            run_id?: string;
            runner_id?: string;
            timestamp: string;
            workdir?: string;
        };
        TaskListResponse: {
            count: number;
            cycles?: (string[] | null)[] | null;
            stats?: components["schemas"]["TaskStats"] | null;
            tasks: components["schemas"]["ResolvedTask"][] | null;
        };
        TaskStats: {
            blocked: number;
            not_pending: number;
            ready: number;
            status_blocked: number;
            total: number;
            waiting: number;
        };
        TriggerConfig: {
            cooldown?: string;
            event?: string;
            events?: string[] | null;
            filter?: {
                [key: string]: string;
            } | null;
            ignore_automation_events?: boolean | null;
            max_concurrent?: number;
            once_per?: string;
            schedule?: string;
            timezone?: string;
            type?: string;
            webhook?: string;
        };
        UpdateEntryRequest: {
            action?: components["schemas"]["AutomationAction"] | null;
            agent?: string | null;
            append?: string | null;
            attachments?: (components["schemas"]["AttachmentReference"][] | null) | null;
            automation_run_id?: string | null;
            checkout_mode?: string | null;
            complete_on_idle?: boolean | null;
            content?: string | null;
            delivery_mode?: string | null;
            depends_on?: (string[] | null) | null;
            direct_prompt?: string | null;
            execution_mode?: string | null;
            executor?: string | null;
            expected_revision?: string;
            expires_at?: string | null;
            extensions?: (string[] | null) | null;
            feature_depends_on?: (string[] | null) | null;
            feature_expires_at?: string | null;
            feature_id?: string | null;
            feature_priority?: string | null;
            feature_run_once_at?: string | null;
            feature_schedule?: string | null;
            feature_starts_at?: string | null;
            feature_timezone?: string | null;
            generated?: boolean | null;
            generated_by?: string | null;
            generated_key?: string | null;
            generated_kind?: string | null;
            git_branch?: string | null;
            git_remote?: string | null;
            goal?: components["schemas"]["GoalConfig"] | null;
            machine_affinity?: string | null;
            max_runs?: number | null;
            merge_policy?: string | null;
            merge_strategy?: string | null;
            merge_target_branch?: string | null;
            model?: string | null;
            next_run?: string | null;
            note?: string | null;
            open_pr_before_merge?: boolean | null;
            origin_client_id?: string | null;
            origin_machine_id?: string | null;
            origin_path?: string | null;
            priority?: string | null;
            reminder?: components["schemas"]["ReminderConfig"] | null;
            remote_branch_policy?: string | null;
            retry?: components["schemas"]["AutomationRetry"] | null;
            run_finalizations?: {
                [key: string]: components["schemas"]["RunFinalization"];
            } | null;
            run_once_at?: string | null;
            runs?: components["schemas"]["CronRun"][] | null;
            schedule?: string | null;
            schedule_enabled?: boolean | null;
            sessions?: {
                [key: string]: components["schemas"]["SessionInfo"];
            } | null;
            starts_at?: string | null;
            status?: string | null;
            tags?: string[] | null;
            target_workdir?: string | null;
            timezone?: string | null;
            title?: string | null;
            trigger?: components["schemas"]["TriggerConfig"] | null;
            user_original_request?: string | null;
            workdir?: string | null;
        };
        BulkDeleteRequest: {
            dry_run?: boolean;
            filter?: components["schemas"]["BulkUpdateFilter"] | null;
            force?: boolean;
            limit?: number;
            paths?: string[] | null;
        };
        BulkDeleteResponse: {
            deleted: number;
            dry_run: boolean;
            failed: number;
            matched_total?: number;
            results: components["schemas"]["BulkUpdateResult"][] | null;
            total: number;
            truncated?: boolean;
        };
        BulkUpdateEntry: {
            path: string;
            updates: components["schemas"]["UpdateEntryRequest"];
        };
        BulkUpdateFilter: {
            agent?: string | null;
            execution_mode?: string | null;
            executor?: string | null;
            feature_id?: string | null;
            generated_by?: string | null;
            generated_key?: string | null;
            priority?: string | null;
            project?: string | null;
            status?: string | null;
            tags?: string[] | null;
            type?: string | null;
        };
        BulkUpdateRequest: {
            dry_run?: boolean;
            entries?: components["schemas"]["BulkUpdateEntry"][] | null;
            filter?: components["schemas"]["BulkUpdateFilter"] | null;
            force?: boolean;
            limit?: number;
            updates?: components["schemas"]["UpdateEntryRequest"] | null;
        };
        BulkUpdateResponse: {
            dry_run: boolean;
            failed: number;
            matched_total?: number;
            results: components["schemas"]["BulkUpdateResult"][] | null;
            total: number;
            truncated?: boolean;
            updated: number;
        };
        BulkUpdateResult: {
            error?: string;
            id: string;
            path: string;
            status: string;
            title: string;
        };
        MoveEntryRequest: {
            project: string;
        };
        MoveResult: {
            from: string;
            id: string;
            newPath: string;
            oldPath: string;
            project: string;
            success: boolean;
            title: string;
            to: string;
        };
        SectionContentResponse: {
            content: string;
            includeSubsections: boolean;
            path: string;
            title: string;
        };
        SectionHeader: {
            level: number;
            title: string;
        };
        SectionsResponse: {
            path: string;
            sections: components["schemas"]["SectionHeader"][] | null;
        };
        AttachEntryAttachmentRequest: {
            attachment: components["schemas"]["AttachmentReference"];
        };
        AttachEntryAttachmentResponse: {
            attachments: components["schemas"]["AttachmentReference"][] | null;
            entry_id: string;
            path: string;
        };
        Attachment: {
            content_type: string;
            created?: string;
            derived?: components["schemas"]["AttachmentDerived"][] | null;
            filename: string;
            id: string;
            metadata?: {
                [key: string]: string;
            } | null;
            modified?: string;
            sha256?: string;
            /** Format: int64 */
            size: number;
            storage_key?: string;
        };
        AttachmentExtractionRequest: {
            attachment_id: string;
            content_type: string;
            entry_id?: string;
            filename?: string;
            metadata?: {
                [key: string]: string;
            } | null;
            project_id?: string;
            /** Format: int64 */
            size?: number;
        };
        AttachmentExtractionResult: {
            attachment: components["schemas"]["Attachment"];
            derived_text: components["schemas"]["AttachmentDerivedText"];
            linked_entries?: components["schemas"]["AttachmentLinkedEntry"][] | null;
        };
        AttachmentLinkedEntry: {
            path: string;
            role?: string;
        };
        CreateAttachmentResponse: {
            attachment: components["schemas"]["Attachment"];
        };
        ListAttachmentsResponse: {
            attachments: components["schemas"]["Attachment"][] | null;
            total: number;
        };
        CreateGoalRequest: {
            action: components["schemas"]["AutomationAction"];
            config: components["schemas"]["GoalConfig"];
            content?: string;
            feature_id?: string;
            project: string;
            title: string;
        };
        GoalProgressResponse: {
            blocked: number;
            completed: number;
            entry_id: string;
            feature_id?: string;
            feature_status?: string;
            goal_id: string;
            goal_status: string;
            in_progress: number;
            pending: number;
            project?: string;
            task_id?: string;
            tasks: components["schemas"]["LinkedTaskSnapshot"][] | null;
            total: number;
        };
        GoalReconcileAudit: {
            decision: string;
            event_id?: string;
            feature_id?: string;
            generated_task_id?: string;
            goal_id: string;
            linked_tasks: components["schemas"]["LinkedTaskSnapshot"][] | null;
            project?: string;
            reason: string;
            sessions_skipped?: number;
            sessions_steered?: number;
            timestamp: string;
            triggering_event: string;
        };
        GoalSummary: {
            action?: components["schemas"]["AutomationAction"] | null;
            config?: components["schemas"]["GoalConfig"] | null;
            entry_id: string;
            feature_id?: string;
            goal_id: string;
            project?: string;
            status: string;
            title: string;
            trigger?: components["schemas"]["TriggerConfig"] | null;
        };
        LinkedTaskSnapshot: {
            id: string;
            status: string;
            title: string;
        };
        UpdateGoalRequest: {
            action?: components["schemas"]["AutomationAction"] | null;
            blocked_statuses?: (string[] | null) | null;
            complete_statuses?: (string[] | null) | null;
            content?: string | null;
            criteria?: string | null;
            feature_id?: string | null;
            status?: string | null;
            steering?: components["schemas"]["GoalSteering"] | null;
            task_id?: string | null;
            title?: string | null;
            trigger_source?: string | null;
            validation?: string | null;
            workdir?: string | null;
        };
        Attention: {
            actions?: components["schemas"]["AttentionAction"][] | null;
            body?: string;
            created_at: string;
            dedup_key?: string;
            feature_id?: string;
            id: string;
            instance_id?: string;
            kind: string;
            project?: string;
            read_at?: string;
            recipient: string;
            resolved_at?: string;
            revision: number;
            runner_id?: string;
            session_id?: string;
            severity: string;
            snoozed_until?: string;
            source_id?: string;
            source_type?: string;
            state: string;
            task_id?: string;
            title: string;
            updated_at: string;
        };
        AttentionAction: {
            kind: string;
            label: string;
            params?: {
                [key: string]: string;
            } | null;
        };
        AttentionCounts: {
            critical: number;
            total: number;
            unread: number;
        };
        CreateAttentionRequest: {
            actions?: components["schemas"]["AttentionAction"][] | null;
            body?: string;
            dedup_key?: string;
            feature_id?: string;
            instance_id?: string;
            kind: string;
            project?: string;
            recipient?: string;
            runner_id?: string;
            session_id?: string;
            severity?: string;
            source_id?: string;
            source_type?: string;
            task_id?: string;
            title: string;
        };
        CreateReminderRequest: {
            config: components["schemas"]["ReminderConfig"];
            content?: string;
            feature_id?: string;
            global?: boolean | null;
            project?: string;
            tags?: string[] | null;
            title: string;
        };
        ReminderListResponse: {
            count: number;
            reminders: components["schemas"]["ReminderSummary"][] | null;
        };
        ReminderSummary: {
            action: string;
            entry_id: string;
            feature_id?: string;
            fire_count?: number;
            fired_at?: string;
            generated_task_id?: string;
            /** Format: int64 */
            late_by_seconds?: number;
            path?: string;
            project?: string;
            prompt?: string;
            remind_at?: string;
            reminder_id: string;
            repeat?: string;
            repeat_until?: string;
            state: string;
            status: string;
            timezone?: string;
            title: string;
        };
        UpdateReminderRequest: {
            action?: string | null;
            agent?: string | null;
            content?: string | null;
            execution_mode?: string | null;
            executor?: string | null;
            model?: string | null;
            prompt?: string | null;
            remind_at?: string | null;
            repeat?: string | null;
            repeat_until?: string | null;
            status?: string | null;
            target_workdir?: string | null;
            timezone?: string | null;
            title?: string | null;
        };
        CreateWebhookRequest: {
            enabled?: boolean | null;
            events: string[] | null;
            filter?: {
                [key: string]: string;
            } | null;
            name: string;
            secret?: string;
            url: string;
        };
        UpdateWebhookRequest: {
            enabled?: boolean | null;
            events?: string[] | null;
            filter?: {
                [key: string]: string;
            } | null;
            name?: string | null;
            secret?: string | null;
            url?: string | null;
        };
        WebhookDeliveryResponse: {
            created_at: string;
            error?: string;
            event_type: string;
            id: string;
            latency_ms?: number | null;
            status_code?: number | null;
            success: boolean;
            webhook_id: string;
        };
        WebhookResponse: {
            created_at: string;
            enabled: boolean;
            events: string[] | null;
            filter?: {
                [key: string]: string;
            } | null;
            id: string;
            name: string;
            updated_at: string;
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "health.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server health (not script availability) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    "entries.list": {
        parameters: {
            query?: {
                project?: string;
                type?: string;
                status?: string;
                tags?: string;
                feature_id?: string;
                limit?: number;
                offset?: number;
                global?: boolean;
                sortBy?: string;
                sortOrder?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of entries; truncated is not end-of-pagination */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEntriesResponse"];
                };
            };
        };
    };
    "entries.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntryRequest"];
            };
        };
        responses: {
            /** @description Persisted entry */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateEntryResponse"];
                };
            };
            /** @description Legacy REST error, normalized by the SDK transport */
            default: {
                headers: {
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyErrorResponse"];
                };
            };
        };
    };
    "entries.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry, including current revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainEntry"];
                };
            };
        };
    };
    "entries.delete": {
        parameters: {
            query: {
                confirm: true;
                force?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry deleted; no response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "entries.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEntryRequest"];
            };
        };
        responses: {
            /** @description Updated entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainEntry"];
                };
            };
        };
    };
    "search.query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Matching entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    "tasks.list": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resolved tasks and dependencies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
        };
    };
    "tasks.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resolved task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedTask"];
                };
            };
        };
    };
    "entries.move": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveEntryRequest"];
            };
        };
        responses: {
            /** @description Move result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveResult"];
                };
            };
        };
    };
    "entries.bulkUpdate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUpdateRequest"];
            };
        };
        responses: {
            /** @description Per-entry outcomes; inspect failed and truncated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkUpdateResponse"];
                };
            };
        };
    };
    "entries.bulkDelete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDeleteRequest"];
            };
        };
        responses: {
            /** @description Per-entry outcomes; inspect failed and truncated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDeleteResponse"];
                };
            };
        };
    };
    "sections.list": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Section headings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionsResponse"];
                };
            };
        };
    };
    "sections.get": {
        parameters: {
            query?: {
                includeSubsections?: boolean;
            };
            header?: never;
            path: {
                id: string;
                title: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Section content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionContentResponse"];
                };
            };
        };
    };
    "graph.backlinks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry array */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainEntry"][];
                };
            };
        };
    };
    "graph.outlinks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry array */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainEntry"][];
                };
            };
        };
    };
    "graph.related": {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry array */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainEntry"][];
                };
            };
        };
    };
    "attachments.list": {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachment metadata list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAttachmentsResponse"];
                };
            };
        };
    };
    "attachments.upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    project_id: string;
                    /** @description JSON-encoded object with string values */
                    metadata?: string;
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Stored attachment metadata */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAttachmentResponse"];
                };
            };
        };
    };
    "attachments.get": {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path: {
                attachmentID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachment metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
        };
    };
    "attachments.delete": {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path: {
                attachmentID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentDeletionResponse"];
                };
            };
        };
    };
    "attachments.download": {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path: {
                attachmentID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw content; actual media type follows stored metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    "attachments.text": {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path: {
                attachmentID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored derived text */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    "attachments.extract": {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path: {
                attachmentID: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AttachmentExtractionRequest"];
            };
        };
        responses: {
            /** @description Derived text and linked-entry outcomes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentExtractionResult"];
                };
            };
        };
    };
    "attachments.forEntry": {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry references */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachEntryAttachmentResponse"];
                };
            };
        };
    };
    "attachments.attach": {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachEntryAttachmentRequest"];
            };
        };
        responses: {
            /** @description Updated entry references */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachEntryAttachmentResponse"];
                };
            };
        };
    };
    "attachments.detach": {
        parameters: {
            query: {
                project_id: string;
                role: string;
            };
            header?: never;
            path: {
                id: string;
                attachmentID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated entry references */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachEntryAttachmentResponse"];
                };
            };
        };
    };
    "goals.list": {
        parameters: {
            query?: {
                project?: string;
                feature_id?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Goal summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListGoalsResponse"];
                };
            };
        };
    };
    "goals.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoalRequest"];
            };
        };
        responses: {
            /** @description Created goal */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalSummary"];
                };
            };
        };
    };
    "goals.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Goal deletion result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteGoalResponse"];
                };
            };
        };
    };
    "goals.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGoalRequest"];
            };
        };
        responses: {
            /** @description Updated goal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalSummary"];
                };
            };
        };
    };
    "goals.progress": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Goal progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalProgressResponse"];
                };
            };
        };
    };
    "goals.audit": {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Goal audit history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalAuditResponse"];
                };
            };
        };
    };
    "goals.run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reconcile decision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalReconcileAudit"];
                };
            };
        };
    };
    "reminders.list": {
        parameters: {
            query?: {
                project?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reminder summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderListResponse"];
                };
            };
        };
    };
    "reminders.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReminderRequest"];
            };
        };
        responses: {
            /** @description Created reminder */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderSummary"];
                };
            };
        };
    };
    "reminders.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reminder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderSummary"];
                };
            };
        };
    };
    "reminders.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion outcome */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionResponse"];
                };
            };
        };
    };
    "reminders.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReminderRequest"];
            };
        };
        responses: {
            /** @description Updated reminder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderSummary"];
                };
            };
        };
    };
    "reminders.ack": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reminder state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderSummary"];
                };
            };
        };
    };
    "reminders.snooze": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnoozeReminderRequest"];
            };
        };
        responses: {
            /** @description Reminder state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderSummary"];
                };
            };
        };
    };
    "reminders.fire": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reminder state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderSummary"];
                };
            };
        };
    };
    "attention.list": {
        parameters: {
            query?: {
                state?: string;
                project?: string;
                kind?: string;
                severity?: string;
                source_type?: string;
                include_snoozed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attention items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttentionListResponse"];
                };
            };
        };
    };
    "attention.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAttentionRequest"];
            };
        };
        responses: {
            /** @description Created attention */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attention"];
                };
            };
        };
    };
    "attention.counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttentionCounts"];
                };
            };
        };
    };
    "attention.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attention item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attention"];
                };
            };
        };
    };
    "attention.read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attention state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attention"];
                };
            };
        };
    };
    "attention.unread": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attention state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attention"];
                };
            };
        };
    };
    "attention.snooze": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnoozeAttentionRequest"];
            };
        };
        responses: {
            /** @description Attention state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attention"];
                };
            };
        };
    };
    "attention.resolve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attention state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attention"];
                };
            };
        };
    };
    "attention.dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attention state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attention"];
                };
            };
        };
    };
    "webhooks.list": {
        parameters: {
            query?: {
                enabled?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhooks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWebhooksResponse"];
                };
            };
        };
    };
    "webhooks.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebhookRequest"];
            };
        };
        responses: {
            /** @description Created webhook */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
        };
    };
    "webhooks.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
        };
    };
    "webhooks.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    "webhooks.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWebhookRequest"];
            };
        };
        responses: {
            /** @description Updated webhook */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
        };
    };
    "webhooks.deliveries": {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delivery history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWebhookDeliveriesResponse"];
                };
            };
        };
    };
    "webhooks.test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delivery result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookDeliveryResponse"];
                };
            };
        };
    };
}
