/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get server health */
        get: operations["health.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List entries */
        get: operations["entries.list"];
        put?: never;
        /** Create an entry */
        post: operations["entries.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get an entry by ID or legacy path */
        get: operations["entries.get"];
        put?: never;
        post?: never;
        /** Delete a confirmed entry */
        delete: operations["entries.delete"];
        options?: never;
        head?: never;
        /** Update an entry */
        patch: operations["entries.update"];
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search visible entries
         * @description Semantic/hybrid strategy may call an embedding provider; not a safe dry-run read.
         */
        post: operations["search.query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** List resolved project tasks */
        get: operations["tasks.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{projectId}/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                taskId: string;
            };
            cookie?: never;
        };
        /** Get a resolved task */
        get: operations["tasks.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            status: string;
            /** Format: date-time */
            timestamp: string;
            embedding: components["schemas"]["EmbeddingHealthStatus"];
        };
        EmbeddingHealthStatus: {
            enabled: boolean;
            status: string;
            provider?: string;
            model?: string;
        };
        AttachmentDerived: {
            content_type?: string;
            created?: string;
            id: string;
            kind: string;
            /** Format: int64 */
            size?: number;
            storage_key?: string;
        };
        AttachmentDerivedText: {
            content_type?: string;
            created?: string;
            error?: string;
            id?: string;
            kind?: string;
            metadata?: {
                [key: string]: string;
            } | null;
            modified?: string;
            status: string;
            text?: string;
        };
        AttachmentReference: {
            caption?: string;
            content_type?: string;
            derived?: components["schemas"]["AttachmentDerived"][] | null;
            derived_text?: components["schemas"]["AttachmentDerivedText"] | null;
            download_url?: string;
            filename?: string;
            id: string;
            metadata?: {
                [key: string]: string;
            } | null;
            role?: string;
            sha256?: string;
            /** Format: int64 */
            size?: number;
            text_url?: string;
        };
        AutomationAction: {
            agent?: string;
            command?: string;
            complete_on_idle?: boolean | null;
            direct_prompt?: string;
            execution_mode?: string;
            executor?: string;
            model?: string;
            requires_capability?: string;
            session_mode?: string;
            set_status?: string;
            target_workdir?: string;
            timeout?: string;
            type: string;
        };
        AutomationRetry: {
            backoff?: string;
            delay?: string;
            max_attempts?: number;
        };
        BacklinkEntry: {
            id: string;
            path: string;
            title: string;
            type: string;
        };
        BrainEntry: {
            access_count?: number;
            action?: components["schemas"]["AutomationAction"] | null;
            agent?: string;
            attachments?: components["schemas"]["AttachmentReference"][] | null;
            attempt_count?: number;
            automation_run_id?: string;
            backlinks?: components["schemas"]["BacklinkEntry"][] | null;
            checkout_mode?: string;
            complete_on_idle?: boolean | null;
            completed_at?: string;
            content: string;
            created?: string;
            delivery_mode?: string;
            delivery_verification?: components["schemas"]["DeliveryVerification"] | null;
            depends_on?: string[] | null;
            direct_prompt?: string;
            embedding_status?: string;
            execution_mode?: string;
            executor?: string;
            expires_at?: string;
            extensions?: string[] | null;
            feature_depends_on?: string[] | null;
            feature_expires_at?: string;
            feature_id?: string;
            feature_priority?: string;
            feature_run_once_at?: string;
            feature_schedule?: string;
            feature_starts_at?: string;
            feature_timezone?: string;
            generated?: boolean | null;
            generated_by?: string;
            generated_key?: string;
            generated_kind?: string;
            git_branch?: string;
            git_remote?: string;
            goal?: components["schemas"]["GoalConfig"] | null;
            id: string;
            last_failed_at?: string;
            last_verified?: string;
            machine_affinity?: string;
            max_runs?: number | null;
            merge_policy?: string;
            merge_strategy?: string;
            merge_target_branch?: string;
            model?: string;
            modified?: string;
            next_run?: string;
            open_pr_before_merge?: boolean | null;
            origin_client_id?: string;
            origin_machine_id?: string;
            origin_path?: string;
            parent_id?: string;
            path: string;
            priority?: string;
            project_id?: string;
            reminder?: components["schemas"]["ReminderConfig"] | null;
            remote_branch_policy?: string;
            requires_capability?: string[] | null;
            resume_executor_override?: string;
            resume_injected_context?: string;
            resume_mode?: string;
            resume_prefer_same_session?: boolean;
            resume_requested?: boolean;
            resume_requested_at?: string;
            retry?: components["schemas"]["AutomationRetry"] | null;
            revision?: string;
            run_finalizations?: {
                [key: string]: components["schemas"]["RunFinalization"];
            } | null;
            run_once_at?: string;
            runs?: components["schemas"]["CronRun"][] | null;
            schedule?: string;
            schedule_enabled?: boolean | null;
            session_mode?: string;
            sessions?: {
                [key: string]: components["schemas"]["SessionInfo"];
            } | null;
            starts_at?: string;
            status: string;
            tags: string[] | null;
            target_workdir?: string;
            timezone?: string;
            title: string;
            trigger?: components["schemas"]["TriggerConfig"] | null;
            type: string;
            user_original_request?: string;
            workdir?: string;
        };
        CreateEntryRequest: {
            action?: components["schemas"]["AutomationAction"] | null;
            agent?: string;
            assignment_intent?: string;
            attachments?: components["schemas"]["AttachmentReference"][] | null;
            automation_run_id?: string;
            checkout_mode?: string;
            complete_on_idle?: boolean | null;
            content: string;
            delivery_mode?: string;
            depends_on?: string[] | null;
            direct_prompt?: string;
            execution_mode?: string;
            executor?: string;
            expires_at?: string;
            extensions?: string[] | null;
            feature_depends_on?: string[] | null;
            feature_expires_at?: string;
            feature_id?: string;
            feature_priority?: string;
            feature_run_once_at?: string;
            feature_schedule?: string;
            feature_starts_at?: string;
            feature_timezone?: string;
            generated?: boolean | null;
            generated_by?: string;
            generated_key?: string;
            generated_kind?: string;
            git_branch?: string;
            git_remote?: string;
            global?: boolean | null;
            goal?: components["schemas"]["GoalConfig"] | null;
            machine_affinity?: string;
            max_runs?: number | null;
            merge_policy?: string;
            merge_strategy?: string;
            merge_target_branch?: string;
            model?: string;
            next_run?: string;
            open_pr_before_merge?: boolean | null;
            origin_client_id?: string;
            origin_machine_id?: string;
            origin_path?: string;
            priority?: string;
            project?: string;
            relatedEntries?: string[] | null;
            reminder?: components["schemas"]["ReminderConfig"] | null;
            remote_branch_policy?: string;
            requires_capability?: string[] | null;
            retry?: components["schemas"]["AutomationRetry"] | null;
            run_finalizations?: {
                [key: string]: components["schemas"]["RunFinalization"];
            } | null;
            run_once_at?: string;
            runner_id?: string;
            runs?: components["schemas"]["CronRun"][] | null;
            schedule?: string;
            schedule_enabled?: boolean | null;
            session_mode?: string;
            starts_at?: string;
            status?: string;
            tags?: string[] | null;
            target_workdir?: string;
            timezone?: string;
            title: string;
            trigger?: components["schemas"]["TriggerConfig"] | null;
            type: string;
            user_original_request?: string;
            workdir?: string;
        };
        CreateEntryResponse: {
            id: string;
            link: string;
            path: string;
            status: string;
            tags?: string[] | null;
            title: string;
            type: string;
        };
        CronRun: {
            completed?: string;
            duration?: number | null;
            failed_task?: string;
            run_id: string;
            skip_reason?: string;
            started: string;
            status: string;
            tasks?: number | null;
        };
        DeliveryEvidence: {
            checks: {
                [key: string]: string;
            } | null;
            head: string;
            integration_artifact?: string;
            integration_passed: boolean;
            integration_reference?: string;
            integration_verifier?: string;
            merge_commit: string;
            merged: boolean;
            review_accepted: boolean;
            source: string;
            target: string;
            /** Format: date-time */
            verified_at: string;
            verifier: string;
        };
        DeliveryVerification: {
            evidence?: components["schemas"]["DeliveryEvidence"] | null;
            head: string;
            pull_request: number;
            repository: string;
            required: string;
            required_checks: string[] | null;
            revision: number;
            target: string;
            verification_error?: string;
        };
        DispatchLease: {
            /** Format: int64 */
            acked_at?: number;
            assigned_machine_id: string;
            assigned_runner_id: string;
            /** Format: int64 */
            expires_at: number;
            id?: string;
            last_error?: string;
            leaseId: string;
            project_id: string;
            /** Format: int64 */
            pushed_at: number;
            /** Format: int64 */
            rejected_at?: number;
            state: string;
            task_id: string;
        };
        GoalConfig: {
            blocked_statuses?: string[] | null;
            complete_statuses?: string[] | null;
            criteria?: string;
            id: string;
            steering?: components["schemas"]["GoalSteering"] | null;
            task_id?: string;
            trigger_source?: string;
            validation?: string;
            workdir?: string;
        };
        GoalSteering: {
            cooldown_minutes?: number;
            enabled?: boolean | null;
        };
        ListEntriesResponse: {
            entries: components["schemas"]["BrainEntry"][] | null;
            limit: number;
            offset: number;
            total: number;
            truncated?: boolean;
        };
        PlacementReason: {
            /** Format: int64 */
            created_at: number;
            decision: string;
            /** Format: int64 */
            id?: number;
            machine_id?: string;
            missing_labels?: string;
            project_id: string;
            reason?: string;
            required_labels?: string;
            runner_id?: string;
            runner_labels?: string;
            task_id: string;
        };
        ReminderConfig: {
            action?: string;
            agent?: string;
            execution_mode?: string;
            executor?: string;
            fire_count?: number;
            fired_at?: string;
            generated_task_id?: string;
            id: string;
            model?: string;
            prompt?: string;
            remind_at?: string;
            repeat?: string;
            repeat_until?: string;
            target_workdir?: string;
            timezone?: string;
        };
        ResolvedTask: {
            abandon_reason?: string;
            action?: components["schemas"]["AutomationAction"] | null;
            agent: string;
            assigned_runner_id?: string;
            assignment_scope?: string;
            attempt_count?: number;
            blocked_by: string[] | null;
            blocked_by_features?: string[] | null;
            blocked_by_reason?: string;
            checkout_mode?: string;
            classification: string;
            complete_on_idle?: boolean | null;
            completed_at?: string;
            content?: string;
            created: string;
            delivery_mode?: string;
            delivery_verification?: components["schemas"]["DeliveryVerification"] | null;
            depends_on: string[] | null;
            direct_prompt: string;
            dispatch_lease?: components["schemas"]["DispatchLease"] | null;
            env?: {
                [key: string]: string;
            } | null;
            execution_mode?: string;
            executor?: string;
            expires_at?: string;
            extensions?: string[] | null;
            feature_depends_on?: string[] | null;
            feature_expires_at?: string;
            feature_id?: string;
            feature_priority?: string;
            feature_run_once_at?: string;
            feature_schedule?: string;
            feature_starts_at?: string;
            feature_timezone?: string;
            generated?: boolean | null;
            generated_by?: string;
            generated_key?: string;
            generated_kind?: string;
            git_branch: string;
            git_remote: string;
            id: string;
            in_cycle: boolean;
            is_abandoned?: boolean;
            last_failed_at?: string;
            last_placement_reason?: components["schemas"]["PlacementReason"] | null;
            machine_affinity?: string;
            max_runs?: number | null;
            merge_policy?: string;
            merge_strategy?: string;
            merge_target_branch?: string;
            model: string;
            modified?: string;
            next_run?: string;
            open_pr_before_merge?: boolean | null;
            origin_client_id?: string;
            origin_machine_id?: string;
            origin_path?: string;
            parent_id?: string;
            path: string;
            placement_reasons?: components["schemas"]["PlacementReason"][] | null;
            priority: string;
            projectId?: string;
            remote_branch_policy?: string;
            requires_capability?: string[] | null;
            resolved_deps: string[] | null;
            resolved_workdir: string;
            resume_executor_override?: string;
            resume_injected_context?: string;
            resume_mode?: string;
            resume_prefer_same_session?: boolean;
            resume_requested?: boolean;
            resume_requested_at?: string;
            retry?: components["schemas"]["AutomationRetry"] | null;
            run_once_at?: string;
            runs?: components["schemas"]["CronRun"][] | null;
            schedule?: string;
            schedule_enabled?: boolean | null;
            sessions?: {
                [key: string]: components["schemas"]["SessionInfo"];
            } | null;
            starts_at?: string;
            status: string;
            tags?: string[] | null;
            target_workdir?: string;
            timezone?: string;
            title: string;
            trigger?: components["schemas"]["TriggerConfig"] | null;
            undispatchable_reason?: string;
            unresolved_deps: string[] | null;
            unresolved_feature_deps?: string[] | null;
            user_original_request?: string;
            waiting_on: string[] | null;
            waiting_on_features?: string[] | null;
            workdir: string;
        };
        RunFinalization: {
            finalized_at: string;
            session_id?: string;
            status: string;
        };
        SearchRequest: {
            feature_id?: string;
            global?: boolean | null;
            include?: string[] | null;
            limit?: number | null;
            priority?: string;
            project?: string;
            projects?: string[] | null;
            query: string;
            status?: string;
            strategy?: string;
            tags?: string[] | null;
            type?: string;
        };
        SearchResponse: {
            results: components["schemas"]["SearchResult"][] | null;
            total: number;
        };
        SearchResult: {
            attachments?: components["schemas"]["AttachmentReference"][] | null;
            id: string;
            match_source?: string;
            path: string;
            snippet: string;
            status: string;
            title: string;
            type: string;
        };
        SessionInfo: {
            cron_id?: string;
            hostname?: string;
            machine_id?: string;
            parent_id?: string;
            run_id?: string;
            runner_id?: string;
            timestamp: string;
            workdir?: string;
        };
        TaskListResponse: {
            count: number;
            cycles?: (string[] | null)[] | null;
            stats?: components["schemas"]["TaskStats"] | null;
            tasks: components["schemas"]["ResolvedTask"][] | null;
        };
        TaskStats: {
            blocked: number;
            not_pending: number;
            ready: number;
            status_blocked: number;
            total: number;
            waiting: number;
        };
        TriggerConfig: {
            cooldown?: string;
            event?: string;
            events?: string[] | null;
            filter?: {
                [key: string]: string;
            } | null;
            ignore_automation_events?: boolean | null;
            max_concurrent?: number;
            once_per?: string;
            schedule?: string;
            timezone?: string;
            type?: string;
            webhook?: string;
        };
        UpdateEntryRequest: {
            action?: components["schemas"]["AutomationAction"] | null;
            agent?: string | null;
            append?: string | null;
            attachments?: (components["schemas"]["AttachmentReference"][] | null) | null;
            automation_run_id?: string | null;
            checkout_mode?: string | null;
            complete_on_idle?: boolean | null;
            content?: string | null;
            delivery_mode?: string | null;
            depends_on?: (string[] | null) | null;
            direct_prompt?: string | null;
            execution_mode?: string | null;
            executor?: string | null;
            expected_revision?: string;
            expires_at?: string | null;
            extensions?: (string[] | null) | null;
            feature_depends_on?: (string[] | null) | null;
            feature_expires_at?: string | null;
            feature_id?: string | null;
            feature_priority?: string | null;
            feature_run_once_at?: string | null;
            feature_schedule?: string | null;
            feature_starts_at?: string | null;
            feature_timezone?: string | null;
            generated?: boolean | null;
            generated_by?: string | null;
            generated_key?: string | null;
            generated_kind?: string | null;
            git_branch?: string | null;
            git_remote?: string | null;
            goal?: components["schemas"]["GoalConfig"] | null;
            machine_affinity?: string | null;
            max_runs?: number | null;
            merge_policy?: string | null;
            merge_strategy?: string | null;
            merge_target_branch?: string | null;
            model?: string | null;
            next_run?: string | null;
            note?: string | null;
            open_pr_before_merge?: boolean | null;
            origin_client_id?: string | null;
            origin_machine_id?: string | null;
            origin_path?: string | null;
            priority?: string | null;
            reminder?: components["schemas"]["ReminderConfig"] | null;
            remote_branch_policy?: string | null;
            retry?: components["schemas"]["AutomationRetry"] | null;
            run_finalizations?: {
                [key: string]: components["schemas"]["RunFinalization"];
            } | null;
            run_once_at?: string | null;
            runs?: components["schemas"]["CronRun"][] | null;
            schedule?: string | null;
            schedule_enabled?: boolean | null;
            sessions?: {
                [key: string]: components["schemas"]["SessionInfo"];
            } | null;
            starts_at?: string | null;
            status?: string | null;
            tags?: string[] | null;
            target_workdir?: string | null;
            timezone?: string | null;
            title?: string | null;
            trigger?: components["schemas"]["TriggerConfig"] | null;
            user_original_request?: string | null;
            workdir?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "health.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server health (not script availability) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    "entries.list": {
        parameters: {
            query?: {
                project?: string;
                type?: string;
                status?: string;
                tags?: string;
                feature_id?: string;
                limit?: number;
                offset?: number;
                global?: boolean;
                sortBy?: string;
                sortOrder?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of entries; truncated is not end-of-pagination */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEntriesResponse"];
                };
            };
        };
    };
    "entries.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntryRequest"];
            };
        };
        responses: {
            /** @description Persisted entry */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateEntryResponse"];
                };
            };
        };
    };
    "entries.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry, including current revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainEntry"];
                };
            };
        };
    };
    "entries.delete": {
        parameters: {
            query: {
                confirm: true;
                force?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry deleted; no response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "entries.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEntryRequest"];
            };
        };
        responses: {
            /** @description Updated entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainEntry"];
                };
            };
        };
    };
    "search.query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Matching entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    "tasks.list": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resolved tasks and dependencies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
        };
    };
    "tasks.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resolved task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedTask"];
                };
            };
        };
    };
}
