package main

import (
	"fmt"
	"strings"
)

const mainHelp = `brain - Unified Brain CLI

Manage the Brain API server, runner, MCP mode, tokens, and plugin integration.

USAGE:
  brain <command> [subcommand] [flags] [args]
  brain help <command>

CORE COMMANDS:
  api                            Run API server in foreground
  api start                      Start API server (optionally with --runner)
  api stop                       Stop daemonized server
  api restart                    Restart daemonized server
  api status                     Show server process status
  api logs                       Show server logs
  api health                     Call /api/v1/health

RUNNER COMMANDS:
  start [project|all]            Open runner TUI (default project: all)
  start [project|all] --monitor  Monitor-only TUI (no local runner)
  run <subcommand> [project]     Runner management subcommands
  runner <subcommand> [project]  Alias for run

SETUP & DIAGNOSTICS:
  init                           Initialize brain directory and templates
  doctor                         Diagnose or fix local brain setup
  config                         Print resolved runtime config

INTEGRATION:
  mcp                            Run MCP stdio server
  install <target>               Install plugin for target app
  uninstall <target>             Uninstall plugin from target app
  plugin-status                  Check plugin installation status

TOKENS:
  token create --name <name>     Create API token
  token list                     List API tokens
  token revoke <name>            Revoke API token

ENTRIES:
  save                           Create a new brain entry
  get <id-or-path>               Read a brain entry (cat is an alias)
  update <id> --status <s>       Update an existing entry
  edit <id-or-path>              Open entry in $EDITOR for editing
  search <query>                 Search brain entries
  list                           List brain entries with filters
  embeddings backfill            Generate missing/stale embeddings

ATTACHMENTS:
  attachments upload <path>       Upload a file to a project
  attachments attach <entry> <id> Attach an existing attachment to an entry
  attachments list                List project or entry attachments
  attachments download <id>       Download original bytes and verify SHA256
  attachments extract <id>        Extract derived searchable text
  attachments backfill            Backfill derived text for project attachments
  attachments delete <id>         Delete an unreferenced attachment

AUTOMATIONS:
  automation                     List automations
  automation create              Create automation (interactive wizard)
  automation test <event>        Simulate event (dry-run)
  automation enable <id>         Enable an automation
  automation disable <id>        Disable an automation
  automation history <id>        List tasks generated by automation
  automation goal                Manage goals (goals-as-automations)
  automation goal set <p> <obj>  Create a goal automation
  automation goal list [p]       List goal automations
  automation goal run <p> <id>   Reconcile a goal now (alias: reconcile)
  goal <sub>                     Deprecated alias for 'automation goal <sub>'

MIGRATION:
  migrate automations            Convert hardcoded monitors to automation entries

DREAM MODE:
  dream                          List dream-enabled projects
  dream <project>                Print dream content for project
  dream <project> --enable       Enable dream mode for project
  dream <project> --disable      Disable dream mode for project

GLOBAL HELP:
  -h, --help                     Show help for current command

EXAMPLES:
  brain start
  brain start my-project --max-parallel 5
  brain start all --monitor
  brain api --port 3000
  brain api start --dry-run
  brain api logs -f -n 200
  brain token create --name dev
  brain save --type task --title "Fix auth bug"
  brain edit abc12def
  brain edit -i --type task
  brain help run
`

const embeddingsHelp = `brain embeddings - Generate semantic-search embeddings

USAGE:
  brain embeddings backfill [flags]

SUBCOMMANDS:
  backfill                       Embed matching notes that are missing or stale

FLAGS:
  --project <id>                 Only embed entries in a project
  --all                          Embed entries across all brains/projects (default)
  --path <prefix>                Only embed entries with this path prefix
  --force                        Re-embed matching entries even if already current
  --dry-run                      Show entries that would be embedded
  -v, --verbose                  Show configuration and detailed entries
  -h, --help                     Show this help

EXAMPLES:
  brain embeddings backfill --project brain-api
  brain embeddings backfill --all
  brain embeddings backfill --project brain-api --force
  brain embeddings backfill --dry-run --verbose
`

const attachmentsHelp = `brain attachments - Manage first-class binary attachments

USAGE:
  brain attachments upload <path> --project <project> [--description <text>]
  brain attachments attach <entry> <attachment-id> --project <project> [--role <role>] [--description <text>]
  brain attachments list --project <project> [--entry <entry>]
  brain attachments download <attachment-id> --project <project> [--output <path>]
  brain attachments extract <attachment-id> --project <project>
  brain attachments backfill --project <project> [--dry-run] [--force] [--batch-size <n>] [--rate-limit-ms <ms>]
  brain attachments detach <entry> <attachment-id> --project <project> [--role <role>]
  brain attachments delete <attachment-id> --project <project>

SUBCOMMANDS:
  upload <path>                   Upload a local file and print attachment metadata
  attach <entry> <attachment-id>  Attach an existing attachment to an entry
  list                            List project attachments or --entry attachments
  download <attachment-id>        Download exact original bytes and verify SHA256
  extract <attachment-id>         Extract derived text for search/indexing
  backfill                        Extract derived text for project attachments
  detach <entry> <attachment-id>  Remove an attachment reference from an entry
  delete <attachment-id>          Delete an unreferenced attachment from storage

FLAGS:
  -p, --project <project>         Project ID (required)
  -e, --entry <entry>             Entry ID/path for list
  -r, --role <role>               Attachment role for attach/detach
  -d, --description <text>        Description/caption metadata
  -o, --output <path>             Download destination (use - for stdout)
      --dry-run                   Preview backfill candidates without extracting
      --force                     Re-extract attachments that already have ready text
      --skip-ready                Skip attachments that already have ready text
      --batch-size <n>            Limit attachments processed in this run
      --rate-limit-ms <ms>        Delay between extraction requests
  -h, --help                      Show this help

EXAMPLES:
  brain attachments upload ./diagram.png --project brain-api
  brain attachments attach abc12def att_123 --project brain-api --role source --description "Design diagram"
  brain attachments list --project brain-api
  brain attachments list --project brain-api --entry abc12def
  brain attachments download att_123 --project brain-api --output diagram.png
  brain attachments extract att_123 --project brain-api
  brain attachments backfill --project brain-api --dry-run
  brain attachments detach abc12def att_123 --project brain-api --role source
  brain attachments delete att_123 --project brain-api
`

const apiHelp = `brain api - API server operations

USAGE:
  brain api [flags]
  brain api <subcommand> [flags]

SUBCOMMANDS:
  start                          Start daemon in background
  stop                           Stop daemon process
  restart                        Restart daemon process
  status                         Show daemon status
  logs                           Show/follow daemon logs
  health                         Query API health endpoint

FLAGS (brain api):
  -p, --port <port>              Listen port (foreground mode)
  --host <host>                  Listen host (foreground mode)
  -d, --daemon                   Run as daemon
  --log-file <path>              Log file path for daemon mode
  --tls                          Enable TLS (foreground mode)
  --tls-cert <path>              TLS certificate path
  --tls-key <path>               TLS private key path
  -h, --help                     Show this help

SUBCOMMAND HELP:
  brain help api start
  brain help api stop
  brain help api restart
  brain help api status
  brain help api logs
  brain help api health

EXAMPLES:
  brain api
  brain api --port 4000 --host 0.0.0.0
  brain api --tls --tls-cert cert.pem --tls-key key.pem
  brain api start
  brain api status
`

const apiStartHelp = `brain api start - Start API server lifecycle

USAGE:
  brain api start [flags]

FLAGS:
  --pid-file <path>              PID file path override
  --log-file <path>              Log file path override
  -d, --daemon                   Run as a background daemon
  --port <n>                     Server port override
  --host <host>                  Server bind host override
  --runner                       Start an embedded headless task runner
  --runner-project <project|all> Embedded runner project (default: all)
  --max-parallel <n>             Embedded runner max parallel tasks
  -i, --include <pattern>        Include project glob for --runner-project all
  -e, --exclude <pattern>        Exclude project glob for --runner-project all
  --executor <name>              Embedded runner executor override
  --dry-run                      Show what would start, do not execute
  -h, --help                     Show this help

NOTES:
  - Without --runner, existing API-only behavior is unchanged.
  - With --runner, the API and runner share one process lifecycle.
  - If the API binds to 0.0.0.0, ::, [::], or an empty host, the embedded
    runner connects to localhost instead of the bind wildcard.
  - The runner URL uses http unless server TLS is enabled, then https.
  - Hosted/domain deployments should set runner.brain_api_url or BRAIN_API_URL
    explicitly when the runner must connect through the public domain.

EXAMPLES:
  brain api start
  brain api start --runner
  brain api start --runner --runner-project personal-productivity
  brain api start --runner --daemon
  brain api start --host 0.0.0.0 --port 3333 --runner
  brain api start --dry-run --runner
`

const apiStopHelp = `brain api stop - Stop daemonized API server

USAGE:
  brain api stop [flags]
  brain stop [flags]

FLAGS:
  --pid-file <path>              PID file path override
  --timeout <sec>                Graceful shutdown timeout (default: 10)
  -f, --force                    Send SIGKILL after timeout
  --dry-run                      Show what would stop, do not execute
  -h, --help                     Show this help

EXAMPLES:
  brain api stop
  brain api stop --timeout 30
  brain api stop --force
`

const apiRestartHelp = `brain api restart - Restart daemonized API server

USAGE:
  brain api restart [flags]

FLAGS:
  --pid-file <path>              PID file path override
  --log-file <path>              Log file path override for next start
  --timeout <sec>                Graceful stop timeout (default: 10)
  -f, --force                    Force kill when stop times out
  --dry-run                      Show what would restart, do not execute
  -h, --help                     Show this help

EXAMPLES:
  brain api restart
  brain api restart --timeout 20 --force
`

const apiStatusHelp = `brain api status - Show daemon status

USAGE:
  brain api status [flags]

FLAGS:
  --json                         JSON output
  -h, --help                     Show this help

EXAMPLES:
  brain api status
  brain api status --json
`

const apiLogsHelp = `brain api logs - Show or follow daemon logs

USAGE:
  brain api logs [flags]

FLAGS:
  -f, --follow                   Stream new log lines
  -n, --lines <n>                Number of lines to show (default: 100)
  --since <duration>             Filter by recency (e.g. 30m, 2h, 1d)
  --level <level>                Filter by level: debug|info|warn|error
  -h, --help                     Show this help

EXAMPLES:
  brain api logs
  brain api logs -n 300
  brain api logs --since 2h --level error
  brain api logs -f --level warn
`

const apiHealthHelp = `brain api health - Query API health endpoint

USAGE:
  brain api health [flags]

FLAGS:
  --wait                         Wait until healthy
  --timeout <sec>                Wait timeout in seconds (default: 30)
  -h, --help                     Show this help

EXAMPLES:
  brain api health
  brain api health --wait --timeout 60
`

const startHelp = `brain start - Open the dashboard TUI

By default this opens a monitor-only TUI (no local runner) — it shows tasks,
brain entries, automations, runners, and lets you drive runners remotely. Pass
--runner to also run a local runner in the same process that claims and executes
tasks. To run a runner detached in the background instead, use ` + "`brain runner start`" + `.

USAGE:
  brain start                         Monitor-only TUI for all projects
  brain start <project>               Monitor-only TUI for one project
  brain start <project> --runner      TUI + a local runner
  brain start all [filters]

FLAGS:
  --runner                       Also run a local runner alongside the TUI
  --tui                          TUI mode (default behavior)
  --monitor                      Monitor-only TUI (no local runner; the default)
  -f, --foreground               Foreground mode without TUI
  -b, --headless                 Headless mode (no TUI, no tmux)
  --dashboard                    Dashboard mode
  -p, --max-parallel <n>         Override max parallel tasks
  --poll-interval <sec>          Override poll interval
  -w, --workdir <dir>            Override execution workdir
  --agent <name>                 Override OpenCode agent
  -m, --model <name>             Override OpenCode model
  -i, --include <pattern>        Include projects (repeatable)
  -e, --exclude <pattern>        Exclude projects (repeatable)
  -F, --feature-id <id>          Limit execution to feature IDs (repeatable)
  --follow                       Follow logs mode
  -h, --help                     Show this help

MONITOR MODE:
  The --monitor flag launches the TUI as a pure remote control panel.
  No local task runner is started. The TUI connects to the Brain API
  via SSE for real-time task updates and uses HTTP API for actions
  like pause/resume and task execution (priority bump).

EXAMPLES:
  brain start
  brain start my-project
  brain start my-project --monitor
  brain start all --monitor
  brain start all -i 'prod-*' -e 'legacy-*'
  brain start all --max-parallel 5 --poll-interval 3
`

const runnerHelp = `brain runner - Background task runner

Run a runner on a machine that registers with the Brain API and claims/executes
tasks. By default it daemonizes (detaches into the background); the runner then
appears under the Control tab in the web UI for remote interaction.

USAGE:
  brain runner start [project|all]    Start a background runner (daemonized)
  brain runner start <p> --foreground Run a headless runner in this terminal
  brain runner stop                   Stop the background runner
  brain runner status                 Show whether a runner is running

FLAGS:
  --foreground                   Run headless in the foreground (don't detach)
  -p, --max-parallel <n>         Max parallel tasks
  -i, --include <pattern>        Include projects (repeatable)
  -e, --exclude <pattern>        Exclude projects (repeatable)
  --executor <name>              Default executor (opencode or pi)
  -h, --help                     Show this help

See also: brain start --runner (TUI + a local runner), brain run (granular).
`

const runHelp = `brain run - Runner management commands

USAGE:
  brain run <subcommand> [project|all] [flags]
  brain runner <subcommand> [project|all] [flags]

SUBCOMMANDS:
  start                          Start runner (implemented)
  stop                           Stop runner (placeholder)
  status                         Show runner status (placeholder)
  list                           List tasks (placeholder)
  ready                          List ready tasks (placeholder)
  features                       List features (placeholder)
  logs                           Stream runner logs (placeholder)
  config                         Show runner config (placeholder)

COMMON FLAGS:
  Same flags as: brain start --help

SUBCOMMAND HELP:
  brain help run start

EXAMPLES:
  brain run start
  brain run start my-project --foreground
  brain runner start all --max-parallel 4
`

const runStartHelp = `brain run start - Start runner via run command

USAGE:
  brain run start [project|all] [flags]

FLAGS:
  Same runner flags as: brain start

EXAMPLES:
  brain run start
  brain run start my-project --headless
`

const mcpHelp = `brain mcp - Start MCP stdio server

USAGE:
  brain mcp [flags]

FLAGS:
  --api-url <url>                Brain API URL
  -h, --help                     Show this help

EXAMPLES:
  brain mcp
  brain mcp --api-url http://localhost:3333
`

const initHelp = `brain init - Initialize brain directory structure

USAGE:
  brain init [flags]

FLAGS:
  -f, --force                    Overwrite existing templates/config
  --dry-run                      Show planned file operations only
  -h, --help                     Show this help

EXAMPLES:
  brain init
  brain init --dry-run
  brain init --force
`

const doctorHelp = `brain doctor - Diagnose and repair local setup

USAGE:
  brain doctor [flags]

FLAGS:
  --fix                          Apply automatic fixes where possible
  -f, --force                    Force replacement of generated files
  --dry-run                      Show changes without applying
  -v, --verbose                  Show all checks (including passes)
  --skip-version-check           Skip tool version checks
  -h, --help                     Show this help

EXAMPLES:
  brain doctor
  brain doctor -v
  brain doctor --fix
  brain doctor --fix --dry-run
`

const configHelp = `brain config - Show or initialize configuration

USAGE:
  brain config
  brain config defaults
  brain config init [--print] [--force]

SUBCOMMANDS:
  defaults                       Print full default config YAML to stdout
  init                           Write default config.yaml if it does not exist

FLAGS:
  --print                        Print default config YAML instead of writing
  -f, --force                    Overwrite existing config.yaml with init
                                 (prints a diff and saves a timestamped .bak first)

DESCRIPTION:
  Without a subcommand, prints resolved server, runner, and MCP settings.
  Use defaults/init to inspect or create ~/.config/brain/config.yaml safely.
  init never touches an existing config.yaml unless --force is given; a
  forced overwrite always writes config.yaml.bak-<timestamp> alongside it.

EXAMPLES:
  brain config
  brain config defaults
  brain config init --print
  brain config init
`

const installHelp = `brain install - Install brain plugin integration

USAGE:
  brain install <target> [flags]

TARGETS:
  opencode                       Install OpenCode integration
  claude                         Install brain skills for Claude Code (~/.claude/skills)
  pi                             Install Pi agent bundles and extensions (~/.pi)

FLAGS:
  -f, --force                    Overwrite existing target files
  --dry-run                      Show planned changes only
  --api-url <url>                API URL to embed in generated config
  -h, --help                     Show this help

EXAMPLES:
  brain install opencode
  brain install claude
  brain install claude --dry-run
  brain install opencode --api-url http://localhost:3333
`

const uninstallHelp = `brain uninstall - Remove brain plugin integration

USAGE:
  brain uninstall <target>

TARGETS:
  opencode                       Remove OpenCode integration
  claude                         Remove brain skills from Claude Code
  pi                             Remove Pi agent bundles and extensions

EXAMPLES:
  brain uninstall opencode
  brain uninstall claude
`

const pluginStatusHelp = `brain plugin-status - Check plugin installation state

USAGE:
  brain plugin-status

DESCRIPTION:
  Reports whether each known target is installed, incomplete,
  unavailable on this machine, or missing.

EXAMPLES:
  brain plugin-status
`

const tokenHelp = `brain token - API token management

USAGE:
  brain token <subcommand> [flags] [args]

SUBCOMMANDS:
  create --name <name>           Create token
  list                           List tokens
  revoke <name>                  Revoke token by name

EXAMPLES:
  brain token create --name dev
  brain token list
  brain token revoke dev
`

const tokenCreateHelp = `brain token create - Create API token

USAGE:
  brain token create --name <name> [--scope <scope>]
  brain token create <name>

FLAGS:
  --name <name>                  Token name
  --scope <scope>                Token scope (default: admin:*)
                                 Values: admin:*, runner:*, read:*, control:*
  -h, --help                     Show this help

SCOPES:
  admin:*                        Full access to all endpoints
  runner:*                       Runner operations (claim/release/heartbeat) + read
  read:*                         Read-only access to entries and tasks
  control:*                      Remote control: attach to / spawn OpenCode instances

EXAMPLES:
  brain token create --name dev
  brain token create --name runner-1 --scope runner:*
  brain token create --name monitoring --scope read:*
  brain token create ci-bot
`

const tokenListHelp = `brain token list - List API tokens

USAGE:
  brain token list

EXAMPLES:
  brain token list
`

const tokenRevokeHelp = `brain token revoke - Revoke API token

USAGE:
  brain token revoke <name>

EXAMPLES:
  brain token revoke dev
`

const dreamHelp = `brain dream - Dream mode management

USAGE:
  brain dream
  brain dream <project>
  brain dream <project> --enable [--schedule "<cron>"]
  brain dream <project> --disable
  brain dream <project> --now

DESCRIPTION:
  Manage dream mode (knowledge consolidation) for projects.
  Dream mode periodically consolidates and synthesizes project knowledge.
  Use --now to trigger consolidation immediately on demand.

FLAGS:
  --enable                       Enable dream mode for project
  --disable                      Disable dream mode for project
  --now                          Trigger dream consolidation immediately
  --schedule "<cron>"            Custom cron schedule (with --enable)
  -h, --help                     Show this help

EXAMPLES:
  brain dream
  brain dream my-project
  brain dream my-project --enable
  brain dream my-project --enable --schedule "0 6 * * *"
  brain dream my-project --disable
  brain dream my-project --now
  brain dream my-project --enable --now
`

const saveHelp = `brain save - Create a new brain entry

USAGE:
  brain save --type <type> --title <title> [flags]

DESCRIPTION:
  Creates a new brain entry. Opens $EDITOR by default for content entry
  (zk-inspired pattern). Supports inline content, stdin, and file input
  for automation.

REQUIRED FLAGS:
  --type <type>                  Entry type (task, plan, decision, etc.)
  --title <title>                Entry title

CONTENT FLAGS:
  --content <text>               Inline content
  --content -                    Read content from stdin
  --content @<path>              Read content from file
  --no-edit                      Skip opening $EDITOR

OPTIONAL FLAGS:
  --tags <t1,t2,...>             Comma-separated tags
  --status <status>              Initial status (default: active, tasks: draft)
  --priority <level>             Priority: high, medium, low
  --depends-on <id1,id2,...>     Comma-separated task dependency IDs
  --feature-id <id>              Feature group identifier
  --global                       Save to global brain (not project-scoped)
  --project <name>               Override auto-detected project
  -h, --help                     Show this help

EDITOR:
  Uses $VISUAL, then $EDITOR, then vi as fallback.
  Save and quit to create the entry. Empty content cancels.

EXAMPLES:
  brain save --type task --title "Fix auth bug"
  brain save --type task --title "Fix auth bug" --content "Description" --no-edit
  echo "content" | brain save --type task --title "My Task" --content - --no-edit
  brain save --type plan --title "Q2 Roadmap" --content @roadmap.md --no-edit
  brain save --type task --title "Fix" --priority high --tags "bug,auth"
  brain save --type learning --title "Go patterns" --global
`

const updateHelp = `brain update - Update an existing brain entry

USAGE:
  brain update <id-or-path> [flags]

DESCRIPTION:
  Updates an existing brain entry. Supports metadata changes (status, tags,
  priority), content replacement (inline, stdin, file), and content append.
  Enables powerful pipe-based editing: brain get id | sed | brain update id --content -

REQUIRED:
  <id-or-path>                   Entry ID (8-char) or full brain path

UPDATE FLAGS:
  --status <status>              New status (draft, pending, active, in_progress,
                                 blocked, completed, validated, superseded, archived)
  --title <title>                New title
  --content <text>               Replace content (inline text)
  --content -                    Replace content from stdin
  --content @<path>              Replace content from file
  --append <text>                Append to existing content
  --note <text>                  Timestamped status-change note
  --tags <t1,t2,...>             Comma-separated tags (replaces existing)
  --priority <level>             Priority: high, medium, low
  --depends-on <id1,id2,...>     Comma-separated task dependency IDs
  --feature-id <id>              Feature group identifier
  -h, --help                     Show this help

RULES:
  - At least one flag must be provided
  - --content and --append are mutually exclusive
  - Multiple flags can be combined in one call

EXAMPLES:
  brain update abc12def --status completed
  brain update abc12def --status blocked --note "Waiting on API design"
  brain update abc12def --append "## Progress\n- Done with auth module"
  brain update abc12def --title "New Title" --priority high
  brain update abc12def --tags "api,auth,v2"
  brain update abc12def --depends-on "task1,task2"
  brain update abc12def --content -           # Read from stdin
  brain update abc12def --content @file.md    # Read from file
  brain get abc12def | sed 's/old/new/g' | brain update abc12def --content -
`

const getHelp = `brain get - Read a brain entry

USAGE:
  brain get <id-or-path> [--format <format>]
  brain cat <id-or-path> [--format <format>]

DESCRIPTION:
  Read a brain entry by short ID or full path. "cat" is an alias for "get".
  TTY-aware: shows formatted metadata + content in terminal, raw markdown
  when piped.

POSITIONAL:
  <id-or-path>                   Entry short ID (8-char) or full brain path

FLAGS:
  --format <format>              Output format (see below)
  -q, --quiet                    Suppress metadata/counts
  --no-color                     Disable color output
  -h, --help                     Show this help

NAMED FORMATS:
  path                           Just the entry path
  id                             Just the short ID
  short                          Compact one-line summary
  full                           YAML frontmatter + body (on-disk format)
  json                           Full JSON representation
  jsonl                          Single JSON line

CUSTOM TEMPLATES:
  --format "{{.Title}}"                    Just the title
  --format "{{.Title}} [{{.Status}}]"      Title with status
  --format "{{.Path}}"                     Just the path

TTY BEHAVIOR:
  Interactive terminal:           Metadata header + content
  Piped (non-TTY):               Raw markdown body only

EXAMPLES:
  brain get abc12def
  brain cat abc12def
  brain get abc12def --format json
  brain get abc12def --format full
  brain get abc12def --format path
  brain get abc12def --format id
  brain get abc12def --format "{{.Title}} [{{.Status}}]"
  brain get abc12def | wc -l
  brain get abc12def | grep "pattern"
  brain get abc12def | sed 's/old/new/g' | brain update abc12def --content -
`

const editHelp = `brain edit - Open brain entry in $EDITOR

USAGE:
  brain edit <id-or-path>
  brain edit -i [filters]

DESCRIPTION:
  Opens a brain entry in your $EDITOR with full YAML frontmatter and
  markdown body. All frontmatter fields are editable. On save, changes
  are diffed against the original and sent back via the API.

POSITIONAL:
  <id-or-path>                   Entry short ID (8-char) or full brain path

FLAGS:
  -i, --interactive              Use fzf to select entry interactively
  --force                        Skip safety confirmations
  --type <type>                  Filter by entry type (with -i)
  --status <status>              Filter by status (with -i)
  --tags <tags>                  Filter by tags (with -i)
  --priority <priority>          Filter by priority (with -i)
  --feature-id <id>              Filter by feature ID (with -i)
  --limit <n>                    Max filter results (default: 20)
  --no-color                     Disable color output
  -h, --help                     Show this help

EDITOR:
  Uses $VISUAL, then $EDITOR, then vi as fallback.
  Save and quit to apply changes. No changes = no API call.

DANGEROUS CHANGES:
  Modifying type or project triggers a confirmation prompt.
  Use --force to skip all confirmations.

EXAMPLES:
  brain edit abc12def
  brain edit projects/brain-api/task/abc12def.md
  brain edit -i --type task
  brain edit -i --type task --status active
  brain edit -i --type task --status active --force
`

const searchHelp = `brain search - Search brain entries

USAGE:
  brain search <query> [flags]

FLAGS:
  --type <type>                  Filter by entry type (task, plan, note, etc.)
  --status <status>              Filter by status (active, pending, completed, etc.)
  --tags <tags>                  Comma-separated tags to filter by
  --priority <priority>          Filter by priority (high, medium, low)
  --feature-id <id>              Filter by feature ID
  --limit <n>                    Max results (default: 20)
  --sort <field>                 Sort by: created, modified, priority
  --format <fmt>                 Output: path, id, short, full, json, jsonl, or Go template
  -q, --quiet                    Suppress "Found N entries" count
  --no-color                     Disable color output
  -0                             NUL-delimited output (for xargs -0)
  -i, --interactive              Post-filter with fzf
  -h, --help                     Show this help

FORMATS:
  path    One path per line (default when piped)
  id      One ID per line
  short   Table: title, path, status, priority (default in terminal)
  full    Frontmatter-style metadata + body
  json    JSON array
  jsonl   One JSON object per line

EXAMPLES:
  brain search "auth module"
  brain search "auth" --type task --status active --limit 5
  brain search "auth" --format json
  brain search "auth" --format path -0 | xargs -0 brain get
  brain search "auth" -i
`

const listHelp = `brain list - List brain entries

USAGE:
  brain list [flags]

FLAGS:
  --type <type>                  Filter by entry type (task, plan, note, etc.)
  --status <status>              Filter by status (active, pending, completed, etc.)
  --tags <tags>                  Comma-separated tags to filter by
  --priority <priority>          Filter by priority (high, medium, low)
  --feature-id <id>              Filter by feature ID
  --limit <n>                    Max results (default: 20)
  --sort <field>                 Sort by: created, modified, priority
  -m, --match <query>            Search query filter
  --format <fmt>                 Output: path, id, short, full, json, jsonl, or Go template
  -q, --quiet                    Suppress "Found N entries" count
  --no-color                     Disable color output
  -0                             NUL-delimited output (for xargs -0)
  -i, --interactive              Post-filter with fzf
  -h, --help                     Show this help

EXAMPLES:
  brain list
  brain list --type task --status pending
  brain list --type task --feature-id auth-system
  brain list --tags "api,v2"
  brain list --sort modified
  brain list --format json
  brain list --format path -0 | xargs -0 brain get
  brain list -i --type task
`

const migrateHelp = `brain migrate - Migration tools for upgrading brain deployments

USAGE:
  brain migrate <subcommand> [flags]

SUBCOMMANDS:
  automations                    Convert hardcoded monitor tasks to automation entries
  goals                          Convert legacy V1 goals to goal automation entries

FLAGS:
  --dry-run                      Show what would be done without making changes
  --force                        Overwrite existing files / recreate existing entries
  --project <name>               Scope goal migration to a single project
  -h, --help                     Show this help

EXAMPLES:
  brain migrate automations
  brain migrate automations --dry-run
  brain migrate automations --force
  brain migrate goals
  brain migrate goals --dry-run
  brain migrate goals --project my-project
`

const migrateAutomationsHelp = `brain migrate automations - Convert hardcoded monitors to automation entries

USAGE:
  brain migrate automations [flags]

FLAGS:
  --dry-run                      Show what would be done without making changes
  --force                        Overwrite existing automation entry files
  -h, --help                     Show this help

DESCRIPTION:
  Migrates hardcoded monitor templates into automation entries stored in
  global/automation/ and installs the default built-in automations.

  Step 1: Deploys default automation entry files to global/automation/
  Step 2: Finds existing monitor tasks and disables their schedules

  Existing monitor tasks are preserved but disabled — they are NOT deleted.
  The new automation entries will be picked up by the AutomationMatcher
  when the API server restarts.

  If the brain API is not running, only Step 1 (file deployment) is performed.
  Run the command again when the API is running to complete Step 2.

EXAMPLES:
  brain migrate automations
  brain migrate automations --dry-run
  brain migrate automations --force
`

const migrateGoalsHelp = `brain migrate goals - Convert legacy V1 goals to goal automation entries

USAGE:
  brain migrate goals [flags]

FLAGS:
  --dry-run                      Show what would be done without making changes
  --force                        Recreate goal automations that already exist
  --project <name>               Scope migration to a single project
  -h, --help                     Show this help

DESCRIPTION:
  Migrates legacy V1 goals into the new goal automation model.

  A legacy goal is a "goal:plan" plan entry paired with an optional
  "goal:reconciler" task. This command converts each plan (and its paired
  reconciler) into a single goal automation entry (type=automation,
  generated_by=brain-goal) whose trigger fires on task/feature lifecycle
  events and whose action drives the in-process reconcile loop.

  Step 1: Lists legacy goal plans (and pairs their reconciler tasks by slug).
  Step 2: Converts each plan into a goal automation entry and creates it
          through the API, skipping goals that already have an automation
          (unless --force is given).
  Step 3: Archives the legacy plan and cancels the paired reconciler task,
          annotating each with a migration note.

  Legacy entries are preserved (archived/cancelled), not deleted. The command
  is idempotent: already-archived plans and already-disabled reconcilers are
  skipped.

  If the brain API is not running, the command prints a notice and exits
  without error. Run it again once the API is available.

EXAMPLES:
  brain migrate goals
  brain migrate goals --dry-run
  brain migrate goals --force
  brain migrate goals --project my-project
`

const automationHelp = `brain automation - Manage automations

USAGE:
  brain automation <subcommand> [id] [flags]

SUBCOMMANDS:
  create                         Interactive wizard to create an automation
  list                           List all automations (default)
  test <event-name>              Simulate an event (dry-run, no tasks created)
  enable <id>                    Enable an automation (set status to active)
  disable <id>                   Disable an automation (set status to archived)
  history <id>                   List tasks generated by an automation

FLAGS:
  --project <name>               Filter by project
  --format <fmt>                 Output format: json, short (default: table)
  --limit <n>                    Max results (default: 20)
  -q, --quiet                    Suppress summary counts
  -h, --help                     Show this help

TRIGGERS:
  event                           Fires on a brain event
  cron                            Fires on a schedule
  webhook                         Fires from an external webhook
  session                         Fires on runner session events

GUARDS:
  cooldown                        Minimum duration between generated tasks (e.g. 5m)
  max_concurrent                  Maximum active generated tasks allowed at once

EXAMPLES:
  brain automation
  brain automation list
  brain automation list --project my-project
  brain automation create
  brain automation test task.completed
  brain automation enable abc12def
  brain automation disable abc12def
  brain automation history abc12def
  brain automation list --format json
`

const automationCreateHelp = `brain automation create - Create an automation interactively

USAGE:
  brain automation create [flags]

FLAGS:
  --project <name>               Pre-set project scope
  -h, --help                     Show this help

DESCRIPTION:
  Opens an interactive wizard that walks you through:
  1. Automation name
  2. Trigger type (event, cron, webhook, session) and configuration
  3. Action type (prompt, script) and configuration
  4. Project scope
  5. Optional guards: cooldown and max_concurrent

TRIGGER TYPES:
  event                           Brain event name (e.g. task.completed)
  cron                            Cron schedule (e.g. 0 9 * * *)
  webhook                         Webhook path (e.g. /hooks/deploy)
  session                         Runner session event; defaults to runner.session_discovered

GUARDS:
  cooldown                        Optional Go duration such as 5m or 1h
  max_concurrent                  Optional positive integer concurrency cap

EXAMPLES:
  brain automation create
  brain automation create --project my-project
`

const automationTestHelp = `brain automation test - Simulate an event (dry-run)

USAGE:
  brain automation test <event-name> [flags]

FLAGS:
  --project <name>               Filter automations by project
  -h, --help                     Show this help

DESCRIPTION:
  Simulates the given event name against all active automations and
  shows which ones would match. No tasks are created (dry-run only).

EXAMPLES:
  brain automation test task.completed
  brain automation test entry.created --project my-project
`

const automationGoalHelp = `brain automation goal - Manage goals (goals-as-automations)

USAGE:
  brain automation goal <subcommand> [project] [id|objective] [flags]

SUBCOMMANDS:
  set <project> "<objective>"    Create a goal automation
  list [project]                 List goal automations
  show <project> <id>            Show a goal with linked-task progress
  edit <project> <id>            Update a goal's config/action
  run <project> <id>             Reconcile a goal now (alias: reconcile)
  reconcile <project> <id>       Alias for run
  pause <project> <id>           Pause a goal (status: blocked)
  resume <project> <id>          Resume a goal (status: active)
  archive <project> <id>         Archive a goal (status: archived)
  clear <project> <id>           Clear a goal (archive)
  validate <project> <id>        Validate goal progress against criteria

FLAGS:
  --feature <id>                 Scope the goal to a feature
  --title <text>                 Goal title (defaults to objective)
  --content <text>               Goal entry body
  --trigger-source <src>         Trigger source: task | feature | both
  --session-mode <mode>          Reconcile session mode: continue | fresh
  --agent <name>                 Agent for reconcile work
  --model <id>                   Model override for reconcile work
  --executor <name>              Executor hint (parsed; reserved)
  --workdir <path>               Working directory for generated work
  --criteria <text>              Success criterion (repeatable)
  --validate <cmd>               Validation command (repeatable)
  --status <status>              Status override (used by edit)
  --project <name>               Filter/scope by project
  --format <fmt>                 Output format: json (default: table)
  --limit <n>                    Max results (default: 20)
  -q, --quiet                    Suppress summary counts
  -h, --help                     Show this help

DESCRIPTION:
  A goal is an automation entry (type=automation, generated_by=brain-goal)
  that triggers on task and/or feature lifecycle events and drives a
  deterministic in-process reconcile loop. These commands operate over the
  goal API (/api/v1/goals).

EXAMPLES:
  brain automation goal set my-project "Ship the auth feature" --feature auth-system
  brain automation goal set my-project "Harden API" --criteria "all tests pass" --criteria "no lint errors"
  brain automation goal list my-project
  brain automation goal show my-project ship-the-auth-feature-a1b2c3d4
  brain automation goal run my-project ship-the-auth-feature-a1b2c3d4
  brain automation goal pause my-project ship-the-auth-feature-a1b2c3d4
  brain automation goal list --format json
`

const stopHelp = `brain stop - Alias for "brain api stop"

USAGE:
  brain stop [flags]

See: brain help api stop
`

func normalizeHelpTopic(command string) string {
	topic := strings.ToLower(strings.TrimSpace(command))
	topic = strings.Join(strings.Fields(topic), " ")
	if topic == "runner" {
		return "run"
	}
	if topic == "tokens" {
		return "token"
	}
	if topic == "cat" {
		return "get"
	}
	return topic
}

func ShowHelp(command string) {
	switch normalizeHelpTopic(command) {
	case "":
		fmt.Print(mainHelp)
	case "api":
		fmt.Print(apiHelp)
	case "api start":
		fmt.Print(apiStartHelp)
	case "api stop":
		fmt.Print(apiStopHelp)
	case "api restart":
		fmt.Print(apiRestartHelp)
	case "api status":
		fmt.Print(apiStatusHelp)
	case "api logs":
		fmt.Print(apiLogsHelp)
	case "api health":
		fmt.Print(apiHealthHelp)
	case "start":
		fmt.Print(startHelp)
	case "run":
		fmt.Print(runHelp)
	case "runner":
		fmt.Print(runnerHelp)
	case "run start":
		fmt.Print(runStartHelp)
	case "mcp":
		fmt.Print(mcpHelp)
	case "init":
		fmt.Print(initHelp)
	case "doctor":
		fmt.Print(doctorHelp)
	case "config":
		fmt.Print(configHelp)
	case "install":
		fmt.Print(installHelp)
	case "uninstall":
		fmt.Print(uninstallHelp)
	case "plugin-status":
		fmt.Print(pluginStatusHelp)
	case "token":
		fmt.Print(tokenHelp)
	case "token create":
		fmt.Print(tokenCreateHelp)
	case "token list":
		fmt.Print(tokenListHelp)
	case "token revoke":
		fmt.Print(tokenRevokeHelp)
	case "migrate":
		fmt.Print(migrateHelp)
	case "migrate automations":
		fmt.Print(migrateAutomationsHelp)
	case "migrate goals":
		fmt.Print(migrateGoalsHelp)
	case "automation":
		fmt.Print(automationHelp)
	case "automation create":
		fmt.Print(automationCreateHelp)
	case "automation test":
		fmt.Print(automationTestHelp)
	case "automation goal",
		"automation goal set",
		"automation goal list",
		"automation goal show",
		"automation goal edit",
		"automation goal run",
		"automation goal reconcile",
		"automation goal pause",
		"automation goal resume",
		"automation goal archive",
		"automation goal clear",
		"automation goal validate":
		fmt.Print(automationGoalHelp)
	case "goal":
		// Deprecated alias for "automation goal".
		fmt.Println("Note: 'brain goal' is deprecated; use 'brain automation goal' instead.")
		fmt.Println()
		fmt.Print(automationGoalHelp)
	case "attachments":
		fmt.Print(attachmentsHelp)
	case "dream":
		fmt.Print(dreamHelp)
	case "save":
		fmt.Print(saveHelp)
	case "get":
		fmt.Print(getHelp)
	case "update":
		fmt.Print(updateHelp)
	case "edit":
		fmt.Print(editHelp)
	case "search":
		fmt.Print(searchHelp)
	case "list":
		fmt.Print(listHelp)
	case "embeddings", "embeddings backfill":
		fmt.Print(embeddingsHelp)
	case "stop":
		fmt.Print(stopHelp)
	default:
		fmt.Printf("No help available for command: %s\n\n", command)
		fmt.Print(mainHelp)
	}
}
